# Generated by Django 4.2.7 on 2025-12-14 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import proposals.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estimates', '0001_initial'),
        ('objects', '0002_object_end_date_object_start_date_object_status'),
        ('accounting', '0004_legalentity_director_legalentity_director_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontOfWorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(help_text='Например: "Подвести электропитание к местам установки вентиляционного оборудования"', max_length=500, verbose_name='Описание работы')),
                ('category', models.CharField(blank=True, help_text='Например: "Электрика", "Строительство"', max_length=100, verbose_name='Категория')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Пункт фронта работ',
                'verbose_name_plural': 'Справочник фронта работ',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MountingCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(help_text='Например: "Проживание", "Инструмент", "Питание"', max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Подробное описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Условие для МП',
                'verbose_name_plural': 'Справочник условий для МП',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TechnicalProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('number', models.CharField(blank=True, help_text='Автоматически генерируется, если не указан', max_length=100, verbose_name='Номер ТКП')),
                ('outgoing_number', models.CharField(blank=True, help_text='Ручной ввод', max_length=100, verbose_name='Исходящий номер')),
                ('name', models.CharField(max_length=255, verbose_name='Название ТКП')),
                ('date', models.DateField(verbose_name='Дата ТКП')),
                ('object_area', models.PositiveIntegerField(blank=True, null=True, verbose_name='Площадь объекта, м²')),
                ('advance_required', models.TextField(blank=True, help_text='Текст с описанием аванса', verbose_name='Необходимый аванс')),
                ('work_duration', models.TextField(blank=True, help_text='Текст с описанием срока', verbose_name='Срок проведения работ')),
                ('validity_days', models.PositiveIntegerField(default=30, verbose_name='Срок действия предложения (дни)')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('in_progress', 'В работе'), ('checking', 'На проверке'), ('approved', 'Утверждено'), ('sent', 'Отправлено Заказчику'), ('agreed', 'Согласовано Заказчиком'), ('rejected', 'Отклонено')], default='draft', max_length=20, verbose_name='Статус')),
                ('file', models.FileField(blank=True, null=True, upload_to=proposals.models.tkp_file_path, verbose_name='Файл ТКП')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата утверждения')),
                ('version_number', models.PositiveIntegerField(default=1, verbose_name='Номер версии')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_tkps', to=settings.AUTH_USER_MODEL, verbose_name='Кто утвердил')),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_tkps', to=settings.AUTH_USER_MODEL, verbose_name='Кто проверил')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tkps', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('estimates', models.ManyToManyField(blank=True, related_name='technical_proposals', to='estimates.estimate', verbose_name='Привязанные сметы')),
                ('legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='technical_proposals', to='accounting.legalentity', verbose_name='Наша компания')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_proposals', to='objects.object', verbose_name='Объект')),
                ('parent_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_versions', to='proposals.technicalproposal', verbose_name='Предыдущая версия')),
            ],
            options={
                'verbose_name': 'ТКП',
                'verbose_name_plural': 'ТКП',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TKPEstimateSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=255, verbose_name='Название раздела')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('source_estimate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tkp_sections', to='estimates.estimate', verbose_name='Исходная смета')),
                ('source_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tkp_sections', to='estimates.estimatesection', verbose_name='Исходный раздел')),
                ('tkp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimate_sections', to='proposals.technicalproposal', verbose_name='ТКП')),
            ],
            options={
                'verbose_name': 'Раздел сметы в ТКП',
                'verbose_name_plural': 'Разделы смет в ТКП',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TKPEstimateSubsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=255, verbose_name='Название подраздела')),
                ('materials_sale', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Материалы — продажа')),
                ('works_sale', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Работы — продажа')),
                ('materials_purchase', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Материалы — закупка')),
                ('works_purchase', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Работы — закупка')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='proposals.tkpestimatesection', verbose_name='Раздел')),
                ('source_subsection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tkp_subsections', to='estimates.estimatesubsection', verbose_name='Исходный подраздел')),
            ],
            options={
                'verbose_name': 'Подраздел сметы в ТКП',
                'verbose_name_plural': 'Подразделы смет в ТКП',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TKPCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(help_text='Например: "Материалы (Смета 1)", "Работы (Смета 1)"', max_length=200, verbose_name='Название')),
                ('purchase_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Сумма закупки')),
                ('sale_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Сумма продажи')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('source_characteristic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tkp_characteristics', to='estimates.estimatecharacteristic', verbose_name='Исходная характеристика')),
                ('source_estimate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tkp_characteristics', to='estimates.estimate', verbose_name='Исходная смета')),
                ('tkp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='proposals.technicalproposal', verbose_name='ТКП')),
            ],
            options={
                'verbose_name': 'Характеристика ТКП',
                'verbose_name_plural': 'Характеристики ТКП',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MountingProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('number', models.CharField(blank=True, help_text='Автоматически генерируется, если не указан', max_length=100, verbose_name='Номер МП')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('date', models.DateField(verbose_name='Дата МП')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Итоговая сумма')),
                ('man_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Человеко-часы')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано'), ('sent', 'Отправлено Исполнителю'), ('approved', 'Согласовано'), ('rejected', 'Отклонено')], default='draft', max_length=20, verbose_name='Статус')),
                ('file', models.FileField(blank=True, null=True, upload_to=proposals.models.mp_file_path, verbose_name='Файл МП')),
                ('telegram_published', models.BooleanField(default=False, verbose_name='Опубликовано в Telegram')),
                ('telegram_published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации в Telegram')),
                ('version_number', models.PositiveIntegerField(default=1, verbose_name='Номер версии')),
                ('conditions', models.ManyToManyField(blank=True, related_name='mounting_proposals', to='proposals.mountingcondition', verbose_name='Условия')),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mounting_proposals', to='accounting.counterparty', verbose_name='Исполнитель')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_mps', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('mounting_estimate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mounting_proposals', to='estimates.mountingestimate', verbose_name='Монтажная смета')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mounting_proposals', to='objects.object', verbose_name='Объект')),
                ('parent_tkp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mounting_proposals', to='proposals.technicalproposal', verbose_name='Родительское ТКП')),
                ('parent_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_versions', to='proposals.mountingproposal', verbose_name='Предыдущая версия')),
            ],
            options={
                'verbose_name': 'МП',
                'verbose_name_plural': 'МП',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TKPFrontOfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('when_text', models.TextField(blank=True, help_text='Текстовое описание срока выполнения', verbose_name='Когда (текст)')),
                ('when_date', models.DateField(blank=True, help_text='Конкретная дата выполнения', null=True, verbose_name='Когда (дата)')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('front_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tkp_usages', to='proposals.frontofworkitem', verbose_name='Пункт из справочника')),
                ('tkp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='front_of_work', to='proposals.technicalproposal', verbose_name='ТКП')),
            ],
            options={
                'verbose_name': 'Пункт фронта работ в ТКП',
                'verbose_name_plural': 'Фронт работ в ТКП',
                'ordering': ['sort_order', 'id'],
                'unique_together': {('tkp', 'front_item')},
            },
        ),
    ]
