# Generated by Django 4.2.7 on 2026-02-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='mountingproposal',
            index=models.Index(fields=['date'], name='proposals_m_date_bac8f8_idx'),
        ),
        migrations.AddIndex(
            model_name='mountingproposal',
            index=models.Index(fields=['status', 'date'], name='proposals_m_status_2c1d04_idx'),
        ),
        migrations.AddIndex(
            model_name='mountingproposal',
            index=models.Index(fields=['object', 'status'], name='proposals_m_object__b5d154_idx'),
        ),
        migrations.AddIndex(
            model_name='mountingproposal',
            index=models.Index(fields=['counterparty', 'status'], name='proposals_m_counter_6050d8_idx'),
        ),
        migrations.AddIndex(
            model_name='technicalproposal',
            index=models.Index(fields=['date'], name='proposals_t_date_5f4687_idx'),
        ),
        migrations.AddIndex(
            model_name='technicalproposal',
            index=models.Index(fields=['status', 'date'], name='proposals_t_status_4331f6_idx'),
        ),
        migrations.AddIndex(
            model_name='technicalproposal',
            index=models.Index(fields=['object', 'status'], name='proposals_t_object__aed96b_idx'),
        ),
        migrations.AddIndex(
            model_name='technicalproposal',
            index=models.Index(fields=['legal_entity', 'status'], name='proposals_t_legal_e_730cfe_idx'),
        ),
    ]
