# Generated by Django 4.2.7 on 2026-02-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0001_initial'),
        ('proposals', '0002_mountingproposal_proposals_m_date_bac8f8_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mountingproposal',
            name='mounting_estimate',
        ),
        migrations.AddField(
            model_name='frontofworkitem',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Автоматически выбирается при создании ТКП', verbose_name='По умолчанию'),
        ),
        migrations.AddField(
            model_name='mountingcondition',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Автоматически выбирается при создании МП', verbose_name='По умолчанию'),
        ),
        migrations.AddField(
            model_name='mountingproposal',
            name='mounting_estimates',
            field=models.ManyToManyField(blank=True, related_name='mounting_proposals', to='estimates.mountingestimate', verbose_name='Монтажные сметы'),
        ),
    ]
