# Generated by Django 4.2.7 on 2026-01-04 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0004_legalentity_director_legalentity_director_name_and_more'),
        ('payments', '0008_alter_payment_scan_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('code', models.CharField(help_text='Уникальный код категории (например: ventilation_fans)', max_length=100, unique=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('level', models.PositiveIntegerField(default=0, help_text='Автоматически рассчитывается при сохранении', verbose_name='Уровень вложенности')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория товаров',
                'verbose_name_plural': 'Категории товаров',
                'ordering': ['level', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
                ('normalized_name', models.CharField(db_index=True, help_text='Lowercase, без спецсимволов, для поиска', max_length=500, verbose_name='Нормализованное название')),
                ('default_unit', models.CharField(default='шт', max_length=20, verbose_name='Единица измерения по умолчанию')),
                ('is_service', models.BooleanField(default=False, help_text='Услуга, а не товар', verbose_name='Это услуга')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('verified', 'Проверен'), ('merged', 'Объединён'), ('archived', 'Архив')], default='new', max_length=20, verbose_name='Статус')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.category', verbose_name='Категория')),
                ('created_from_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_products', to='payments.payment', verbose_name='Создан из платежа')),
                ('merged_into', models.ForeignKey(blank=True, help_text='Если товар объединён с другим', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_products', to='catalog.product', verbose_name='Объединён в')),
            ],
            options={
                'verbose_name': 'Товар/Услуга',
                'verbose_name_plural': 'Товары/Услуги',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Цена за единицу')),
                ('unit', models.CharField(max_length=20, verbose_name='Единица измерения')),
                ('invoice_date', models.DateField(verbose_name='Дата счёта')),
                ('invoice_number', models.CharField(blank=True, max_length=100, verbose_name='Номер счёта')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_prices', to='accounting.counterparty', verbose_name='Поставщик')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_prices', to='payments.payment', verbose_name='Платёж-источник')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'История цены товара',
                'verbose_name_plural': 'История цен товаров',
                'ordering': ['-invoice_date'],
                'indexes': [models.Index(fields=['product', 'invoice_date'], name='catalog_pro_product_f60159_idx'), models.Index(fields=['counterparty'], name='catalog_pro_counter_df5ac9_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('alias_name', models.CharField(max_length=500, verbose_name='Альтернативное название')),
                ('normalized_alias', models.CharField(db_index=True, max_length=500, verbose_name='Нормализованный алиас')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='catalog.product', verbose_name='Товар')),
                ('source_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_aliases', to='payments.payment', verbose_name='Источник (платёж)')),
            ],
            options={
                'verbose_name': 'Синоним товара',
                'verbose_name_plural': 'Синонимы товаров',
                'unique_together': {('product', 'normalized_alias')},
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status'], name='catalog_pro_status_521020_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['normalized_name'], name='catalog_pro_normali_e11b72_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'status'], name='catalog_pro_categor_da0f0a_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent', 'is_active'], name='catalog_cat_parent__e2d7e1_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['code'], name='catalog_cat_code_f3eb51_idx'),
        ),
    ]
