# Generated by Django 4.2.7 on 2026-02-23 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricelists', '0007_workitem_required_grade_alter_workitem_grade'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductWorkMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('confidence', models.FloatField(default=1.0, help_text='1.0 = ручное сопоставление, 0.x = автоматическое', verbose_name='Уверенность')),
                ('source', models.CharField(choices=[('manual', 'Ручное сопоставление'), ('rule', 'По правилам категорий'), ('llm', 'Подобрано LLM')], default='manual', max_length=20, verbose_name='Источник')),
                ('usage_count', models.PositiveIntegerField(default=1, verbose_name='Количество использований')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_mappings', to='catalog.product', verbose_name='Товар')),
                ('work_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_mappings', to='pricelists.workitem', verbose_name='Работа из прайс-листа')),
            ],
            options={
                'verbose_name': 'Сопоставление товар → работа',
                'verbose_name_plural': 'Сопоставления товар → работа',
                'ordering': ['-usage_count', '-confidence'],
                'indexes': [models.Index(fields=['product', '-usage_count'], name='catalog_pro_product_09184e_idx')],
                'unique_together': {('product', 'work_item')},
            },
        ),
    ]
