# Generated by Django 4.2.7 on 2026-03-27 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricelists', '0009_add_workitem_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0006_suppliercatalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='default_work_item',
            field=models.ForeignKey(blank=True, help_text='Если указана — используется при подборе работ без дополнительного поиска', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_products', to='pricelists.workitem', verbose_name='Расценка по умолчанию'),
        ),
        migrations.CreateModel(
            name='ProductKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('item_name_pattern', models.CharField(db_index=True, help_text='Normalized form через Product.normalize_name()', max_length=500, verbose_name='Нормализованное имя позиции')),
                ('confidence', models.FloatField(default=0.5, verbose_name='Уверенность (0.0-1.0)')),
                ('source', models.CharField(choices=[('llm', 'LLM semantic match'), ('web', 'Web search'), ('manual', 'Ручной ввод')], max_length=20, verbose_name='Источник знания')),
                ('status', models.CharField(choices=[('pending', 'Ожидает проверки'), ('verified', 'Подтверждено сметчиком'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус верификации')),
                ('llm_reasoning', models.TextField(blank=True, help_text='Почему LLM выбрал эту работу', verbose_name='Обоснование LLM')),
                ('web_search_query', models.TextField(blank=True, verbose_name='Поисковый запрос')),
                ('web_search_result_summary', models.TextField(blank=True, help_text='Краткое содержание найденной информации', verbose_name='Результат поиска')),
                ('md_file_path', models.CharField(blank=True, help_text='Относительный путь в data/knowledge/', max_length=500, verbose_name='Путь к .md файлу')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='Количество использований')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Последнее использование')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Подтвердил')),
                ('work_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_entries', to='pricelists.workitem', verbose_name='Подходящая работа')),
                ('work_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_entries', to='pricelists.worksection', verbose_name='Раздел работ')),
            ],
            options={
                'verbose_name': 'Знание о товаре → работе',
                'verbose_name_plural': 'База знаний (товар → работа)',
                'indexes': [models.Index(fields=['item_name_pattern', '-confidence'], name='catalog_pro_item_na_1f3f27_idx'), models.Index(fields=['status', '-usage_count'], name='catalog_pro_status_836f9e_idx')],
                'unique_together': {('item_name_pattern', 'work_item')},
            },
        ),
    ]
