# Generated by Django 4.2.7 on 2026-02-14 22:37

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kanban_core', '0003_attachment_delivery_batch_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('erp_object_id', models.IntegerField(blank=True, null=True)),
                ('priority', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='object_task', to='kanban_core.card')),
            ],
            options={
                'verbose_name': 'Задача по объекту',
                'verbose_name_plural': 'Задачи по объекту',
            },
        ),
        migrations.CreateModel(
            name='OverdueMarker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('marker_date', models.DateField(default=datetime.date.today)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overdue_markers', to='kanban_core.card')),
            ],
            options={
                'indexes': [models.Index(fields=['marker_date'], name='kanban_obje_marker__b3b810_idx')],
                'unique_together': {('card', 'marker_date')},
            },
        ),
    ]
