# Generated by Django 4.2.7 on 2025-11-26 08:17

import communications.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0002_act_contract_contract_type_contract_counterparty_and_more'),
        ('accounting', '0002_populate_tax_systems'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correspondence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('type', models.CharField(choices=[('incoming', 'Входящее'), ('outgoing', 'Исходящее')], max_length=20, verbose_name='Тип')),
                ('category', models.CharField(choices=[('letter', 'Письмо'), ('notification', 'Уведомление'), ('claim', 'Претензия'), ('agreement', 'Согласование'), ('other', 'Другое')], default='letter', max_length=20, verbose_name='Категория')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('sent', 'Отправлено'), ('delivered', 'Доставлено'), ('received', 'Получено'), ('processed', 'Обработано'), ('cancelled', 'Отменено')], default='draft', max_length=20, verbose_name='Статус')),
                ('number', models.CharField(blank=True, help_text='Исходящий номер (для нас) или Входящий номер (от контрагента)', max_length=100, verbose_name='Номер документа')),
                ('date', models.DateField(verbose_name='Дата документа')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема')),
                ('description', models.TextField(blank=True, verbose_name='Содержание / Краткое описание')),
                ('file', models.FileField(blank=True, null=True, upload_to=communications.models.correspondence_scan_path, verbose_name='Скан документа')),
                ('contract', models.ForeignKey(blank=True, help_text='Договор, к которому относится письмо', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correspondence', to='contracts.contract', verbose_name='Договор')),
                ('counterparty', models.ForeignKey(blank=True, help_text='Контрагент (заполняется автоматически если выбран договор)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correspondence', to='accounting.counterparty', verbose_name='Контрагент')),
                ('related_to', models.ForeignKey(blank=True, help_text='Письмо, на которое дается ответ (цепочка переписки)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='communications.correspondence', verbose_name='В ответ на')),
            ],
            options={
                'verbose_name': 'Корреспонденция',
                'verbose_name_plural': 'Корреспонденция',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['type', 'date'], name='communicati_type_3331f7_idx'), models.Index(fields=['contract'], name='communicati_contrac_b0fe7a_idx'), models.Index(fields=['counterparty'], name='communicati_counter_0518b9_idx')],
            },
        ),
    ]
