# Generated by Django 4.2.7 on 2026-02-14 22:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kanban_core', '0003_attachment_delivery_batch_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('erp_object_id', models.IntegerField(blank=True, null=True)),
                ('erp_contract_id', models.IntegerField(blank=True, null=True)),
                ('supplier_label', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supply_case', to='kanban_core.card')),
            ],
            options={
                'verbose_name': 'SupplyCase',
                'verbose_name_plural': 'SupplyCases',
            },
        ),
        migrations.CreateModel(
            name='InvoiceRef',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('erp_invoice_id', models.IntegerField()),
                ('cached_status', models.CharField(blank=True, max_length=64)),
                ('cached_amount_gross', models.CharField(blank=True, max_length=64)),
                ('cached_currency', models.CharField(blank=True, max_length=16)),
                ('cached_due_date', models.DateField(blank=True, null=True)),
                ('cached_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supply_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_refs', to='kanban_supply.supplycase')),
            ],
            options={
                'verbose_name': 'InvoiceRef',
                'verbose_name_plural': 'InvoiceRefs',
                'unique_together': {('supply_case', 'erp_invoice_id')},
            },
        ),
        migrations.CreateModel(
            name='DeliveryBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('planned', 'План'), ('in_progress', 'В процессе'), ('delivered', 'Поставлено')], default='planned', max_length=20)),
                ('planned_date', models.DateField(blank=True, null=True)),
                ('actual_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='kanban_supply.invoiceref')),
                ('supply_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='kanban_supply.supplycase')),
            ],
            options={
                'verbose_name': 'DeliveryBatch',
                'verbose_name_plural': 'DeliveryBatches',
            },
        ),
    ]
