# Generated by Django 4.2.7 on 2026-02-14 22:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kanban_files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Доска',
                'verbose_name_plural': 'Доски',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('wip_limit', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='kanban_core.board')),
            ],
            options={
                'verbose_name': 'Колонка',
                'verbose_name_plural': 'Колонки',
                'ordering': ['board__key', 'order', 'key'],
                'unique_together': {('board', 'key')},
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('supply_case', 'Supply case'), ('object_task', 'Object task')], max_length=32)),
                ('title', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_by_user_id', models.IntegerField(blank=True, null=True)),
                ('created_by_username', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='kanban_core.board')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='kanban_core.column')),
            ],
            options={
                'verbose_name': 'Карточка',
                'verbose_name_plural': 'Карточки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('document', 'Документ'), ('photo', 'Фото'), ('other', 'Другое')], default='document', max_length=32)),
                ('document_type', models.CharField(blank=True, max_length=64)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_by_user_id', models.IntegerField(blank=True, null=True)),
                ('created_by_username', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='kanban_core.card')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kanban_attachments', to='kanban_files.fileobject')),
            ],
            options={
                'verbose_name': 'Вложение',
                'verbose_name_plural': 'Вложения',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CardEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=64)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('actor_user_id', models.IntegerField(blank=True, null=True)),
                ('actor_username', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='kanban_core.card')),
            ],
            options={
                'verbose_name': 'Событие карточки',
                'verbose_name_plural': 'События карточки',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['card', 'created_at'], name='kanban_core_card_id_254785_idx'), models.Index(fields=['event_type'], name='kanban_core_event_t_1e59dc_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['board', 'column'], name='kanban_core_board_i_41c1dd_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['type'], name='kanban_core_type_c9a98f_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['card', 'created_at'], name='kanban_core_card_id_f74df0_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['document_type'], name='kanban_core_documen_e16610_idx'),
        ),
    ]
