# Generated by Django 4.2.7 on 2026-02-14 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='assignee_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='assignee_username',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='card',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
