# Generated by Django 4.2.7 on 2026-02-14 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_core', '0002_card_assignee_user_id_card_assignee_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='delivery_batch_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attachment',
            name='invoice_ref_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
