# Generated by Django 4.2.7 on 2026-02-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_core', '0003_attachment_delivery_batch_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='type',
            field=models.CharField(choices=[('supply_case', 'Supply case'), ('object_task', 'Object task'), ('commercial_case', 'Commercial case')], max_length=32),
        ),
    ]
