# Generated by Django 4.2.7 on 2025-11-26 07:57

import contracts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_make_category_required'),
        ('accounting', '0002_populate_tax_systems'),
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('number', models.CharField(max_length=50, verbose_name='Номер документа')),
                ('date', models.DateField(verbose_name='Дата подписания')),
                ('period_start', models.DateField(blank=True, null=True, verbose_name='Начало периода работ')),
                ('period_end', models.DateField(blank=True, null=True, verbose_name='Конец периода работ')),
                ('amount_gross', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сумма с НДС')),
                ('amount_net', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сумма без НДС')),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сумма НДС')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('signed', 'Подписан'), ('cancelled', 'Отменен')], default='draft', max_length=20, verbose_name='Статус')),
                ('file', models.FileField(blank=True, null=True, upload_to=contracts.models.act_scan_path, verbose_name='Скан акта')),
                ('description', models.TextField(blank=True, verbose_name='Описание работ')),
            ],
            options={
                'verbose_name': 'Акт выполненных работ',
                'verbose_name_plural': 'Акты выполненных работ',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(choices=[('income', 'Доходный (с Заказчиком)'), ('expense', 'Расходный (с Исполнителем)')], default='expense', max_length=20, verbose_name='Тип договора'),
        ),
        migrations.AddField(
            model_name='contract',
            name='counterparty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='accounting.counterparty', verbose_name='Контрагент'),
        ),
        migrations.AddField(
            model_name='contract',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=contracts.models.contract_scan_path, verbose_name='Скан договора'),
        ),
        migrations.AddField(
            model_name='contract',
            name='legal_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='accounting.legalentity', verbose_name='Наше юрлицо'),
        ),
        migrations.AddField(
            model_name='contract',
            name='parent_contract',
            field=models.ForeignKey(blank=True, help_text='Для зеркальных договоров: ссылка на договор с Заказчиком', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcontracts', to='contracts.contract', verbose_name='Родительский договор'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contractor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Контрагент (текст)'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='document_link',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка на договор (legacy)'),
        ),
        migrations.CreateModel(
            name='WorkScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование работ')),
                ('start_date', models.DateField(verbose_name='Начало')),
                ('end_date', models.DateField(verbose_name='Окончание')),
                ('workers_count', models.PositiveIntegerField(default=0, verbose_name='Кол-во рабочих')),
                ('status', models.CharField(choices=[('pending', 'Не начато'), ('in_progress', 'В работе'), ('done', 'Выполнено')], default='pending', max_length=20, verbose_name='Статус')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_items', to='contracts.contract', verbose_name='Договор')),
            ],
            options={
                'verbose_name': 'Задача графика',
                'verbose_name_plural': 'График работ',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='ActPaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сумма покрытия')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_allocations', to='contracts.act', verbose_name='Акт')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='act_allocations', to='payments.payment', verbose_name='Платёж')),
            ],
            options={
                'verbose_name': 'Распределение оплаты',
                'verbose_name_plural': 'Распределения оплат',
            },
        ),
        migrations.AddField(
            model_name='act',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acts', to='contracts.contract', verbose_name='Договор'),
        ),
        migrations.CreateModel(
            name='ContractAmendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('number', models.CharField(max_length=50, verbose_name='Номер Доп.Соглашения')),
                ('date', models.DateField(verbose_name='Дата подписания')),
                ('reason', models.TextField(verbose_name='Причина изменений')),
                ('new_start_date', models.DateField(blank=True, null=True, verbose_name='Новая дата начала')),
                ('new_end_date', models.DateField(blank=True, null=True, verbose_name='Новая дата окончания')),
                ('new_total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Новая сумма')),
                ('file', models.FileField(blank=True, null=True, upload_to=contracts.models.amendment_scan_path, verbose_name='Скан документа')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='contracts.contract', verbose_name='Договор')),
            ],
            options={
                'verbose_name': 'Доп. соглашение',
                'verbose_name_plural': 'Доп. соглашения',
                'ordering': ['date'],
                'unique_together': {('contract', 'number')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='act',
            unique_together={('contract', 'number')},
        ),
    ]
