# Generated by Django 4.2.7 on 2025-11-26 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_act_contract_contract_type_contract_counterparty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='contractor',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='document_link',
        ),
    ]
