# Generated by Django 4.2.7 on 2025-11-26 10:00

import contracts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_populate_tax_systems'),
        ('objects', '0001_initial'),
        ('contracts', '0003_remove_contract_contractor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('proposal_type', models.CharField(choices=[('income', 'ТКП для Заказчика'), ('expense', 'Монтажное предложение Исполнителя')], default='expense', max_length=20, verbose_name='Тип предложения')),
                ('number', models.CharField(max_length=100, verbose_name='Номер предложения')),
                ('date', models.DateField(verbose_name='Дата предложения')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Итоговая сумма')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('sent', 'Отправлено'), ('approved', 'Согласовано'), ('rejected', 'Отклонено')], default='draft', max_length=20, verbose_name='Статус')),
                ('file', models.FileField(blank=True, null=True, upload_to='contracts/proposals/%Y/%m/%d/', verbose_name='Файл предложения')),
                ('description', models.TextField(blank=True, verbose_name='Примечания')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commercial_proposals', to='accounting.counterparty', verbose_name='Контрагент')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_proposals', to='objects.object', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Коммерческое предложение',
                'verbose_name_plural': 'Коммерческие предложения',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='commercial_proposal',
            field=models.OneToOneField(blank=True, help_text='Предложение, на основании которого создан договор', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract', to='contracts.commercialproposal', verbose_name='Основание (КП)'),
        ),
    ]
