# Generated by Django 4.2.7 on 2025-12-13 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_commercialproposal_contract_commercial_proposal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='act',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='act',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='commercialproposal',
            name='parent_proposal',
            field=models.ForeignKey(blank=True, help_text='Ссылка на ТКП для Заказчика (заполняется только для МП)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mounting_proposals', to='contracts.commercialproposal', verbose_name='Родительское ТКП'),
        ),
    ]
