# Generated by Django 4.2.7 on 2025-12-13 09:48

import contracts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_add_parent_proposal_to_commercial_proposal'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialProposalEstimateFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('file', models.FileField(help_text='Файл сметы (Excel, PDF и т.д.)', upload_to='contracts/proposals/%Y/%m/%d/estimates/', verbose_name='Файл сметы')),
                ('name', models.CharField(blank=True, help_text='Опциональное название для отображения (если не указано, используется имя файла)', max_length=255, verbose_name='Название файла')),
                ('description', models.TextField(blank=True, help_text='Дополнительное описание файла сметы', verbose_name='Описание')),
                ('commercial_proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimate_files', to='contracts.commercialproposal', verbose_name='Коммерческое предложение')),
            ],
            options={
                'verbose_name': 'Файл сметы',
                'verbose_name_plural': 'Файлы смет',
                'ordering': ['-created_at'],
            },
        ),
    ]
