# Generated by Django 4.2.7 on 2025-12-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_add_commercial_proposal_estimate_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialproposal',
            name='number',
            field=models.CharField(blank=True, help_text='Автоматически генерируется, если не указан', max_length=100, verbose_name='Номер предложения'),
        ),
    ]
