# Generated by Django 4.2.7 on 2025-12-14 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
        ('contracts', '0007_make_commercial_proposal_number_optional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='commercial_proposal',
        ),
        migrations.AddField(
            model_name='contract',
            name='mounting_proposal',
            field=models.OneToOneField(blank=True, help_text='МП, на основании которого создан договор с Исполнителем', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract', to='proposals.mountingproposal', verbose_name='Основание (МП)'),
        ),
        migrations.AddField(
            model_name='contract',
            name='technical_proposal',
            field=models.OneToOneField(blank=True, help_text='ТКП, на основании которого создан договор', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract', to='proposals.technicalproposal', verbose_name='Основание (ТКП)'),
        ),
    ]
