# Generated by Django 4.2.7 on 2025-12-14 18:35

import contracts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_legalentity_director_legalentity_director_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pricelists', '0007_workitem_required_grade_alter_workitem_grade'),
        ('contracts', '0009_remove_commercial_proposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='responsible_engineer',
            field=models.ForeignKey(blank=True, help_text='Ответственный инженер по договору', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engineered_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный инженер'),
        ),
        migrations.AddField(
            model_name='contract',
            name='responsible_manager',
            field=models.ForeignKey(blank=True, help_text='Ответственный начальник участка', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Начальник участка'),
        ),
        migrations.CreateModel(
            name='FrameworkContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('number', models.CharField(max_length=100, verbose_name='Номер договора')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('date', models.DateField(verbose_name='Дата заключения')),
                ('valid_from', models.DateField(verbose_name='Начало действия')),
                ('valid_until', models.DateField(verbose_name='Окончание действия')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Действующий'), ('expired', 'Истёк срок'), ('terminated', 'Расторгнут')], default='draft', max_length=20, verbose_name='Статус')),
                ('file', models.FileField(blank=True, null=True, upload_to=contracts.models.framework_contract_file_path, verbose_name='Скан договора')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='framework_contracts', to='accounting.counterparty', verbose_name='Исполнитель')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_framework_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='framework_contracts', to='accounting.legalentity', verbose_name='Наша компания')),
                ('price_lists', models.ManyToManyField(blank=True, related_name='framework_contracts', to='pricelists.pricelist', verbose_name='Согласованные прайс-листы')),
            ],
            options={
                'verbose_name': 'Рамочный договор',
                'verbose_name_plural': 'Рамочные договоры',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='framework_contract',
            field=models.ForeignKey(blank=True, help_text='Рамочный договор, под который создан этот договор (только для расходных)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='contracts.frameworkcontract', verbose_name='Рамочный договор'),
        ),
    ]
