# Generated by Django 4.2.7 on 2025-12-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0010_contract_responsible_engineer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='due_date',
            field=models.DateField(blank=True, help_text='Срок оплаты по акту', null=True, verbose_name='Срок оплаты'),
        ),
    ]
