# Generated by Django 4.2.7 on 2026-02-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0011_act_due_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='act',
            options={'ordering': ['-date'], 'verbose_name': 'Акт', 'verbose_name_plural': 'Акты'},
        ),
        migrations.AddIndex(
            model_name='act',
            index=models.Index(fields=['contract', 'status'], name='contracts_a_contrac_6d81aa_idx'),
        ),
        migrations.AddIndex(
            model_name='act',
            index=models.Index(fields=['date'], name='contracts_a_date_a31249_idx'),
        ),
        migrations.AddIndex(
            model_name='act',
            index=models.Index(fields=['status', 'date'], name='contracts_a_status_59e6c8_idx'),
        ),
        migrations.AddIndex(
            model_name='act',
            index=models.Index(fields=['due_date'], name='contracts_a_due_dat_10d841_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['contract_date'], name='contracts_c_contrac_ac5933_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['status', 'contract_date'], name='contracts_c_status_e8e73a_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['contract_type', 'status'], name='contracts_c_contrac_fd43fa_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['object', 'status'], name='contracts_c_object__d3af37_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['counterparty', 'status'], name='contracts_c_counter_f9f995_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['framework_contract'], name='contracts_c_framewo_7058ad_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['end_date'], name='contracts_c_end_dat_dedd36_idx'),
        ),
    ]
