# Generated by Django 4.2.7 on 2026-02-23 14:53

import contracts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0002_estimateitem'),
        ('catalog', '0002_productworkmapping'),
        ('pricelists', '0007_workitem_required_grade_alter_workitem_grade'),
        ('contracts', '0012_alter_act_options_act_contracts_a_contrac_6d81aa_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('number', models.CharField(max_length=100, verbose_name='Номер сметы')),
                ('name', models.CharField(max_length=255, verbose_name='Название сметы')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('agreed', 'Согласована'), ('signed', 'Подписана')], default='draft', max_length=20, verbose_name='Статус')),
                ('signed_date', models.DateField(blank=True, null=True, verbose_name='Дата подписания')),
                ('file', models.FileField(blank=True, null=True, upload_to=contracts.models.contract_estimate_file_path, verbose_name='Файл сметы (Excel/PDF)')),
                ('version_number', models.PositiveIntegerField(default=1, verbose_name='Номер версии')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('amendment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_estimates', to='contracts.contractamendment', verbose_name='ДОП-соглашение (для новой версии)')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_estimates', to='contracts.contract', verbose_name='Договор')),
                ('parent_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_versions', to='contracts.contractestimate', verbose_name='Предыдущая версия')),
                ('source_estimate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_estimates', to='estimates.estimate', verbose_name='Исходная смета')),
            ],
            options={
                'verbose_name': 'Смета к договору',
                'verbose_name_plural': 'Сметы к договорам',
                'ordering': ['-version_number', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractEstimateSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=255, verbose_name='Название раздела')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('contract_estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='contracts.contractestimate', verbose_name='Смета к договору')),
            ],
            options={
                'verbose_name': 'Раздел сметы к договору',
                'verbose_name_plural': 'Разделы смет к договорам',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContractEstimateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('item_number', models.PositiveIntegerField(default=0, verbose_name='Номер по порядку')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
                ('model_name', models.CharField(blank=True, max_length=300, verbose_name='Модель / артикул')),
                ('unit', models.CharField(default='шт', max_length=50, verbose_name='Единица измерения')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Количество')),
                ('material_unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Цена материала за ед.')),
                ('work_unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Цена работы за ед.')),
                ('is_analog', models.BooleanField(default=False, verbose_name='Применён аналог')),
                ('analog_reason', models.TextField(blank=True, verbose_name='Обоснование аналога')),
                ('original_name', models.CharField(blank=True, max_length=500, verbose_name='Оригинальное наименование')),
                ('item_type', models.CharField(choices=[('regular', 'Обычная строка'), ('consumable', 'Расходные материалы'), ('additional', 'Допработы')], default='regular', max_length=20, verbose_name='Тип строки')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('contract_estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='contracts.contractestimate', verbose_name='Смета к договору')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_estimate_items', to='catalog.product', verbose_name='Товар из каталога')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='contracts.contractestimatesection', verbose_name='Раздел')),
                ('source_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_items', to='estimates.estimateitem', verbose_name='Исходная строка сметы')),
                ('work_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_estimate_items', to='pricelists.workitem', verbose_name='Работа из прайс-листа')),
            ],
            options={
                'verbose_name': 'Строка сметы к договору',
                'verbose_name_plural': 'Строки смет к договорам',
                'ordering': ['section__sort_order', 'sort_order', 'item_number'],
                'indexes': [models.Index(fields=['contract_estimate', 'section'], name='contracts_c_contrac_c65e0a_idx'), models.Index(fields=['product'], name='contracts_c_product_1163b2_idx'), models.Index(fields=['item_type'], name='contracts_c_item_ty_3359c3_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='contractestimate',
            index=models.Index(fields=['contract', 'status'], name='contracts_c_contrac_51ef3e_idx'),
        ),
    ]
