# Generated by Django 4.2.7 on 2026-02-23 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0007_object_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0013_contractestimate_contractestimatesection_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contract',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='contractamendment',
            name='content_md',
            field=models.TextField(blank=True, verbose_name='Текст допсоглашения (md)'),
        ),
        migrations.AddField(
            model_name='contractamendment',
            name='contract_estimate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amendments', to='contracts.contractestimate', verbose_name='Новая смета'),
        ),
        migrations.AddField(
            model_name='contractamendment',
            name='object',
            field=models.ForeignKey(blank=True, help_text='На какой объект ДОП (для рамочных договоров с Заказчиком)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_amendments', to='objects.object', verbose_name='Объект (для рамочных)'),
        ),
        migrations.AddField(
            model_name='contractamendment',
            name='parent_amendment',
            field=models.ForeignKey(blank=True, help_text='ДОП к ДОП', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_amendments', to='contracts.contractamendment', verbose_name='Родительское ДОП'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='objects.object', verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('planned', 'Планируется'), ('agreed', 'Согласован'), ('active', 'В работе'), ('completed', 'Завершён'), ('suspended', 'Приостановлен'), ('terminated', 'Расторгнут')], default='planned', max_length=20, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='ContractText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('content_md', models.TextField(verbose_name='Текст в формате Markdown')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Версия текста')),
                ('amendment', models.ForeignKey(blank=True, help_text='null = основной текст договора', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='texts', to='contracts.contractamendment', verbose_name='Допсоглашение')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='contracts.contract', verbose_name='Договор')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_contract_texts', to=settings.AUTH_USER_MODEL, verbose_name='Кто внёс')),
            ],
            options={
                'verbose_name': 'Текст договора',
                'verbose_name_plural': 'Тексты договоров',
                'ordering': ['-version'],
                'indexes': [models.Index(fields=['contract', 'amendment'], name='contracts_c_contrac_72fa57_idx')],
            },
        ),
    ]
