# Generated by Django 4.2.7 on 2026-02-23 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_create_system_accounts'),
        ('contracts', '0014_alter_contract_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimatePurchaseLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('quantity_matched', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Сопоставленное количество')),
                ('match_type', models.CharField(choices=[('exact', 'Точное совпадение'), ('analog', 'Аналог'), ('substitute', 'Замена')], default='exact', max_length=20, verbose_name='Тип сопоставления')),
                ('match_reason', models.TextField(blank=True, verbose_name='Обоснование (для аналога/замены)')),
                ('price_exceeds', models.BooleanField(default=False, verbose_name='Цена закупки превышает сметную')),
                ('quantity_exceeds', models.BooleanField(default=False, verbose_name='Количество превышает сметное')),
                ('contract_estimate_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_links', to='contracts.contractestimateitem', verbose_name='Строка сметы')),
                ('invoice_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimate_links', to='payments.invoiceitem', verbose_name='Позиция счёта')),
            ],
            options={
                'verbose_name': 'Сопоставление закупки со сметой',
                'verbose_name_plural': 'Сопоставления закупок со сметами',
                'indexes': [models.Index(fields=['contract_estimate_item'], name='contracts_e_contrac_cce515_idx'), models.Index(fields=['invoice_item'], name='contracts_e_invoice_27fa13_idx')],
            },
        ),
    ]
