# Generated by Django 4.2.7 on 2026-02-23 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0015_estimatepurchaselink'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование работ')),
                ('unit', models.CharField(default='шт', max_length=50, verbose_name='Единица измерения')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Количество')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Цена за единицу')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сумма')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Строка акта',
                'verbose_name_plural': 'Строки актов',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='act',
            name='act_type',
            field=models.CharField(choices=[('ks2', 'КС-2 (Акт о приёмке выполненных работ)'), ('ks3', 'КС-3 (Справка о стоимости)'), ('simple', 'Простой акт')], default='ks2', max_length=20, verbose_name='Тип акта'),
        ),
        migrations.AddField(
            model_name='act',
            name='contract_estimate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acts', to='contracts.contractestimate', verbose_name='Смета к договору'),
        ),
        migrations.AlterField(
            model_name='act',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('agreed', 'Согласован'), ('signed', 'Подписан'), ('cancelled', 'Отменен')], default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddIndex(
            model_name='act',
            index=models.Index(fields=['act_type'], name='contracts_a_act_typ_0f6946_idx'),
        ),
        migrations.AddField(
            model_name='actitem',
            name='act',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='act_items', to='contracts.act', verbose_name='Акт'),
        ),
        migrations.AddField(
            model_name='actitem',
            name='contract_estimate_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='act_items', to='contracts.contractestimateitem', verbose_name='Строка сметы'),
        ),
        migrations.AddIndex(
            model_name='actitem',
            index=models.Index(fields=['act'], name='contracts_a_act_id_63116e_idx'),
        ),
    ]
