# Generated by Django 4.2.7 on 2026-03-16 07:02

import api_public.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import storages.backends.s3


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0006_suppliercatalog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estimates', '0005_estimateitem_supplier_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('email', models.EmailField(max_length=254, verbose_name='Email заказчика')),
                ('contact_name', models.CharField(blank=True, max_length=255, verbose_name='Контактное лицо')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='Компания')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('access_token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Токен доступа')),
                ('project_name', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('project_description', models.TextField(blank=True, verbose_name='Описание проекта')),
                ('status', models.CharField(choices=[('uploaded', 'Файлы загружены'), ('parsing', 'Парсинг документов'), ('matching', 'Подбор товаров'), ('review', 'На проверке оператором'), ('rfq_sent', 'Запросы поставщикам'), ('ready', 'Смета готова'), ('delivered', 'Отправлена клиенту'), ('error', 'Ошибка')], default='uploaded', max_length=20, verbose_name='Статус')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('result_excel_file', models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(access_key='minioadmin', bucket_name='portal-estimates', default_acl='private', endpoint_url='http://localhost:9000', querystring_auth=True, querystring_expire=3600, secret_key='minioadmin'), upload_to=api_public.models.portal_result_path, verbose_name='Excel-файл сметы')),
                ('task_id', models.CharField(blank=True, max_length=255)),
                ('total_files', models.PositiveIntegerField(default=0)),
                ('processed_files', models.PositiveIntegerField(default=0)),
                ('total_spec_items', models.PositiveIntegerField(default=0)),
                ('matched_exact', models.PositiveIntegerField(default=0)),
                ('matched_analog', models.PositiveIntegerField(default=0)),
                ('unmatched', models.PositiveIntegerField(default=0)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notification_sent', models.BooleanField(default=False)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True, verbose_name='Когда скачан')),
                ('llm_cost', models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='Стоимость LLM-обработки ($)')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('estimate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_requests', to='estimates.estimate', verbose_name='Внутренняя смета')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_public_requests', to=settings.AUTH_USER_MODEL, verbose_name='Проверил')),
            ],
            options={
                'verbose_name': 'Публичный запрос сметы',
                'verbose_name_plural': 'Публичные запросы смет',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicPortalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('auto_approve', models.BooleanField(default=False, help_text='True = сметы отправляются клиенту без проверки оператором. False = оператор проверяет перед отправкой.', verbose_name='Автоматическая отправка')),
                ('operator_emails', models.TextField(blank=True, help_text='Через запятую. Все получают уведомления о новых запросах, ошибках, callback-заявках.', verbose_name='Email операторов')),
                ('max_pages_per_request', models.PositiveIntegerField(default=100, verbose_name='Макс. страниц на запрос')),
                ('max_files_per_request', models.PositiveIntegerField(default=20, verbose_name='Макс. файлов на запрос')),
                ('link_expiry_days', models.PositiveIntegerField(default=30, verbose_name='Срок жизни ссылки (дней)')),
                ('company_phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон компании (для CTA)')),
            ],
            options={
                'verbose_name': 'Настройки портала',
                'verbose_name_plural': 'Настройки портала',
            },
        ),
        migrations.CreateModel(
            name='PublicPricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('markup_percent', models.DecimalField(decimal_places=2, default=30.0, max_digits=5, verbose_name='Наценка (%)')),
                ('is_default', models.BooleanField(default=False, help_text='Только одна запись может быть default', verbose_name='По умолчанию')),
                ('category', models.ForeignKey(blank=True, help_text='NULL = наценка по умолчанию', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='public_pricing_configs', to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Настройка наценки',
                'verbose_name_plural': 'Настройки наценок',
            },
        ),
        migrations.CreateModel(
            name='EstimateRequestVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('version_number', models.PositiveIntegerField()),
                ('excel_file', models.FileField(storage=storages.backends.s3.S3Storage(access_key='minioadmin', bucket_name='portal-estimates', default_acl='private', endpoint_url='http://localhost:9000', querystring_auth=True, querystring_expire=3600, secret_key='minioadmin'), upload_to=api_public.models.portal_version_path)),
                ('generated_by', models.CharField(max_length=50, verbose_name='Кем сгенерирована')),
                ('changes_description', models.TextField(blank=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='api_public.estimaterequest')),
            ],
            options={
                'verbose_name': 'Версия сметы',
                'verbose_name_plural': 'Версии смет',
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='EstimateRequestFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('file', models.FileField(storage=storages.backends.s3.S3Storage(access_key='minioadmin', bucket_name='portal-estimates', default_acl='private', endpoint_url='http://localhost:9000', querystring_auth=True, querystring_expire=3600, secret_key='minioadmin'), upload_to=api_public.models.portal_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('spec', 'Спецификация'), ('equip', 'Ведомость оборудования'), ('drawing', 'Чертёж'), ('excel', 'Excel-ведомость'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип файла')),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('parsed_data', models.JSONField(blank=True, null=True)),
                ('parse_status', models.CharField(choices=[('pending', 'Ожидает'), ('parsing', 'Обрабатывается'), ('done', 'Готово'), ('partial', 'Частично обработан'), ('skipped', 'Пропущен (не спецификация)'), ('error', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус парсинга')),
                ('parse_error', models.TextField(blank=True)),
                ('pages_total', models.PositiveIntegerField(default=0)),
                ('pages_processed', models.PositiveIntegerField(default=0)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api_public.estimaterequest')),
            ],
            options={
                'verbose_name': 'Файл запроса',
                'verbose_name_plural': 'Файлы запросов',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CallbackRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('preferred_time', models.CharField(blank=True, max_length=100, verbose_name='Удобное время для звонка')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('completed', 'Обработана'), ('cancelled', 'Отменена')], default='new', max_length=20, verbose_name='Статус')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_callbacks', to=settings.AUTH_USER_MODEL, verbose_name='Обработал')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='callbacks', to='api_public.estimaterequest', verbose_name='Запрос на смету')),
            ],
            options={
                'verbose_name': 'Заявка на звонок',
                'verbose_name_plural': 'Заявки на звонок',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='publicpricingconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('category__isnull', False)), fields=('category',), name='unique_category_pricing'),
        ),
        migrations.AlterUniqueTogether(
            name='estimaterequestversion',
            unique_together={('request', 'version_number')},
        ),
    ]
