# Generated by Django 4.2.7 on 2026-04-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_public', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='Компания')),
                ('contact_name', models.CharField(blank=True, max_length=255, verbose_name='Контактное лицо')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Email подтверждён')),
                ('session_token', models.CharField(blank=True, db_index=True, max_length=128, verbose_name='Токен сессии')),
                ('session_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Токен истекает')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='Последний вход')),
            ],
            options={
                'verbose_name': 'Внешний пользователь',
                'verbose_name_plural': 'Внешние пользователи',
                'ordering': ['-created_at'],
            },
        ),
    ]
