# Generated by Django 4.2.7 on 2025-11-26 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(help_text='ООО "Ромашка", ИП Иванов И.И.', max_length=255, verbose_name='Полное наименование')),
                ('short_name', models.CharField(blank=True, help_text='Для удобного поиска', max_length=100, verbose_name='Краткое имя')),
                ('type', models.CharField(choices=[('customer', 'Заказчик'), ('vendor', 'Исполнитель/Поставщик'), ('both', 'Заказчик и Исполнитель')], max_length=20, verbose_name='Тип контрагента')),
                ('legal_form', models.CharField(choices=[('ooo', 'ООО'), ('ip', 'ИП'), ('self_employed', 'Самозанятый'), ('fiz', 'Физ. лицо')], max_length=20, verbose_name='Правовая форма')),
                ('inn', models.CharField(max_length=12, unique=True, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=9, verbose_name='КПП')),
                ('ogrn', models.CharField(blank=True, max_length=15, verbose_name='ОГРН / ОГРНИП')),
                ('contact_info', models.TextField(blank=True, help_text='Телефоны, email, ответственные лица', verbose_name='Контактная информация')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TaxSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('code', models.CharField(help_text='osn_vat_20, usn_income, etc.', max_length=50, unique=True, verbose_name='Код системы')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('vat_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Ставка НДС, %')),
                ('has_vat', models.BooleanField(default=False, verbose_name='Есть НДС')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Система налогообложения',
                'verbose_name_plural': 'Системы налогообложения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=255, verbose_name='Полное наименование')),
                ('short_name', models.CharField(max_length=100, verbose_name='Краткое наименование')),
                ('inn', models.CharField(max_length=12, unique=True, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=9, verbose_name='КПП')),
                ('ogrn', models.CharField(blank=True, max_length=15, verbose_name='ОГРН')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('tax_system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.taxsystem', verbose_name='Система налогообложения')),
            ],
            options={
                'verbose_name': 'Юридическое лицо (Наше)',
                'verbose_name_plural': 'Юридические лица (Наши)',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=100, verbose_name='Название счёта')),
                ('number', models.CharField(help_text='Номер расчётного счёта или условный номер кассы', max_length=50, verbose_name='Номер счёта')),
                ('account_type', models.CharField(choices=[('bank_account', 'Расчётный счёт'), ('cash', 'Касса (наличные)'), ('deposit', 'Депозит'), ('currency_account', 'Валютный счёт')], default='bank_account', max_length=20, verbose_name='Тип счёта')),
                ('bank_name', models.CharField(blank=True, max_length=255, verbose_name='Наименование банка')),
                ('bik', models.CharField(blank=True, max_length=9, verbose_name='БИК банка')),
                ('currency', models.CharField(choices=[('RUB', 'Российский рубль'), ('USD', 'Доллар США'), ('EUR', 'Евро')], default='RUB', max_length=3, verbose_name='Валюта')),
                ('initial_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Начальный остаток')),
                ('balance_date', models.DateField(blank=True, null=True, verbose_name='Дата начального остатка')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Местоположение (для касс)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='accounting.legalentity', verbose_name='Юридическое лицо')),
            ],
            options={
                'verbose_name': 'Счёт',
                'verbose_name_plural': 'Счета',
                'ordering': ['legal_entity', 'name'],
                'unique_together': {('legal_entity', 'number')},
            },
        ),
        migrations.CreateModel(
            name='AccountBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_date', models.DateField(verbose_name='Дата')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Остаток')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='accounting.account', verbose_name='Счёт')),
            ],
            options={
                'verbose_name': 'Остаток на счёте',
                'verbose_name_plural': 'Остатки на счетах',
                'ordering': ['-balance_date'],
                'unique_together': {('account', 'balance_date')},
            },
        ),
    ]
