# Generated by Django 4.2.7 on 2025-12-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_populate_tax_systems'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterparty',
            name='vendor_subtype',
            field=models.CharField(blank=True, choices=[('supplier', 'Поставщик'), ('executor', 'Исполнитель'), ('both', 'Исполнитель и Поставщик')], help_text='Уточнение: Поставщик или Исполнитель. Заполняется только для типа "Исполнитель/Поставщик"', max_length=20, null=True, verbose_name='Подтип (для vendor)'),
        ),
    ]
