# Generated by Django 4.2.7 on 2025-12-14 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0003_add_vendor_subtype_to_counterparty'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalentity',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directed_legal_entities', to=settings.AUTH_USER_MODEL, verbose_name='Генеральный директор (пользователь)'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='director_name',
            field=models.CharField(blank=True, help_text='Полное ФИО для документов (Иванов Иван Иванович)', max_length=255, verbose_name='ФИО директора'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='director_position',
            field=models.CharField(default='Генеральный директор', max_length=100, verbose_name='Должность директора'),
        ),
    ]
