# Generated by Django 4.2.7 on 2026-02-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_counterparty_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterparty',
            name='type',
            field=models.CharField(choices=[('customer', 'Заказчик'), ('vendor', 'Исполнитель/Поставщик'), ('both', 'Заказчик и Исполнитель'), ('employee', 'Сотрудник')], max_length=20, verbose_name='Тип контрагента'),
        ),
    ]
