# Generated by Django 4.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_alter_counterparty_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='corr_account',
            field=models.CharField(blank=True, max_length=20, verbose_name='Корреспондентский счёт банка'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='legal_address',
            field=models.TextField(blank=True, verbose_name='Юридический адрес'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='actual_address',
            field=models.TextField(blank=True, verbose_name='Фактический адрес'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Наименование банка'),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='bank_bik',
            field=models.CharField(blank=True, max_length=9, verbose_name='БИК банка'),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='bank_corr_account',
            field=models.CharField(blank=True, max_length=20, verbose_name='Корреспондентский счёт банка'),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='bank_account',
            field=models.CharField(blank=True, max_length=20, verbose_name='Расчётный счёт'),
        ),
    ]
