# Generated by Django 4.2.7 on 2026-02-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_banking_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountbalance',
            name='source',
            field=models.CharField(
                choices=[('internal', 'Внутренний (ERP)'), ('bank_tochka', 'Банк (Точка)')],
                default='internal',
                max_length=20,
                verbose_name='Источник',
            ),
        ),
        migrations.AlterUniqueTogether(
            name='accountbalance',
            unique_together={('account', 'balance_date', 'source')},
        ),
    ]

