# Generated by Django 4.2.7 on 2026-04-18 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ac_brands', '0001_initial'),
        ('ac_methodology', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ACModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('series', models.CharField(blank=True, default='', max_length=255, verbose_name='Серия')),
                ('inner_unit', models.CharField(max_length=255, verbose_name='Модель внутреннего блока')),
                ('outer_unit', models.CharField(blank=True, default='', max_length=255, verbose_name='Модель наружного блока')),
                ('nominal_capacity', models.FloatField(blank=True, null=True, verbose_name='Номинальная холодопроизводительность (Вт)')),
                ('publish_status', models.CharField(choices=[('draft', 'Черновик'), ('review', 'На проверке'), ('published', 'Опубликован'), ('archived', 'В архиве')], db_index=True, default='draft', max_length=20, verbose_name='Статус публикации')),
                ('total_index', models.FloatField(db_index=True, default=0, verbose_name='Итоговый индекс')),
                ('youtube_url', models.URLField(blank=True, default='', max_length=512)),
                ('rutube_url', models.URLField(blank=True, default='', max_length=512)),
                ('vk_url', models.URLField(blank=True, default='', max_length=512)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Рекомендованная цена (руб.)')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, default='', help_text='Генерируется автоматически из бренда, серии и блоков', max_length=500, unique=True, verbose_name='URL-slug')),
                ('pros_text', models.TextField(blank=True, default='', verbose_name='Плюсы (AI)')),
                ('cons_text', models.TextField(blank=True, default='', verbose_name='Минусы (AI)')),
                ('is_ad', models.BooleanField(default=False, verbose_name='Рекламная модель')),
                ('ad_position', models.PositiveIntegerField(blank=True, help_text='Номер позиции в списке (1 = первая). Пусто = не рекламная.', null=True, verbose_name='Позиция в рейтинге')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models', to='ac_brands.brand', verbose_name='Бренд')),
            ],
            options={
                'verbose_name': 'Модель кондиционера',
                'verbose_name_plural': 'Модели кондиционеров',
                'ordering': ['-total_index'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Тип оборудования')),
            ],
            options={
                'verbose_name': 'Тип оборудования (рейтинг кондиционеров)',
                'verbose_name_plural': 'Типы оборудования (рейтинг кондиционеров)',
            },
        ),
        migrations.CreateModel(
            name='ModelRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_code', models.CharField(choices=[('ru', 'Россия'), ('eu', 'Европа')], max_length=10, verbose_name='Регион')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='ac_catalog.acmodel', verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Доступность в регионе',
                'verbose_name_plural': 'Доступность в регионах',
            },
        ),
        migrations.CreateModel(
            name='ModelRawValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('criterion_code', models.CharField(blank=True, db_index=True, default='', help_text='Дублирует criterion.code для сохранения идентичности при удалении критерия', max_length=50, verbose_name='Код критерия')),
                ('raw_value', models.CharField(blank=True, default='', max_length=500, verbose_name='Значение')),
                ('compressor_model', models.CharField(blank=True, default='', help_text='Используется для критерия «Мощность компрессора».', max_length=255, verbose_name='Модель компрессора')),
                ('numeric_value', models.FloatField(blank=True, null=True, verbose_name='Числовое значение')),
                ('source', models.CharField(blank=True, default='', max_length=255, verbose_name='Источник')),
                ('source_url', models.URLField(blank=True, default='', max_length=512, verbose_name='Ссылка на источник')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('verification_status', models.CharField(choices=[('catalog', 'Данные по каталогу'), ('editorial', 'Проверено редакцией'), ('lab', 'Подтверждено лабораторией')], db_index=True, default='catalog', max_length=20, verbose_name='Статус верификации')),
                ('lab_status', models.CharField(choices=[('not_measured', 'Не измерено'), ('pending', 'Ожидает измерения'), ('not_in_mode', 'Не участвует в данном режиме'), ('measured', 'Измерено')], db_index=True, default='not_measured', max_length=20, verbose_name='Статус лаб. измерения')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ac_approved_values', to=settings.AUTH_USER_MODEL, verbose_name='Утвердил данные')),
                ('criterion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='values', to='ac_methodology.criterion', verbose_name='Критерий')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ac_entered_values', to=settings.AUTH_USER_MODEL, verbose_name='Внёс данные')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_values', to='ac_catalog.acmodel', verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Значение параметра модели',
                'verbose_name_plural': 'Значения параметров моделей',
                'ordering': ['criterion__code'],
            },
        ),
        migrations.CreateModel(
            name='ACModelSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=200, verbose_name='Название поставщика')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='ac_catalog.acmodel', verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Поставщик (Где купить)',
                'verbose_name_plural': 'Поставщики (Где купить)',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ACModelPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('image', models.ImageField(upload_to='ac_rating/photos/', verbose_name='Фото')),
                ('alt', models.CharField(blank=True, default='', help_text='Alt-текст для SEO и доступности', max_length=255, verbose_name='Alt-текст')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='ac_catalog.acmodel', verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Фото модели',
                'verbose_name_plural': 'Фото моделей',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='acmodel',
            name='equipment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='models', to='ac_catalog.equipmenttype', verbose_name='Тип оборудования'),
        ),
        migrations.AddConstraint(
            model_name='modelregion',
            constraint=models.UniqueConstraint(fields=('model', 'region_code'), name='unique_acmodel_region'),
        ),
        migrations.AddConstraint(
            model_name='modelrawvalue',
            constraint=models.UniqueConstraint(condition=models.Q(('criterion__isnull', False)), fields=('model', 'criterion'), name='unique_acmodel_criterion_value'),
        ),
        migrations.AddConstraint(
            model_name='modelrawvalue',
            constraint=models.UniqueConstraint(condition=models.Q(('criterion__isnull', True)), fields=('model', 'criterion_code'), name='unique_acmodel_criterion_code_orphan'),
        ),
    ]
