# Generated by Django 4.2.7 on 2026-04-21 09:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac_catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acmodel',
            name='editorial_body',
            field=models.TextField(blank=True, default='', help_text='Основной текст обзора. Plain text с разделителями \\n\\n. Markdown не поддерживается. Длина ≤5000 символов.', validators=[django.core.validators.MaxLengthValidator(5000)], verbose_name='Обзор: основной текст'),
        ),
        migrations.AddField(
            model_name='acmodel',
            name='editorial_lede',
            field=models.TextField(blank=True, default='', help_text='Вводный абзац редакторского обзора. Показывается первым абзацем в секции «Обзор» на детальной странице.', verbose_name='Обзор: вводный абзац'),
        ),
        migrations.AddField(
            model_name='acmodel',
            name='editorial_quote',
            field=models.TextField(blank=True, default='', help_text='Цитата-выноска редактора (pull quote).', verbose_name='Обзор: цитата'),
        ),
        migrations.AddField(
            model_name='acmodel',
            name='editorial_quote_author',
            field=models.CharField(blank=True, default='', help_text='Например: «А. Петров, главред».', max_length=200, verbose_name='Обзор: автор цитаты'),
        ),
    ]
