# Generated by Django 4.2.7 on 2026-04-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac_catalog', '0002_add_editorial_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='acmodel',
            name='inner_unit_dimensions',
            field=models.CharField(blank=True, default='', help_text='Например: «850 × 295 × 189 мм». Свободная форма строки.', max_length=100, verbose_name='Габариты внутреннего блока'),
        ),
        migrations.AddField(
            model_name='acmodel',
            name='inner_unit_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Вес внутреннего блока (кг)'),
        ),
        migrations.AddField(
            model_name='acmodel',
            name='outer_unit_dimensions',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Габариты наружного блока'),
        ),
        migrations.AddField(
            model_name='acmodel',
            name='outer_unit_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Вес наружного блока (кг)'),
        ),
        # SQL DEFAULT '' для CharField NOT NULL — нужно для COPY-загрузки
        # старых дампов без новых колонок. Weight-поля nullable, дефолт не нужен.
        migrations.RunSQL(
            sql=(
                "ALTER TABLE ac_catalog_acmodel "
                "ALTER COLUMN inner_unit_dimensions SET DEFAULT '', "
                "ALTER COLUMN outer_unit_dimensions SET DEFAULT '';"
            ),
            reverse_sql=(
                "ALTER TABLE ac_catalog_acmodel "
                "ALTER COLUMN inner_unit_dimensions DROP DEFAULT, "
                "ALTER COLUMN outer_unit_dimensions DROP DEFAULT;"
            ),
        ),
    ]
