# Generated by Django 4.2.7 on 2026-04-21 09:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac_catalog', '0003_add_unit_dimensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='acmodelsupplier',
            name='availability',
            field=models.CharField(choices=[('in_stock', 'В наличии'), ('low_stock', 'Осталось мало'), ('out_of_stock', 'Нет в наличии'), ('unknown', 'Не известно')], default='unknown', max_length=20, verbose_name='Наличие'),
        ),
        migrations.AddField(
            model_name='acmodelsupplier',
            name='city',
            field=models.CharField(blank=True, default='', help_text='Город склада / магазина, например «Москва».', max_length=100, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='acmodelsupplier',
            name='note',
            field=models.CharField(blank=True, default='', help_text='Например: «с монтажом · 2 дня», «самовывоз · завтра».', max_length=200, verbose_name='Пометка'),
        ),
        migrations.AddField(
            model_name='acmodelsupplier',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Цена у поставщика. null = не известна.', max_digits=10, null=True, verbose_name='Цена (руб.)'),
        ),
        migrations.AddField(
            model_name='acmodelsupplier',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='0.0–5.0.', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг магазина'),
        ),
        # SQL DEFAULT для NOT NULL колонок — нужно для COPY-загрузки
        # старых дампов без этих колонок. price/rating nullable, дефолт не нужен.
        migrations.RunSQL(
            sql=(
                "ALTER TABLE ac_catalog_acmodelsupplier "
                "ALTER COLUMN city SET DEFAULT '', "
                "ALTER COLUMN note SET DEFAULT '', "
                "ALTER COLUMN availability SET DEFAULT 'unknown';"
            ),
            reverse_sql=(
                "ALTER TABLE ac_catalog_acmodelsupplier "
                "ALTER COLUMN city DROP DEFAULT, "
                "ALTER COLUMN note DROP DEFAULT, "
                "ALTER COLUMN availability DROP DEFAULT;"
            ),
        ),
    ]
