"""Wave 13: тесты semantic_rename_images management команды + service."""
from __future__ import annotations

import io
import os
from io import StringIO
from unittest.mock import patch

import pytest
from django.core.files.storage import default_storage
from django.core.files.uploadedfile import SimpleUploadedFile
from django.core.management import call_command
from django.core.management.base import CommandError
from PIL import Image

from news.models import MediaUpload, NewsDuplicateGroup, NewsMedia, NewsPost
from news.services_semantic_naming import (
    build_context,
    build_prompt,
    collect_post_images,
    is_auto_generated_basename,
    parse_slug,
    plan_new_storage_name,
    replace_basename_in_html,
    url_to_storage_name,
)
from news.tests.factories import NewsPostFactory


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

def _png_bytes() -> bytes:
    buf = io.BytesIO()
    Image.new("RGB", (4, 4), "white").save(buf, format="PNG")
    return buf.getvalue()


@pytest.fixture
def media_root(tmp_path, settings):
    settings.MEDIA_ROOT = str(tmp_path)
    settings.GEMINI_API_KEY = "test-key"
    return str(tmp_path)


@pytest.fixture
def admin_user(db):
    from django.contrib.auth.models import User
    return User.objects.create_superuser(username="t", password="x", email="t@t.t")


# ---------------------------------------------------------------------------
# url_to_storage_name
# ---------------------------------------------------------------------------

class TestUrlToStorageName:
    def test_relative_media_url(self):
        assert (
            url_to_storage_name("/media/news/uploads/2026/02/snimok_x.png")
            == "news/uploads/2026/02/snimok_x.png"
        )

    def test_relative_hvac_media_url(self):
        assert (
            url_to_storage_name("/hvac-media/news/media/foo.jpg")
            == "news/media/foo.jpg"
        )

    def test_absolute_url(self):
        assert (
            url_to_storage_name("https://hvac-info.com/media/news/X/y.png")
            == "news/X/y.png"
        )

    def test_percent_encoded(self):
        # %D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA = «Снимок»
        assert (
            url_to_storage_name(
                "/media/news/uploads/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA.png"
            )
            == "news/uploads/Снимок.png"
        )

    def test_non_media_url(self):
        assert url_to_storage_name("/static/img/logo.svg") is None

    def test_empty_url(self):
        assert url_to_storage_name("") is None
        assert url_to_storage_name(None) is None

    def test_url_with_query_string_stripped(self):
        assert (
            url_to_storage_name("/media/news/x.png?v=2")
            == "news/x.png"
        )


# ---------------------------------------------------------------------------
# is_auto_generated_basename
# ---------------------------------------------------------------------------

class TestIsAutoGeneratedBasename:
    @pytest.mark.parametrize("name", [
        "snimok_ehkrana_2026-02-12.png",
        "snimok-x.jpg",
        "screenshot-1.png",
        "screen_2026.png",
        "image.png",
        "image-1.png",
        "img_42.jpg",
        "photo.jpg",
        "photo-3.png",
        "untitled.png",
        "untitled-design.jpg",
        "file.png",
        "file-1.jpg",
        "media.png",
        "upload.jpg",
        "12345.png",
        "abcdef0123456789.png",  # 16-hex
        "foto.png",
        "kartinka.jpg",
        "izobrazhenie-1.png",
    ])
    def test_auto_generated(self, name):
        assert is_auto_generated_basename(name) is True, name

    @pytest.mark.parametrize("name", [
        "novyi-kompressor-danfoss.jpg",
        "danfoss-launch-2026.png",
        "rotational-compressor-review.jpg",
        "vrf-system-installation.png",
    ])
    def test_semantic_kept(self, name):
        assert is_auto_generated_basename(name) is False, name


# ---------------------------------------------------------------------------
# parse_slug
# ---------------------------------------------------------------------------

class TestParseSlug:
    def test_clean_response(self):
        assert parse_slug("novyi-kompressor-danfoss") == "novyi-kompressor-danfoss"

    def test_underscore_to_dash(self):
        assert parse_slug("novyi_kompressor_danfoss") == "novyi-kompressor-danfoss"

    def test_strip_quotes(self):
        assert parse_slug('"novyi-kompressor"') == "novyi-kompressor"
        assert parse_slug("'rotational-compressor'") == "rotational-compressor"

    def test_strip_backticks(self):
        assert parse_slug("`some-slug-here`") == "some-slug-here"

    def test_multiline_takes_first(self):
        assert parse_slug("danfoss-news\n\nObjasnenie") == "danfoss-news"

    def test_uppercase_lowered(self):
        assert parse_slug("NOVYI-KOMPRESSOR") == "novyi-kompressor"

    def test_collapse_dashes(self):
        assert parse_slug("foo--bar---baz") == "foo-bar-baz"

    def test_strip_leading_trailing_dash(self):
        assert parse_slug("-foo-bar-") == "foo-bar"

    def test_too_short_returns_none(self):
        assert parse_slug("abc") is None  # < 5 chars

    def test_too_long_returns_none(self):
        assert parse_slug("a" * 100) is None

    def test_empty_returns_none(self):
        assert parse_slug("") is None
        assert parse_slug(None) is None
        assert parse_slug("   ") is None

    def test_pure_cyrillic_after_clean_returns_none(self):
        # После strip non-latin останется пусто.
        assert parse_slug("кондиционер") is None

    def test_mixed_letters_strip_cyrillic(self):
        # «danfoss-новый» → «danfoss-» после удаления нелатиницы → «danfoss».
        # Это короче 5 символов? «danfoss» = 7 → ОК.
        assert parse_slug("danfoss-новый") == "danfoss"

    def test_rejects_punctuation_chars(self):
        # Slash, скобки и пробелы — обрезаются → итог должен пройти validate.
        assert parse_slug("foo/bar baz") == "foo-bar-baz"


# ---------------------------------------------------------------------------
# replace_basename_in_html
# ---------------------------------------------------------------------------

class TestReplaceBasenameInHtml:
    def test_basic_img_src(self):
        html = '<p>X</p><img src="/media/news/old.png" alt="x">'
        out, n = replace_basename_in_html(html, "old.png", "new.png")
        assert n == 1
        assert "/media/news/new.png" in out
        assert "old.png" not in out

    def test_href_a_tag(self):
        html = '<a href="https://hvac-info.com/media/news/old.jpg">link</a>'
        out, n = replace_basename_in_html(html, "old.jpg", "new.jpg")
        assert n == 1
        assert "new.jpg" in out

    def test_css_url(self):
        html = '<div style="background: url(/media/news/old.png)"></div>'
        out, n = replace_basename_in_html(html, "old.png", "new.png")
        assert n == 1
        assert "url(/media/news/new.png)" in out

    def test_idempotent_same_basename(self):
        html = '<img src="/media/news/x.png">'
        out, n = replace_basename_in_html(html, "x.png", "x.png")
        assert n == 0
        assert out == html

    def test_no_replacements_when_basename_absent(self):
        html = '<img src="/media/news/foo.png">'
        out, n = replace_basename_in_html(html, "bar.png", "baz.png")
        assert n == 0
        assert out == html

    def test_does_not_touch_plain_text(self):
        # basename как plain-text (не в src/href/url()) не должен заменяться,
        # чтобы избежать ложных срабатываний.
        html = '<p>Файл old.png упомянут в тексте</p>'
        out, n = replace_basename_in_html(html, "old.png", "new.png")
        assert n == 0
        assert out == html

    def test_multiple_occurrences(self):
        html = (
            '<img src="/media/a/old.png">'
            '<img src="/media/b/old.png">'
        )
        out, n = replace_basename_in_html(html, "old.png", "new.png")
        assert n == 2
        assert out.count("new.png") == 2


# ---------------------------------------------------------------------------
# plan_new_storage_name
# ---------------------------------------------------------------------------

class TestPlanNewStorageName:
    def test_basic(self, media_root):
        # Без коллизии — просто dirname/slug.ext.
        assert (
            plan_new_storage_name(
                "news/uploads/2026/02/snimok_x.png", "novyi-news", default_storage
            )
            == "news/uploads/2026/02/novyi-news.png"
        )

    def test_no_dirname(self, media_root):
        assert (
            plan_new_storage_name("snimok.png", "x-y-z-w", default_storage)
            == "x-y-z-w.png"
        )

    def test_collision_with_existing_file(self, media_root):
        # Создаём «занятый» файл на storage.
        default_storage.save(
            "news/uploads/foo.png",
            SimpleUploadedFile("foo.png", _png_bytes()),
        )
        # foo.png занят → должен подобрать foo-2.png.
        result = plan_new_storage_name(
            "news/uploads/snimok.png", "foo", default_storage
        )
        assert result == "news/uploads/foo-2.png"

    def test_collision_via_extra_taken(self, media_root):
        # foo.png НЕ существует на disk, но «зарезервирован» в этом run-е.
        result = plan_new_storage_name(
            "news/uploads/snimok.png",
            "foo",
            default_storage,
            extra_taken={"news/uploads/foo.png"},
        )
        assert result == "news/uploads/foo-2.png"

    def test_same_old_path_returned_when_slug_matches(self, media_root):
        # Если новый path == старому — возвращаем как есть, без увеличения суффикса.
        assert (
            plan_new_storage_name(
                "news/uploads/foo.png", "foo", default_storage
            )
            == "news/uploads/foo.png"
        )


# ---------------------------------------------------------------------------
# collect_post_images
# ---------------------------------------------------------------------------

@pytest.mark.django_db
class TestCollectPostImages:
    def test_inline_only(self):
        post = NewsPostFactory(
            body='<p>Текст</p><img src="/media/news/uploads/2026/02/snimok_x.png" alt="alt-text">',
        )
        refs = collect_post_images(post)
        assert len(refs) == 1
        assert refs[0].storage_name == "news/uploads/2026/02/snimok_x.png"
        assert refs[0].alt == "alt-text"

    def test_news_media_fk(self, media_root):
        post = NewsPostFactory(body="")
        upload = SimpleUploadedFile("snimok_y.png", _png_bytes())
        media = NewsMedia.objects.create(
            news_post=post, file=upload, media_type="image",
            original_name="snimok_y.png",
        )
        refs = collect_post_images(post)
        assert len(refs) == 1
        assert refs[0].storage_name == media.file.name
        assert media in refs[0].file_field_owners

    def test_dedup_inline_and_fk(self, media_root):
        # Создаём NewsMedia + ссылаемся в body на тот же файл.
        post = NewsPostFactory(body="placeholder")
        upload = SimpleUploadedFile("snimok_z.png", _png_bytes())
        media = NewsMedia.objects.create(
            news_post=post, file=upload, media_type="image",
            original_name="snimok_z.png",
        )
        post.body = f'<img src="/media/{media.file.name}" alt="alt">'
        post.save(update_fields=["body"])

        refs = collect_post_images(post)
        assert len(refs) == 1
        assert refs[0].alt == "alt"
        assert media in refs[0].file_field_owners

    def test_lede_and_rating_explanation(self):
        post = NewsPostFactory(
            body="",
            lede='<img src="/media/news/uploads/lede_img.png">',
            rating_explanation='<img src="/media/news/uploads/rating_img.png">',
        )
        refs = collect_post_images(post)
        snames = sorted(r.storage_name for r in refs)
        assert snames == [
            "news/uploads/lede_img.png",
            "news/uploads/rating_img.png",
        ]

    def test_duplicate_group_merged_body(self):
        group = NewsDuplicateGroup.objects.create(
            merged_title="merged",
            merged_body='<img src="/media/news/uploads/group_img.png">',
            source_count=1,
        )
        post = NewsPostFactory(body="", duplicate_group=group)
        refs = collect_post_images(post)
        assert any(r.storage_name == "news/uploads/group_img.png" for r in refs)


# ---------------------------------------------------------------------------
# build_context / build_prompt
# ---------------------------------------------------------------------------

@pytest.mark.django_db
class TestBuildContext:
    def test_window_around_basename(self):
        post = NewsPostFactory(
            title="Новый компрессор Danfoss",
            body=(
                "Левый текст до картинки. "
                '<img src="/media/news/uploads/snimok_x.png">'
                " Правый текст после картинки."
            ),
        )
        from news.services_semantic_naming import ImageRef
        ref = ImageRef(storage_name="news/uploads/snimok_x.png")
        ctx = build_context(post, ref, window=80)
        assert "Левый текст" in ctx
        assert "Правый текст" in ctx

    def test_falls_back_to_lede_if_basename_absent(self):
        post = NewsPostFactory(
            title="t",
            body="нет картинки в теле",
            lede="лид-абзац новости",
        )
        from news.services_semantic_naming import ImageRef
        ref = ImageRef(storage_name="news/uploads/notfound.png")
        ctx = build_context(post, ref, window=50)
        assert "лид-абзац" in ctx

    def test_build_prompt_includes_title_alt_context(self):
        post = NewsPostFactory(
            title="Новый компрессор Danfoss",
            body="контекст вокруг snimok_x.png и дальше",
        )
        from news.services_semantic_naming import ImageRef
        ref = ImageRef(storage_name="news/uploads/snimok_x.png", alt="my alt")
        prompt = build_prompt(post, ref)
        assert "Новый компрессор Danfoss" in prompt
        assert "my alt" in prompt
        assert "контекст" in prompt


# ---------------------------------------------------------------------------
# Management command — full integration
# ---------------------------------------------------------------------------

@pytest.fixture
def post_with_inline_image(media_root, admin_user):
    """NewsPost с одной inline auto-generated картинкой, файл на disk."""
    storage_name = "news/uploads/2026/02/snimok_ehkrana_x.png"
    default_storage.save(storage_name, SimpleUploadedFile("snimok_ehkrana_x.png", _png_bytes()))
    post = NewsPostFactory(
        title="Новый ротационный компрессор Danfoss",
        body=f'<p>Лид</p><img src="/media/{storage_name}" alt="компрессор">',
    )
    return post, storage_name


@pytest.mark.django_db
class TestCommandDryRun:
    def test_dry_run_does_not_change_files(self, post_with_inline_image):
        post, storage_name = post_with_inline_image
        with patch("news.services_semantic_naming.NewsLLMClient.query_raw") as mock_q:
            mock_q.return_value = "novyi-kompressor-danfoss"
            out = StringIO()
            call_command(
                "semantic_rename_images",
                "--post-id", str(post.id),
                "--sleep", "0",
                stdout=out,
            )
        text = out.getvalue()
        # В выводе видим планируемое имя.
        assert "novyi-kompressor-danfoss" in text
        # Файл на storage остался под старым именем.
        assert default_storage.exists(storage_name)
        assert not default_storage.exists("news/uploads/2026/02/novyi-kompressor-danfoss.png")
        # body не изменился.
        post.refresh_from_db()
        assert "snimok_ehkrana_x.png" in post.body

    def test_warning_about_dry_run_in_output(self, post_with_inline_image):
        post, _ = post_with_inline_image
        with patch("news.services_semantic_naming.NewsLLMClient.query_raw") as mock_q:
            mock_q.return_value = "novyi-kompressor-danfoss"
            out = StringIO()
            call_command(
                "semantic_rename_images",
                "--post-id", str(post.id),
                "--sleep", "0",
                stdout=out,
            )
        assert "DRY RUN" in out.getvalue()


@pytest.mark.django_db
class TestCommandExecute:
    def test_execute_renames_file(self, post_with_inline_image):
        post, storage_name = post_with_inline_image
        with patch("news.services_semantic_naming.NewsLLMClient.query_raw") as mock_q:
            mock_q.return_value = "novyi-kompressor-danfoss"
            out = StringIO()
            call_command(
                "semantic_rename_images",
                "--post-id", str(post.id),
                "--execute", "--sleep", "0",
                stdout=out,
            )
        # Файл переехал.
        assert not default_storage.exists(storage_name)
        new_path = "news/uploads/2026/02/novyi-kompressor-danfoss.png"
        assert default_storage.exists(new_path)
        # body обновился.
        post.refresh_from_db()
        assert "novyi-kompressor-danfoss.png" in post.body
        assert "snimok_ehkrana_x.png" not in post.body

    def test_execute_updates_news_media_fk(self, media_root, admin_user):
        # Создаём NewsMedia с auto-generated именем.
        post = NewsPostFactory(
            title="Промышленные климат-системы",
            body="контекст вокруг файла",
        )
        upload = SimpleUploadedFile("snimok_ehkrana_y.png", _png_bytes())
        media = NewsMedia.objects.create(
            news_post=post, file=upload, media_type="image",
            original_name="snimok_ehkrana_y.png",
        )
        old_name = media.file.name

        with patch("news.services_semantic_naming.NewsLLMClient.query_raw") as mock_q:
            mock_q.return_value = "promyshlennye-klimat-sistemy"
            call_command(
                "semantic_rename_images",
                "--post-id", str(post.id),
                "--execute", "--sleep", "0",
                stdout=StringIO(),
            )
        media.refresh_from_db()
        assert media.file.name != old_name
        assert "promyshlennye-klimat-sistemy" in media.file.name

    def test_execute_updates_duplicate_group_merged_body(self, media_root, admin_user):
        storage_name = "news/uploads/snimok_dup.png"
        default_storage.save(storage_name, SimpleUploadedFile("snimok_dup.png", _png_bytes()))
        group = NewsDuplicateGroup.objects.create(
            merged_title="merged",
            merged_body=f'<img src="/media/{storage_name}" alt="x">',
            source_count=2,
        )
        post = NewsPostFactory(
            title="Дубль новости про Daikin",
            body="",
            duplicate_group=group,
        )
        with patch("news.services_semantic_naming.NewsLLMClient.query_raw") as mock_q:
            mock_q.return_value = "dubl-novosti-daikin"
            call_command(
                "semantic_rename_images",
                "--post-id", str(post.id),
                "--execute", "--sleep", "0",
                stdout=StringIO(),
            )
        group.refresh_from_db()
        assert "dubl-novosti-daikin" in group.merged_body
        assert "snimok_dup.png" not in group.merged_body


@pytest.mark.django_db
class TestCommandSkipping:
    def test_skip_already_semantic(self, media_root, admin_user):
        storage_name = "news/uploads/novyi-kompressor-danfoss.png"
        default_storage.save(storage_name, SimpleUploadedFile("x.png", _png_bytes()))
        post = NewsPostFactory(
            title="t", body=f'<img src="/media/{storage_name}">',
        )
        with patch("news.services_semantic_naming.NewsLLMClient.query_raw") as mock_q:
            mock_q.return_value = "should-not-be-called"
            out = StringIO()
            call_command(
                "semantic_rename_images",
                "--post-id", str(post.id),
                "--execute", "--sleep", "0",
                stdout=out,
            )
        # LLM не вызван — basename уже семантический.
        mock_q.assert_not_called()
        assert "skip already-semantic" in out.getvalue()
        # Файл на месте.
        assert default_storage.exists(storage_name)

    def test_force_overrides_already_semantic(self, media_root, admin_user):
        storage_name = "news/uploads/novyi-kompressor-danfoss.png"
        default_storage.save(storage_name, SimpleUploadedFile("x.png", _png_bytes()))
        post = NewsPostFactory(
            title="Запуск нового бренда AUX",
            body=f'<img src="/media/{storage_name}">',
        )
        with patch("news.services_semantic_naming.NewsLLMClient.query_raw") as mock_q:
            mock_q.return_value = "zapusk-novogo-brenda-aux"
            call_command(
                "semantic_rename_images",
                "--post-id", str(post.id),
                "--execute", "--force", "--sleep", "0",
                stdout=StringIO(),
            )
        mock_q.assert_called_once()
        assert default_storage.exists("news/uploads/zapusk-novogo-brenda-aux.png")

    def test_llm_failure_skips(self, post_with_inline_image):
        post, storage_name = post_with_inline_image
        with patch("news.services_semantic_naming.NewsLLMClient.query_raw") as mock_q:
            mock_q.return_value = None  # provider failed
            call_command(
                "semantic_rename_images",
                "--post-id", str(post.id),
                "--execute", "--sleep", "0",
                stdout=StringIO(),
            )
        # Файл остался под старым именем.
        assert default_storage.exists(storage_name)
        post.refresh_from_db()
        assert "snimok_ehkrana_x.png" in post.body

    def test_llm_returns_garbage_skips(self, post_with_inline_image):
        post, storage_name = post_with_inline_image
        with patch("news.services_semantic_naming.NewsLLMClient.query_raw") as mock_q:
            mock_q.return_value = "OK"  # too short
            call_command(
                "semantic_rename_images",
                "--post-id", str(post.id),
                "--execute", "--sleep", "0",
                stdout=StringIO(),
            )
        assert default_storage.exists(storage_name)


@pytest.mark.django_db
class TestCommandValidation:
    def test_missing_gemini_key_raises(self, post_with_inline_image, settings):
        post, _ = post_with_inline_image
        settings.GEMINI_API_KEY = ""
        with pytest.raises(CommandError):
            call_command(
                "semantic_rename_images",
                "--post-id", str(post.id),
                "--sleep", "0",
                stdout=StringIO(),
            )

    def test_alternative_provider_grok(self, post_with_inline_image, settings):
        """С --provider grok проверяется XAI_API_KEY, а не GEMINI."""
        post, _ = post_with_inline_image
        settings.GEMINI_API_KEY = ""
        settings.XAI_API_KEY = "test-grok-key"
        with patch("news.services_semantic_naming.NewsLLMClient.query_raw") as mock_q:
            mock_q.return_value = "novyi-kompressor-grok"
            out = StringIO()
            call_command(
                "semantic_rename_images",
                "--post-id", str(post.id),
                "--provider", "grok",
                "--sleep", "0",
                stdout=out,
            )
        assert "novyi-kompressor-grok" in out.getvalue()


@pytest.mark.django_db
class TestCommandCollision:
    def test_collision_resolved_with_suffix(self, media_root, admin_user):
        # Существует «занятый» файл с целевым именем.
        default_storage.save(
            "news/uploads/danfoss-news.png",
            SimpleUploadedFile("a.png", _png_bytes()),
        )
        # А вот этот мы хотим переименовать в danfoss-news → должен попасть в danfoss-news-2.
        storage_name = "news/uploads/snimok_collision.png"
        default_storage.save(storage_name, SimpleUploadedFile("b.png", _png_bytes()))
        post = NewsPostFactory(
            title="Danfoss news",
            body=f'<img src="/media/{storage_name}">',
        )
        with patch("news.services_semantic_naming.NewsLLMClient.query_raw") as mock_q:
            mock_q.return_value = "danfoss-news"
            call_command(
                "semantic_rename_images",
                "--post-id", str(post.id),
                "--execute", "--sleep", "0",
                stdout=StringIO(),
            )
        assert default_storage.exists("news/uploads/danfoss-news-2.png")
        post.refresh_from_db()
        assert "danfoss-news-2.png" in post.body


@pytest.mark.django_db
class TestCommandShared:
    def test_shared_image_renamed_once(self, media_root, admin_user):
        """Картинка-«сирота», на которую ссылаются два поста, переименовывается
        ровно один раз внутри одного запуска команды; LLM вызван один раз;
        body обоих постов обновляется."""
        storage_name = "news/uploads/snimok_shared.png"
        default_storage.save(storage_name, SimpleUploadedFile("x.png", _png_bytes()))
        group = NewsDuplicateGroup.objects.create(
            merged_title="m", merged_body="", source_count=2,
        )
        body = f'<img src="/media/{storage_name}">'
        post_a = NewsPostFactory(
            title="Daikin запускает завод",
            body=body, duplicate_group=group,
        )
        post_b = NewsPostFactory(
            title="Daikin запускает завод (другой источник)",
            body=body, duplicate_group=group,
        )

        with patch("news.services_semantic_naming.NewsLLMClient.query_raw") as mock_q:
            mock_q.return_value = "daikin-zavod-launch"
            # Без --post-id — пройдёт по обоим постам в одном запуске.
            call_command(
                "semantic_rename_images",
                "--execute", "--sleep", "0",
                stdout=StringIO(),
            )
        # LLM вызван ровно один раз — второй пост увидел картинку в rename_map.
        assert mock_q.call_count == 1
        # Файл существует под новым именем.
        new_path = "news/uploads/daikin-zavod-launch.png"
        assert default_storage.exists(new_path)
        # Старого файла нет.
        assert not default_storage.exists(storage_name)
        # Оба body обновились.
        post_a.refresh_from_db()
        post_b.refresh_from_db()
        assert "daikin-zavod-launch.png" in post_a.body
        assert "daikin-zavod-launch.png" in post_b.body
