# Generated by Django 4.2.7 on 2025-12-13 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import estimates.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0003_add_vendor_subtype_to_counterparty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pricelists', '0002_alter_pricelistagreement_options'),
        ('objects', '0002_object_end_date_object_start_date_object_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Номер сметы')),
                ('name', models.CharField(max_length=255, verbose_name='Название сметы')),
                ('with_vat', models.BooleanField(default=True, verbose_name='С НДС')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=20.0, max_digits=4, verbose_name='Ставка НДС, %')),
                ('man_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Человеко-часы')),
                ('usd_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Курс USD')),
                ('eur_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Курс EUR')),
                ('cny_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Курс CNY')),
                ('file', models.FileField(blank=True, null=True, upload_to=estimates.models.estimate_file_path, verbose_name='Excel-файл сметы')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('in_progress', 'В работе'), ('checking', 'На проверке'), ('approved', 'Утверждена'), ('sent', 'Отправлена Заказчику'), ('agreed', 'Согласована Заказчиком'), ('rejected', 'Отклонена')], default='draft', max_length=20, verbose_name='Статус')),
                ('approved_by_customer', models.BooleanField(default=False, verbose_name='Согласовано Заказчиком')),
                ('approved_date', models.DateField(blank=True, null=True, verbose_name='Дата согласования')),
                ('version_number', models.PositiveIntegerField(default=1, verbose_name='Номер версии')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_estimates', to=settings.AUTH_USER_MODEL, verbose_name='Кто утвердил')),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_estimates', to=settings.AUTH_USER_MODEL, verbose_name='Кто проверил')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_estimates', to=settings.AUTH_USER_MODEL, verbose_name='Кто составил')),
                ('legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estimates', to='accounting.legalentity', verbose_name='Наша компания')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to='objects.object', verbose_name='Объект')),
                ('parent_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_versions', to='estimates.estimate', verbose_name='Предыдущая версия')),
                ('price_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimates', to='pricelists.pricelist', verbose_name='Прайс-лист для расчёта')),
            ],
            options={
                'verbose_name': 'Смета',
                'verbose_name_plural': 'Сметы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EstimateSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=255, verbose_name='Название раздела')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='estimates.estimate', verbose_name='Смета')),
            ],
            options={
                'verbose_name': 'Раздел сметы',
                'verbose_name_plural': 'Разделы сметы',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('cipher', models.CharField(max_length=100, verbose_name='Шифр проекта')),
                ('name', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('date', models.DateField(verbose_name='Дата проекта')),
                ('stage', models.CharField(choices=[('П', 'Проектная документация'), ('РД', 'Рабочая документация')], max_length=10, verbose_name='Стадия')),
                ('file', models.FileField(upload_to=estimates.models.project_file_path, verbose_name='ZIP-архив проекта')),
                ('notes', models.TextField(blank=True, verbose_name='Общие примечания')),
                ('is_approved_for_production', models.BooleanField(default=False, verbose_name='Разрешение "В производство работ"')),
                ('production_approval_file', models.FileField(blank=True, null=True, upload_to=estimates.models.project_approval_path, verbose_name='Скан разрешения')),
                ('production_approval_date', models.DateField(blank=True, null=True, verbose_name='Дата получения разрешения')),
                ('primary_check_done', models.BooleanField(default=False, verbose_name='Первичная проверка выполнена')),
                ('primary_check_date', models.DateField(blank=True, null=True, verbose_name='Дата первичной проверки')),
                ('secondary_check_done', models.BooleanField(default=False, verbose_name='Вторичная проверка выполнена')),
                ('secondary_check_date', models.DateField(blank=True, null=True, verbose_name='Дата вторичной проверки')),
                ('version_number', models.PositiveIntegerField(default=1, verbose_name='Номер версии')),
                ('is_current', models.BooleanField(default=True, verbose_name='Актуальная версия')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='objects.object', verbose_name='Объект строительства')),
                ('parent_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_versions', to='estimates.project', verbose_name='Предыдущая версия')),
                ('primary_check_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_checked_projects', to=settings.AUTH_USER_MODEL, verbose_name='Кто проверил (первичная)')),
                ('secondary_check_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_checked_projects', to=settings.AUTH_USER_MODEL, verbose_name='Кто проверил (вторичная)')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-date', '-created_at'],
                'unique_together': {('cipher', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ProjectNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('text', models.TextField(verbose_name='Текст замечания')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_notes', to=settings.AUTH_USER_MODEL, verbose_name='Автор замечания')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_notes', to='estimates.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Замечание к проекту',
                'verbose_name_plural': 'Замечания к проектам',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MountingEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Номер')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Итоговая сумма (без НДС)')),
                ('man_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Человеко-часы')),
                ('file', models.FileField(blank=True, null=True, upload_to=estimates.models.mounting_estimate_file_path, verbose_name='Excel-файл')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('sent', 'Отправлена'), ('approved', 'Согласована'), ('rejected', 'Отклонена')], default='draft', max_length=20, verbose_name='Статус')),
                ('agreed_date', models.DateField(blank=True, null=True, verbose_name='Дата согласования')),
                ('version_number', models.PositiveIntegerField(default=1, verbose_name='Номер версии')),
                ('agreed_counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreed_mounting_estimates', to='accounting.counterparty', verbose_name='Согласовано с Исполнителем')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_mounting_estimates', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mounting_estimates', to='objects.object', verbose_name='Объект')),
                ('parent_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_versions', to='estimates.mountingestimate', verbose_name='Предыдущая версия')),
                ('source_estimate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mounting_estimates', to='estimates.estimate', verbose_name='Исходная смета')),
            ],
            options={
                'verbose_name': 'Монтажная смета',
                'verbose_name_plural': 'Монтажные сметы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EstimateSubsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=255, verbose_name='Название подраздела')),
                ('materials_sale', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Материалы — продажа')),
                ('works_sale', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Работы — продажа')),
                ('materials_purchase', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Материалы — закупка')),
                ('works_purchase', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Работы — закупка')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='estimates.estimatesection', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Подраздел сметы',
                'verbose_name_plural': 'Подразделы сметы',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EstimateCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('purchase_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Сумма закупки')),
                ('sale_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Сумма продажи')),
                ('is_auto_calculated', models.BooleanField(default=False, verbose_name='Автоматически рассчитано')),
                ('source_type', models.CharField(choices=[('sections', 'Из разделов сметы'), ('manual', 'Введено вручную')], default='manual', max_length=20, verbose_name='Источник данных')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='estimates.estimate', verbose_name='Смета')),
            ],
            options={
                'verbose_name': 'Характеристика сметы',
                'verbose_name_plural': 'Характеристики сметы',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='estimate',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='estimates', to='estimates.project', verbose_name='Проекты-основания'),
        ),
    ]
