# Generated by Django 4.2.7 on 2026-02-23 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_productworkmapping'),
        ('pricelists', '0007_workitem_required_grade_alter_workitem_grade'),
        ('estimates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('item_number', models.PositiveIntegerField(default=0, verbose_name='Номер по порядку')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование товара / работы')),
                ('model_name', models.CharField(blank=True, max_length=300, verbose_name='Модель / артикул')),
                ('unit', models.CharField(default='шт', max_length=50, verbose_name='Единица измерения')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Количество')),
                ('material_unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Цена материала за ед.')),
                ('work_unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Цена работы за ед.')),
                ('is_analog', models.BooleanField(default=False, verbose_name='Применён аналог')),
                ('analog_reason', models.TextField(blank=True, verbose_name='Обоснование применения аналога')),
                ('original_name', models.CharField(blank=True, max_length=500, verbose_name='Оригинальное наименование из спецификации')),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='estimates.estimate', verbose_name='Смета')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimate_items', to='catalog.product', verbose_name='Товар из каталога')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='estimates.estimatesection', verbose_name='Раздел')),
                ('source_price_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimate_items', to='catalog.productpricehistory', verbose_name='Источник цены (из истории)')),
                ('subsection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='estimates.estimatesubsection', verbose_name='Подраздел')),
                ('work_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimate_items', to='pricelists.workitem', verbose_name='Работа из прайс-листа')),
            ],
            options={
                'verbose_name': 'Строка сметы',
                'verbose_name_plural': 'Строки сметы',
                'ordering': ['section__sort_order', 'sort_order', 'item_number'],
                'indexes': [models.Index(fields=['estimate', 'section'], name='estimates_e_estimat_aa755a_idx'), models.Index(fields=['product'], name='estimates_e_product_8a35dd_idx'), models.Index(fields=['work_item'], name='estimates_e_work_it_62d504_idx'), models.Index(fields=['is_analog'], name='estimates_e_is_anal_87da0e_idx')],
            },
        ),
    ]
