# Generated by Django 4.2.7 on 2026-03-16 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_public', '0001_initial'),
        ('estimates', '0005_estimateitem_supplier_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecificationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
                ('model_name', models.CharField(blank=True, max_length=300, verbose_name='Модель/артикул')),
                ('brand', models.CharField(blank=True, max_length=255, verbose_name='Бренд/производитель')),
                ('unit', models.CharField(default='шт', max_length=50, verbose_name='Единица измерения')),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=14, verbose_name='Количество')),
                ('tech_specs_raw', models.TextField(blank=True, verbose_name='Тех. характеристики (из документа)')),
                ('section_name', models.CharField(blank=True, help_text='ОВ, ВК, ЭО, АР, КР и т.д.', max_length=255, verbose_name='Раздел проекта')),
                ('page_number', models.PositiveIntegerField(default=0, verbose_name='Страница в документе')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_items', to='api_public.estimaterequest', verbose_name='Запрос')),
                ('source_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spec_items', to='api_public.estimaterequestfile', verbose_name='Исходный файл')),
            ],
            options={
                'verbose_name': 'Позиция спецификации (сырые данные)',
                'verbose_name_plural': 'Позиции спецификации (сырые данные)',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
