# Generated by Django 4.2.7 on 2026-03-26 09:04

import os
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import estimates.models


SEED_FILE_TYPES = [
    {'name': 'Полный проект', 'code': 'full_project', 'sort_order': 1},
    {'name': 'Графическая часть', 'code': 'graphics', 'sort_order': 2},
    {'name': 'Спецификация', 'code': 'specification', 'sort_order': 3},
    {'name': 'Техника', 'code': 'technique', 'sort_order': 4},
]


def seed_file_types(apps, schema_editor):
    ProjectFileType = apps.get_model('estimates', 'ProjectFileType')
    for ft in SEED_FILE_TYPES:
        ProjectFileType.objects.get_or_create(code=ft['code'], defaults=ft)


def unseed_file_types(apps, schema_editor):
    ProjectFileType = apps.get_model('estimates', 'ProjectFileType')
    codes = [ft['code'] for ft in SEED_FILE_TYPES]
    ProjectFileType.objects.filter(code__in=codes).delete()


def migrate_existing_files(apps, schema_editor):
    """Мигрировать Project.file -> ProjectFile с типом 'Полный проект'."""
    Project = apps.get_model('estimates', 'Project')
    ProjectFile = apps.get_model('estimates', 'ProjectFile')
    ProjectFileType = apps.get_model('estimates', 'ProjectFileType')

    full_project_type = ProjectFileType.objects.filter(code='full_project').first()
    if not full_project_type:
        return

    for project in Project.objects.exclude(file='').exclude(file__isnull=True):
        original_name = os.path.basename(project.file.name) if project.file else ''
        ProjectFile.objects.get_or_create(
            project=project,
            file=project.file.name,
            defaults={
                'file_type': full_project_type,
                'title': '',
                'original_filename': original_name,
            },
        )


def reverse_migrate_files(apps, schema_editor):
    ProjectFile = apps.get_model('estimates', 'ProjectFile')
    ProjectFile.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estimates', '0007_increase_name_max_length_to_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Тип файла проекта',
                'verbose_name_plural': 'Типы файлов проектов',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.RunPython(seed_file_types, unseed_file_types),
        migrations.AlterField(
            model_name='project',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=estimates.models.project_file_path, verbose_name='Файл проекта (устаревшее — используйте ProjectFile)'),
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('file', models.FileField(upload_to=estimates.models.project_multi_file_path, verbose_name='Файл')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название файла')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Оригинальное имя файла')),
                ('file_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_files', to='estimates.projectfiletype', verbose_name='Тип файла')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_files', to='estimates.project', verbose_name='Проект')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_project_files', to=settings.AUTH_USER_MODEL, verbose_name='Кто загрузил')),
            ],
            options={
                'verbose_name': 'Файл проекта',
                'verbose_name_plural': 'Файлы проекта',
                'ordering': ['file_type__sort_order', 'created_at'],
            },
        ),
        migrations.RunPython(migrate_existing_files, reverse_migrate_files),
    ]
