# Generated by Django 4.2.7 on 2026-03-26 09:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0008_projectfiletype_projectfile_and_file_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimateMarkupDefaults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('material_markup_percent', models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=7, verbose_name='Наценка на материалы по умолчанию (%)')),
                ('work_markup_percent', models.DecimalField(decimal_places=2, default=Decimal('300.00'), max_digits=7, verbose_name='Наценка на работы по умолчанию (%)')),
            ],
            options={
                'verbose_name': 'Наценки по умолчанию',
                'verbose_name_plural': 'Наценки по умолчанию',
            },
        ),
        migrations.AddField(
            model_name='estimate',
            name='default_material_markup_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=7, verbose_name='Наценка на материалы по умолчанию (%)'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='default_work_markup_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('300.00'), max_digits=7, verbose_name='Наценка на работы по умолчанию (%)'),
        ),
        migrations.AddField(
            model_name='estimateitem',
            name='material_markup_type',
            field=models.CharField(blank=True, choices=[('percent', 'Процент'), ('fixed_price', 'Продажная цена'), ('fixed_amount', 'Фикс. сумма')], max_length=20, null=True, verbose_name='Тип наценки на материалы'),
        ),
        migrations.AddField(
            model_name='estimateitem',
            name='material_markup_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Значение наценки на материалы'),
        ),
        migrations.AddField(
            model_name='estimateitem',
            name='work_markup_type',
            field=models.CharField(blank=True, choices=[('percent', 'Процент'), ('fixed_price', 'Продажная цена'), ('fixed_amount', 'Фикс. сумма')], max_length=20, null=True, verbose_name='Тип наценки на работы'),
        ),
        migrations.AddField(
            model_name='estimateitem',
            name='work_markup_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Значение наценки на работы'),
        ),
        migrations.AddField(
            model_name='estimatesection',
            name='material_markup_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Пусто = наследовать от сметы', max_digits=7, null=True, verbose_name='Наценка на материалы (%)'),
        ),
        migrations.AddField(
            model_name='estimatesection',
            name='work_markup_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Пусто = наследовать от сметы', max_digits=7, null=True, verbose_name='Наценка на работы (%)'),
        ),
        migrations.AlterField(
            model_name='estimateitem',
            name='material_unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Цена материала за ед. (закупка)'),
        ),
        migrations.AlterField(
            model_name='estimateitem',
            name='work_unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Цена работы за ед. (закупка)'),
        ),
    ]
