# Generated by Django 4.2.7 on 2026-03-26 09:26

from decimal import Decimal
from django.db import migrations


def populate_markup_defaults(apps, schema_editor):
    """
    Создать глобальные дефолты наценок.
    Для существующих смет — установить дефолтные наценки 30%/300%.
    Пересчитать все подразделы (purchase = sale при 0% markup, но мы ставим 30%/300%).
    """
    EstimateMarkupDefaults = apps.get_model('estimates', 'EstimateMarkupDefaults')
    EstimateMarkupDefaults.objects.get_or_create(
        pk=1,
        defaults={
            'material_markup_percent': Decimal('30.00'),
            'work_markup_percent': Decimal('300.00'),
        }
    )

    # Все существующие сметы получают дефолтные наценки
    Estimate = apps.get_model('estimates', 'Estimate')
    Estimate.objects.all().update(
        default_material_markup_percent=Decimal('30.00'),
        default_work_markup_percent=Decimal('300.00'),
    )

    # Пересчитать подразделы для каждой сметы:
    # purchase = sum(qty * unit_price), sale = purchase * (1 + markup/100)
    EstimateSubsection = apps.get_model('estimates', 'EstimateSubsection')
    EstimateItem = apps.get_model('estimates', 'EstimateItem')

    mat_markup = Decimal('30.00')
    work_markup = Decimal('300.00')
    mat_mult = 1 + mat_markup / 100
    work_mult = 1 + work_markup / 100

    for sub in EstimateSubsection.objects.all():
        items = EstimateItem.objects.filter(subsection=sub)
        mat_purchase = Decimal('0')
        work_purchase = Decimal('0')
        for item in items:
            qty = item.quantity or Decimal('0')
            mat_purchase += qty * (item.material_unit_price or Decimal('0'))
            work_purchase += qty * (item.work_unit_price or Decimal('0'))

        sub.materials_purchase = mat_purchase.quantize(Decimal('0.01'))
        sub.works_purchase = work_purchase.quantize(Decimal('0.01'))
        sub.materials_sale = (mat_purchase * mat_mult).quantize(Decimal('0.01'))
        sub.works_sale = (work_purchase * work_mult).quantize(Decimal('0.01'))
        sub.save(update_fields=[
            'materials_purchase', 'works_purchase',
            'materials_sale', 'works_sale',
        ])


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0009_markup_system'),
    ]

    operations = [
        migrations.RunPython(populate_markup_defaults, reverse_noop),
    ]
