# Generated by Django 4.2.7 on 2026-04-14 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_public', '0002_externaluser'),
        ('estimates', '0010_markup_data_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='external_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimates', to='api_public.externaluser', verbose_name='Внешний пользователь'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='public_source',
            field=models.BooleanField(default=False, help_text='True если смета создана внешним пользователем', verbose_name='Из публичного портала'),
        ),
    ]
