# Generated by Django 4.2.7 on 2025-11-11 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, verbose_name='Номер договора')),
                ('name', models.CharField(max_length=255, verbose_name='Название / предмет договора')),
                ('contract_date', models.DateField(verbose_name='Дата заключения')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала работ')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Плановая дата завершения')),
                ('contractor', models.CharField(max_length=255, verbose_name='Контрагент')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сумма договора')),
                ('currency', models.CharField(choices=[('RUB', 'Российский рубль'), ('USD', 'Доллар США'), ('EUR', 'Евро')], default='RUB', max_length=3, verbose_name='Валюта')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=20.0, max_digits=4, verbose_name='Ставка НДС, %')),
                ('vat_included', models.BooleanField(default=True, verbose_name='Сумма включает НДС')),
                ('status', models.CharField(choices=[('planned', 'Планируется'), ('active', 'В работе'), ('completed', 'Завершён'), ('suspended', 'Приостановлен'), ('terminated', 'Расторгнут')], default='planned', max_length=20, verbose_name='Статус')),
                ('document_link', models.CharField(blank=True, max_length=500, verbose_name='Ссылка на договор')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='objects.object', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
                'ordering': ['-contract_date', '-created_at'],
                'unique_together': {('object', 'number')},
            },
        ),
    ]
