# Generated by Django 4.2.7 on 2026-03-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0007_add_language_to_newsresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='is_kmp',
            field=models.BooleanField(default=False, help_text='Крупный мировой производитель (LG, DAIKIN, Mitsubishi и т.д.). Любые новости от КМП автоматически получают рейтинг не ниже 4 звёзд.', verbose_name='KMP (Key Market Producer)'),
        ),
    ]
