# Generated by Django 4.2.7 on 2026-04-18 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandOriginClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('origin_type', models.CharField(max_length=255, unique=True, verbose_name='Тип происхождения')),
                ('fallback_score', models.FloatField(default=50, help_text='Балл по умолчанию для мощности компрессора при отсутствии данных', verbose_name='Fallback-балл')),
            ],
            options={
                'verbose_name': 'Тип происхождения бренда',
                'verbose_name_plural': 'Типы происхождения брендов',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('logo', models.ImageField(blank=True, default='', upload_to='ac_rating/brands/', verbose_name='Логотип')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('sales_start_year_ru', models.PositiveSmallIntegerField(blank=True, help_text='Например: 2015', null=True, verbose_name='Год начала продаж в РФ')),
                ('origin_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brands', to='ac_brands.brandoriginclass', verbose_name='Тип происхождения')),
            ],
            options={
                'verbose_name': 'Бренд (рейтинг кондиционеров)',
                'verbose_name_plural': 'Бренды (рейтинг кондиционеров)',
                'ordering': ['name'],
            },
        ),
    ]
