# Generated by Django 4.2.7 on 2026-04-18 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('code', models.CharField(help_text='Уникальный код параметра, напр. noise_min', max_length=50, unique=True, verbose_name='Код')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Название (RU)')),
                ('name_en', models.CharField(blank=True, default='', max_length=255, verbose_name='Название (EN)')),
                ('name_de', models.CharField(blank=True, default='', max_length=255, verbose_name='Название (DE)')),
                ('name_pt', models.CharField(blank=True, default='', max_length=255, verbose_name='Название (PT)')),
                ('description_ru', models.TextField(blank=True, default='', verbose_name='Описание (RU)')),
                ('description_en', models.TextField(blank=True, default='', verbose_name='Описание (EN)')),
                ('description_de', models.TextField(blank=True, default='', verbose_name='Описание (DE)')),
                ('description_pt', models.TextField(blank=True, default='', verbose_name='Описание (PT)')),
                ('unit', models.CharField(blank=True, default='', max_length=50, verbose_name='Ед. измерения')),
                ('photo', models.ImageField(blank=True, default='', upload_to='ac_rating/criteria/', verbose_name='Фото')),
                ('value_type', models.CharField(choices=[('numeric', 'Числовой'), ('binary', 'Бинарный (да/нет)'), ('categorical', 'Категориальный'), ('custom_scale', 'Индивидуальная шкала'), ('formula', 'Формульная логика'), ('lab', 'Лабораторный'), ('fallback', 'С fallback-логикой'), ('brand_age', 'Возраст бренда в РФ')], max_length=30, verbose_name='Тип значения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Параметр',
                'verbose_name_plural': 'Параметры',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='MethodologyCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('scoring_type', models.CharField(choices=[('min_median_max', 'Min / Median / Max'), ('binary', 'Бинарный (0 или 100)'), ('universal_scale', 'Универсальная шкала (100/70/50/30/0)'), ('custom_scale', 'Индивидуальная шкала (JSON)'), ('formula', 'Формула (JSON)'), ('interval', 'Интервальная шкала')], max_length=30, verbose_name='Тип скоринга')),
                ('weight', models.FloatField(default=0, help_text='Вес параметра в процентах. Сумма весов всех параметров = 100%', verbose_name='Вес (%)')),
                ('min_value', models.FloatField(blank=True, null=True, verbose_name='Min')),
                ('median_value', models.FloatField(blank=True, null=True, verbose_name='Медиана')),
                ('max_value', models.FloatField(blank=True, null=True, verbose_name='Max')),
                ('is_inverted', models.BooleanField(default=False, help_text='Если включено: min = хорошо (100), max = плохо (0). Для шума, вибрации и т.п.', verbose_name='Инвертированная шкала')),
                ('median_by_capacity', models.JSONField(blank=True, help_text='Формат: {"2.0": 0.18, "2.5": 0.21, "3.5": 0.30}. Ключ — номинальная мощность кВт, значение — медиана.', null=True, verbose_name='Медианы по мощности (JSON)')),
                ('custom_scale_json', models.JSONField(blank=True, help_text='Формат: {"значение": балл, ...} или [{"from": x, "to": y, "score": z}, ...]', null=True, verbose_name='Индивидуальная шкала (JSON)')),
                ('formula_json', models.JSONField(blank=True, help_text='Описание формулы расчёта для формульных параметров', null=True, verbose_name='Формула (JSON)')),
                ('is_required_lab', models.BooleanField(default=False, verbose_name='Обязателен для LAB режима')),
                ('is_required_checklist', models.BooleanField(default=False, verbose_name='Обязателен для CHECKLIST')),
                ('is_required_catalog', models.BooleanField(default=False, verbose_name='Обязателен для CATALOG')),
                ('use_in_lab', models.BooleanField(default=True, verbose_name='Используется в LAB')),
                ('use_in_checklist', models.BooleanField(default=True, verbose_name='Используется в CHECKLIST')),
                ('use_in_catalog', models.BooleanField(default=True, verbose_name='Используется в CATALOG')),
                ('region_scope', models.CharField(choices=[('global', 'Глобальный'), ('ru', 'Только Россия'), ('eu', 'Только Европа')], default='global', max_length=10, verbose_name='Регион')),
                ('is_public', models.BooleanField(default=True, verbose_name='Публичный')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methodology_entries', to='ac_methodology.criterion', verbose_name='Параметр')),
            ],
            options={
                'verbose_name': 'Параметр методики',
                'verbose_name_plural': 'Параметры методики',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='MethodologyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('version', models.CharField(max_length=30, unique=True, verbose_name='Версия')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('tab_description_index', models.TextField(blank=True, default='', verbose_name='Описание таба «По индексу»')),
                ('tab_description_quiet', models.TextField(blank=True, default='', verbose_name='Описание таба «Самые тихие»')),
                ('tab_description_custom', models.TextField(blank=True, default='', verbose_name='Описание таба «Пользовательский рейтинг»')),
                ('is_active', models.BooleanField(default=False, help_text='Только одна методика может быть активной', verbose_name='Активна')),
                ('needs_recalculation', models.BooleanField(default=False, help_text='Устанавливается при изменении весов или формул', verbose_name='Требуется пересчёт')),
                ('criteria', models.ManyToManyField(related_name='methodologies', through='ac_methodology.MethodologyCriterion', to='ac_methodology.criterion', verbose_name='Параметры')),
            ],
            options={
                'verbose_name': 'Версия методики',
                'verbose_name_plural': 'Версии методики',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='methodologycriterion',
            name='methodology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methodology_criteria', to='ac_methodology.methodologyversion', verbose_name='Методика'),
        ),
        migrations.AddConstraint(
            model_name='methodologycriterion',
            constraint=models.UniqueConstraint(fields=('methodology', 'criterion'), name='unique_methodology_criterion'),
        ),
        migrations.AddConstraint(
            model_name='methodologycriterion',
            constraint=models.CheckConstraint(check=models.Q(('weight__gte', 0)), name='mc_weight_non_negative'),
        ),
    ]
