# Generated by Django 4.2.7 on 2026-04-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac_methodology', '0003_populate_criterion_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='Slug')),
                ('label', models.CharField(max_length=128, verbose_name='Название')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('is_all_selected', models.BooleanField(default=False, help_text='Если включено — M2M игнорируется, пресет включает все активные критерии активной методики.', verbose_name='Выбирает все критерии')),
                ('criteria', models.ManyToManyField(blank=True, related_name='presets', to='ac_methodology.criterion', verbose_name='Критерии')),
            ],
            options={
                'verbose_name': 'Пресет «Свой рейтинг»',
                'verbose_name_plural': 'Пресеты «Свой рейтинг»',
                'ordering': ['order', 'label'],
            },
        ),
    ]
