# Generated by Django 4.2.7 on 2026-04-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac_methodology', '0005_seed_initial_presets'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterion',
            name='is_key_measurement',
            field=models.BooleanField(default=False, help_text='Выделяется отдельным визуальным блоком на детальной странице модели (teal badge «КЛЮЧЕВОЙ ЗАМЕР» + первая позиция в списке критериев).', verbose_name='Ключевой замер'),
        ),
        # Django drops DEFAULT on the column after AddField. Keep SQL-level
        # DEFAULT false для COPY-based загрузки старых pg_dump'ов
        # (`load_ac_rating_dump`), где колонка `is_key_measurement`
        # отсутствует. Та же история, что с 0002 для `group`.
        migrations.RunSQL(
            sql="ALTER TABLE ac_methodology_criterion "
                "ALTER COLUMN is_key_measurement SET DEFAULT false;",
            reverse_sql="ALTER TABLE ac_methodology_criterion "
                        "ALTER COLUMN is_key_measurement DROP DEFAULT;",
        ),
    ]
