# Generated by Django 4.2.7 on 2026-02-14 22:32

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kanban_core', '0003_attachment_delivery_batch_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('warehouse', 'Склад'), ('object', 'Объект')], max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('erp_object_id', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Локация склада',
                'verbose_name_plural': 'Локации склада',
                'unique_together': {('kind', 'erp_object_id')},
            },
        ),
        migrations.CreateModel(
            name='StockMove',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('move_type', models.CharField(choices=[('IN', 'Приход'), ('OUT', 'Расход (выдача)'), ('ADJUST', 'Корректировка')], max_length=16)),
                ('delivery_batch_id', models.UUIDField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_by_user_id', models.IntegerField(blank=True, null=True)),
                ('created_by_username', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_moves', to='kanban_core.card')),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moves_out', to='kanban_warehouse.stocklocation')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moves_in', to='kanban_warehouse.stocklocation')),
            ],
            options={
                'verbose_name': 'Движение склада',
                'verbose_name_plural': 'Движения склада',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockMoveLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('erp_product_id', models.IntegerField(blank=True, null=True)),
                ('product_name', models.CharField(max_length=512)),
                ('unit', models.CharField(default='шт', max_length=32)),
                ('qty', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=16)),
                ('move', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='kanban_warehouse.stockmove')),
            ],
            options={
                'verbose_name': 'Строка движения',
                'verbose_name_plural': 'Строки движения',
                'indexes': [models.Index(fields=['erp_product_id'], name='kanban_ware_erp_pro_0bfe6e_idx')],
            },
        ),
    ]
