# Generated by Django 4.2.7 on 2026-02-14 22:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kanban_core', '0002_card_assignee_user_id_card_assignee_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('event_type', models.CharField(max_length=64)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('conditions', models.JSONField(blank=True, default=dict)),
                ('actions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='kanban_core.board')),
            ],
            options={
                'verbose_name': 'Правило',
                'verbose_name_plural': 'Правила',
            },
        ),
        migrations.CreateModel(
            name='RuleExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='ok', max_length=16)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_executions', to='kanban_core.cardevent')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='kanban_rules.rule')),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='kanban_rule_created_dcd5bf_idx')],
                'unique_together': {('rule', 'event')},
            },
        ),
        migrations.AddIndex(
            model_name='rule',
            index=models.Index(fields=['board', 'event_type', 'is_active'], name='kanban_rule_board_i_c8c4d9_idx'),
        ),
    ]
