# Generated by Django 4.2.7 on 2025-11-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AddField(
            model_name='object',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала'),
        ),
        migrations.AddField(
            model_name='object',
            name='status',
            field=models.CharField(choices=[('planned', 'Планируется'), ('in_progress', 'В работе'), ('completed', 'Завершен')], default='in_progress', max_length=20, verbose_name='Статус'),
        ),
    ]
