# Generated by Django 4.2.7 on 2025-12-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0002_object_end_date_object_start_date_object_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='status',
            field=models.CharField(choices=[('planned', 'Планируется'), ('in_progress', 'В работе'), ('completed', 'Завершен'), ('suspended', 'Приостановлен')], default='in_progress', max_length=20, verbose_name='Статус'),
        ),
    ]
