# Generated by Django 4.2.13 on 2026-02-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0003_alter_object_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='geo_radius',
            field=models.IntegerField(default=500, help_text='Радиус для проверки геолокации при регистрации на смену', verbose_name='Радиус геозоны в метрах'),
        ),
        migrations.AddField(
            model_name='object',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Широта (центр геозоны)'),
        ),
        migrations.AddField(
            model_name='object',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Долгота (центр геозоны)'),
        ),
    ]
