# Generated by Django 4.2.7 on 2026-02-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0004_add_geo_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='allow_geo_bypass',
            field=models.BooleanField(default=False, help_text='Если включено, монтажники смогут регистрироваться на смену находясь за пределами геозоны (с пометкой)', verbose_name='Разрешить регистрацию вне геозоны'),
        ),
    ]
