# Generated by Django 4.2.7 on 2026-02-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0005_add_allow_geo_bypass'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='registration_window_minutes',
            field=models.PositiveIntegerField(default=0, help_text='За сколько минут до начала и после окончания смены разрешена регистрация. 0 = без ограничений.', verbose_name='Окно регистрации (минуты)'),
        ),
    ]
