# Generated by Django 4.2.7

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0008_banking_fields'),
        ('payments', '0009_alter_payment_scan_file_paymentitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('provider', models.CharField(choices=[('tochka', 'Банк Точка')], default='tochka', max_length=30, verbose_name='Банк-провайдер')),
                ('name', models.CharField(help_text='Например: "Точка — основной счёт ООО Август"', max_length=255, verbose_name='Название подключения')),
                ('client_id', models.CharField(max_length=500, verbose_name='Client ID')),
                ('client_secret', models.CharField(max_length=500, verbose_name='Client Secret')),
                ('access_token', models.TextField(blank=True, default='', verbose_name='Access Token')),
                ('refresh_token', models.TextField(blank=True, default='', verbose_name='Refresh Token')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Срок действия access token')),
                ('customer_code', models.CharField(blank=True, help_text='Уникальный идентификатор клиента в банке (customerCode)', max_length=100, verbose_name='Customer Code')),
                ('payment_mode', models.CharField(choices=[('for_sign', 'Черновик (подпись через банк)'), ('auto_sign', 'Автоподпись через API')], default='for_sign', max_length=20, verbose_name='Режим платежей')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация')),
                ('legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_connections', to='accounting.legalentity', verbose_name='Юридическое лицо')),
            ],
            options={
                'verbose_name': 'Банковское подключение',
                'verbose_name_plural': 'Банковские подключения',
                'ordering': ['legal_entity', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('external_account_id', models.CharField(help_text='accountId из API банка', max_length=100, verbose_name='ID счёта в банке')),
                ('last_statement_date', models.DateField(blank=True, null=True, verbose_name='Дата последней выписки')),
                ('sync_enabled', models.BooleanField(default=True, verbose_name='Синхронизация включена')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to='accounting.account', verbose_name='Внутренний счёт')),
                ('bank_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='banking.bankconnection', verbose_name='Банковское подключение')),
            ],
            options={
                'verbose_name': 'Банковский счёт (привязка)',
                'verbose_name_plural': 'Банковские счета (привязки)',
                'ordering': ['bank_connection', 'account'],
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('external_id', models.CharField(help_text='paymentId из API банка', max_length=100, unique=True, verbose_name='ID платежа в банке')),
                ('transaction_type', models.CharField(choices=[('incoming', 'Входящий'), ('outgoing', 'Исходящий')], max_length=20, verbose_name='Тип транзакции')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сумма')),
                ('date', models.DateField(verbose_name='Дата операции')),
                ('purpose', models.TextField(blank=True, verbose_name='Назначение платежа')),
                ('counterparty_name', models.CharField(blank=True, max_length=255, verbose_name='Наименование контрагента')),
                ('counterparty_inn', models.CharField(blank=True, max_length=12, verbose_name='ИНН контрагента')),
                ('counterparty_kpp', models.CharField(blank=True, max_length=9, verbose_name='КПП контрагента')),
                ('counterparty_account', models.CharField(blank=True, max_length=20, verbose_name='Счёт контрагента')),
                ('counterparty_bank_name', models.CharField(blank=True, max_length=255, verbose_name='Банк контрагента')),
                ('counterparty_bik', models.CharField(blank=True, max_length=9, verbose_name='БИК банка контрагента')),
                ('counterparty_corr_account', models.CharField(blank=True, max_length=20, verbose_name='Корр. счёт банка контрагента')),
                ('document_number', models.CharField(blank=True, max_length=50, verbose_name='Номер документа')),
                ('reconciled', models.BooleanField(default=False, verbose_name='Сверено')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='Полный ответ банка')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='banking.bankaccount', verbose_name='Банковский счёт')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transactions', to='payments.payment', verbose_name='Внутренний платёж')),
            ],
            options={
                'verbose_name': 'Банковская транзакция',
                'verbose_name_plural': 'Банковские транзакции',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankPaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('recipient_name', models.CharField(max_length=255, verbose_name='Наименование получателя')),
                ('recipient_inn', models.CharField(max_length=12, verbose_name='ИНН получателя')),
                ('recipient_kpp', models.CharField(blank=True, max_length=9, verbose_name='КПП получателя')),
                ('recipient_account', models.CharField(max_length=20, verbose_name='Расчётный счёт получателя')),
                ('recipient_bank_name', models.CharField(max_length=255, verbose_name='Банк получателя')),
                ('recipient_bik', models.CharField(max_length=9, verbose_name='БИК банка получателя')),
                ('recipient_corr_account', models.CharField(blank=True, max_length=20, verbose_name='Корр. счёт банка получателя')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сумма')),
                ('purpose', models.TextField(verbose_name='Назначение платежа')),
                ('vat_info', models.CharField(blank=True, help_text='Например: "В т.ч. НДС 20% — 1000.00 руб." или "Без НДС"', max_length=255, verbose_name='Информация о НДС')),
                ('payment_date', models.DateField(help_text='Может переноситься многократно до отправки в банк', verbose_name='Запланированная дата оплаты')),
                ('original_payment_date', models.DateField(help_text='Устанавливается при создании и не меняется', verbose_name='Первоначальная дата оплаты')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('pending_approval', 'На согласовании'), ('approved', 'Одобрено'), ('sent_to_bank', 'Отправлено в банк'), ('pending_sign', 'Ожидает подписи'), ('executed', 'Исполнено'), ('rejected', 'Отклонено'), ('failed', 'Ошибка')], default='draft', max_length=20, verbose_name='Статус')),
                ('external_request_id', models.CharField(blank=True, max_length=100, verbose_name='ID запроса в банке')),
                ('external_payment_id', models.CharField(blank=True, max_length=100, verbose_name='ID платежа в банке')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата одобрения')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки в банк')),
                ('executed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата исполнения')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('raw_response', models.JSONField(blank=True, null=True, verbose_name='Полный ответ банка')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_bank_orders', to=settings.AUTH_USER_MODEL, verbose_name='Одобрено пользователем')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_orders', to='banking.bankaccount', verbose_name='Банковский счёт списания')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_bank_orders', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем')),
                ('payment_registry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_payment_order', to='payments.paymentregistry', verbose_name='Заявка из реестра')),
            ],
            options={
                'verbose_name': 'Платёжное поручение',
                'verbose_name_plural': 'Платёжные поручения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankPaymentOrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('event_type', models.CharField(choices=[('created', 'Создано'), ('submitted', 'Отправлено на согласование'), ('approved', 'Одобрено'), ('rejected', 'Отклонено'), ('rescheduled', 'Перенос даты оплаты'), ('sent_to_bank', 'Отправлено в банк'), ('executed', 'Исполнено'), ('failed', 'Ошибка'), ('comment', 'Комментарий')], max_length=30, verbose_name='Тип события')),
                ('old_value', models.JSONField(blank=True, help_text='Например: {"payment_date": "2026-03-01", "status": "approved"}', null=True, verbose_name='Предыдущее значение')),
                ('new_value', models.JSONField(blank=True, help_text='Например: {"payment_date": "2026-03-15"}', null=True, verbose_name='Новое значение')),
                ('comment', models.TextField(blank=True, help_text='Причина переноса, комментарий к решению и т.д.', verbose_name='Комментарий')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='banking.bankpaymentorder', verbose_name='Платёжное поручение')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_order_events', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Событие платёжного поручения',
                'verbose_name_plural': 'События платёжных поручений',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['date'], name='banking_ban_date_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['bank_account', 'date'], name='banking_ban_bank_acc_date_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['counterparty_inn'], name='banking_ban_counter_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['reconciled'], name='banking_ban_reconci_idx'),
        ),
        migrations.AddIndex(
            model_name='bankpaymentorder',
            index=models.Index(fields=['status'], name='banking_ban_status_idx'),
        ),
        migrations.AddIndex(
            model_name='bankpaymentorder',
            index=models.Index(fields=['payment_date'], name='banking_ban_payment_idx'),
        ),
        migrations.AddIndex(
            model_name='bankpaymentorder',
            index=models.Index(fields=['status', 'payment_date'], name='banking_ban_status_pay_idx'),
        ),
    ]
