# Generated by Django 4.2.7 on 2026-02-14 10:11

import banking.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bankpaymentorder',
            new_name='banking_ban_status_19ad6c_idx',
            old_name='banking_ban_status_idx',
        ),
        migrations.RenameIndex(
            model_name='bankpaymentorder',
            new_name='banking_ban_payment_cb6edd_idx',
            old_name='banking_ban_payment_idx',
        ),
        migrations.RenameIndex(
            model_name='bankpaymentorder',
            new_name='banking_ban_status_e9713b_idx',
            old_name='banking_ban_status_pay_idx',
        ),
        migrations.RenameIndex(
            model_name='banktransaction',
            new_name='banking_ban_date_7c96e7_idx',
            old_name='banking_ban_date_idx',
        ),
        migrations.RenameIndex(
            model_name='banktransaction',
            new_name='banking_ban_bank_ac_be3862_idx',
            old_name='banking_ban_bank_acc_date_idx',
        ),
        migrations.RenameIndex(
            model_name='banktransaction',
            new_name='banking_ban_counter_21e9ec_idx',
            old_name='banking_ban_counter_idx',
        ),
        migrations.RenameIndex(
            model_name='banktransaction',
            new_name='banking_ban_reconci_ed7586_idx',
            old_name='banking_ban_reconci_idx',
        ),
        migrations.AlterField(
            model_name='bankconnection',
            name='access_token',
            field=banking.encryption.EncryptedTextField(blank=True, default='', verbose_name='Access Token'),
        ),
        migrations.AlterField(
            model_name='bankconnection',
            name='client_id',
            field=banking.encryption.EncryptedCharField(verbose_name='Client ID'),
        ),
        migrations.AlterField(
            model_name='bankconnection',
            name='client_secret',
            field=banking.encryption.EncryptedCharField(verbose_name='Client Secret'),
        ),
        migrations.AlterField(
            model_name='bankconnection',
            name='refresh_token',
            field=banking.encryption.EncryptedTextField(blank=True, default='', verbose_name='Refresh Token'),
        ),
    ]
