# Generated by Django 4.2.7 on 2026-02-14 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_invoice_supply_request_incomerecord_account_and_more'),
        ('banking', '0002_rename_banking_ban_status_idx_banking_ban_status_19ad6c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_bank_transactions', to='payments.invoice', verbose_name='Счёт на оплату'),
        ),
        migrations.AlterField(
            model_name='bankpaymentorder',
            name='payment_registry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_payment_order', to='payments.paymentregistry', verbose_name='Заявка из реестра (LEGACY)'),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transactions', to='payments.payment', verbose_name='Внутренний платёж (LEGACY)'),
        ),
    ]
