# Generated by Django 4.2.13 on 2026-02-07 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objects', '0004_add_geo_fields'),
        ('accounting', '0004_legalentity_director_legalentity_director_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_number', models.IntegerField(default=1, verbose_name='Номер отчёта за смену')),
                ('report_type', models.CharField(choices=[('intermediate', 'Промежуточный'), ('final', 'Финальный'), ('supplement', 'Дополнение')], max_length=16, verbose_name='Тип отчёта')),
                ('trigger', models.CharField(choices=[('manual', 'Вручную'), ('member_change', 'Изменение состава'), ('shift_end', 'Закрытие смены'), ('auto', 'Автоматически')], max_length=16, verbose_name='Триггер создания')),
                ('media_count', models.IntegerField(default=0, verbose_name='Количество медиа')),
                ('members_snapshot', models.JSONField(blank=True, default=list, verbose_name='Состав звена на момент отчёта')),
                ('divider_message_id', models.IntegerField(blank=True, null=True, verbose_name='ID разделителя в Telegram')),
                ('first_message_id', models.IntegerField(blank=True, null=True, verbose_name='Первый message_id в отчёте')),
                ('last_message_id', models.IntegerField(blank=True, null=True, verbose_name='Последний message_id в отчёте')),
                ('status', models.CharField(choices=[('submitted', 'Отправлен'), ('questions_pending', 'Ожидает ответов'), ('completed', 'Завершён')], default='submitted', max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Отчёт',
                'verbose_name_plural': 'Отчёты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Дата смены')),
                ('shift_type', models.CharField(choices=[('day', 'Дневная'), ('evening', 'Вечерняя'), ('night', 'Ночная')], default='day', max_length=16, verbose_name='Тип смены')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('qr_code', models.TextField(blank=True, verbose_name='Данные QR-кода')),
                ('qr_token', models.CharField(blank=True, max_length=128, unique=True, verbose_name='Одноразовый токен QR')),
                ('status', models.CharField(choices=[('scheduled', 'Запланирована'), ('active', 'Активна'), ('closed', 'Закрыта')], default='scheduled', max_length=16, verbose_name='Статус')),
                ('extended_until', models.DateTimeField(blank=True, null=True, verbose_name='Продлена до')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='accounting.counterparty', verbose_name='Исполнитель')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='objects.object', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Смена',
                'verbose_name_plural': 'Смены',
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic_id', models.IntegerField(blank=True, null=True, verbose_name='ID топика в Telegram (message_thread_id)')),
                ('topic_name', models.CharField(blank=True, max_length=255, verbose_name='Название топика')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('closed', 'Закрыто')], default='active', max_length=16, verbose_name='Статус')),
                ('is_solo', models.BooleanField(default=False, verbose_name='Соло-режим (один человек)')),
            ],
            options={
                'verbose_name': 'Звено',
                'verbose_name_plural': 'Звенья',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон')),
                ('photo_url', models.URLField(blank=True, verbose_name='URL фото профиля')),
                ('role', models.CharField(choices=[('worker', 'Монтажник'), ('brigadier', 'Бригадир')], default='worker', max_length=16, verbose_name='Роль')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('uz', 'Узбекский'), ('tg', 'Таджикский'), ('ky', 'Киргизский')], default='ru', max_length=4, verbose_name='Язык интерфейса')),
                ('bot_started', models.BooleanField(default=False, verbose_name='Написал /start боту')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='accounting.counterparty', verbose_name='Исполнитель (контрагент)')),
            ],
            options={
                'verbose_name': 'Монтажник',
                'verbose_name_plural': 'Монтажники',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда присоединился')),
                ('left_at', models.DateTimeField(blank=True, null=True, verbose_name='Когда вышел')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='worklog.team', verbose_name='Звено')),
                ('triggered_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_by_membership', to='worklog.report', verbose_name='Отчёт при изменении состава')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to='worklog.worker', verbose_name='Монтажник')),
            ],
            options={
                'verbose_name': 'Участие в звене',
                'verbose_name_plural': 'Участия в звеньях',
            },
        ),
        migrations.AddField(
            model_name='team',
            name='brigadier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_teams', to='worklog.worker', verbose_name='Бригадир звена'),
        ),
        migrations.AddField(
            model_name='team',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='accounting.counterparty', verbose_name='Исполнитель'),
        ),
        migrations.AddField(
            model_name='team',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_teams', to='worklog.worker', verbose_name='Кто создал звено'),
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(related_name='teams', through='worklog.TeamMembership', to='worklog.worker', verbose_name='Участники'),
        ),
        migrations.AddField(
            model_name='team',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='objects.object', verbose_name='Объект'),
        ),
        migrations.AddField(
            model_name='team',
            name='previous_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_teams', to='worklog.team', verbose_name='Предыдущее звено с тем же составом'),
        ),
        migrations.AddField(
            model_name='team',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='worklog.shift', verbose_name='Смена'),
        ),
        migrations.AddField(
            model_name='report',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reports', to='worklog.worker', verbose_name='Кто создал'),
        ),
        migrations.AddField(
            model_name='report',
            name='parent_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplements', to='worklog.report', verbose_name='Родительский отчёт'),
        ),
        migrations.AddField(
            model_name='report',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='worklog.shift', verbose_name='Смена'),
        ),
        migrations.AddField(
            model_name='report',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='worklog.team', verbose_name='Звено'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asked_by', models.CharField(choices=[('backend_auto', 'Автоматически (бекенд)'), ('office', 'Офис'), ('contractor', 'Исполнитель')], max_length=16, verbose_name='Кто задал')),
                ('question_text', models.TextField(verbose_name='Текст вопроса')),
                ('question_type', models.CharField(choices=[('text', 'Свободный ввод'), ('choice', 'Выбор из вариантов'), ('media', 'Запрос медиа'), ('confirm', 'Да/Нет')], default='text', max_length=16, verbose_name='Тип вопроса')),
                ('choices', models.JSONField(blank=True, default=list, verbose_name='Варианты ответа')),
                ('message_id', models.IntegerField(blank=True, null=True, verbose_name='ID сообщения с вопросом в Telegram')),
                ('status', models.CharField(choices=[('pending', 'Ожидает ответа'), ('answered', 'Отвечен'), ('expired', 'Просрочен')], default='pending', max_length=16, verbose_name='Статус')),
                ('asked_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asked_questions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь-автор')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='worklog.report', verbose_name='Отчёт')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_questions', to='worklog.worker', verbose_name='Кому адресован')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='worklog.team', verbose_name='Звено')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_id', models.IntegerField(blank=True, null=True, verbose_name='ID сообщения в Telegram')),
                ('media_type', models.CharField(choices=[('photo', 'Фото'), ('video', 'Видео'), ('audio', 'Аудио'), ('voice', 'Голосовое'), ('document', 'Документ'), ('text', 'Текст')], max_length=16, verbose_name='Тип медиа')),
                ('tag', models.CharField(choices=[('none', 'Без тега'), ('problem', 'Проблема'), ('supply', 'Снабжение'), ('final_report', 'Финальное фото')], default='none', max_length=16, verbose_name='Тег')),
                ('tag_source', models.CharField(choices=[('none', 'Нет'), ('reaction', 'Реакция'), ('hashtag', 'Хештег'), ('manual', 'Вручную')], default='none', max_length=16, verbose_name='Источник тега')),
                ('file_id', models.CharField(blank=True, max_length=512, verbose_name='Telegram file_id')),
                ('file_unique_id', models.CharField(blank=True, max_length=256, verbose_name='Telegram file_unique_id')),
                ('file_url', models.URLField(blank=True, verbose_name='URL в S3')),
                ('file_size', models.IntegerField(blank=True, null=True, verbose_name='Размер в байтах')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='Длительность (сек)')),
                ('thumbnail_url', models.URLField(blank=True, verbose_name='URL превью')),
                ('text_content', models.TextField(blank=True, verbose_name='Текст / подпись')),
                ('exif_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата из EXIF')),
                ('phash', models.CharField(blank=True, max_length=64, verbose_name='Perceptual hash')),
                ('status', models.CharField(choices=[('pending', 'Ожидает скачивания'), ('downloaded', 'Скачано'), ('committed', 'В отчёте'), ('deleted', 'Удалено')], default='pending', max_length=16, verbose_name='Статус')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='worklog.worker', verbose_name='Автор')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media', to='worklog.report', verbose_name='Отчёт')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='worklog.team', verbose_name='Звено')),
            ],
            options={
                'verbose_name': 'Медиа',
                'verbose_name_plural': 'Медиа',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer_text', models.TextField(blank=True, verbose_name='Текст ответа')),
                ('message_id', models.IntegerField(blank=True, null=True, verbose_name='ID сообщения с ответом в Telegram')),
                ('answer_media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answer_for', to='worklog.media', verbose_name='Медиа-ответ')),
                ('answered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='worklog.worker', verbose_name='Кто ответил')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='worklog.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Supergroup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('telegram_group_id', models.BigIntegerField(unique=True, verbose_name='ID супергруппы в Telegram')),
                ('invite_link', models.URLField(blank=True, verbose_name='Ссылка-приглашение для монтажников')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supergroups', to='accounting.counterparty', verbose_name='Исполнитель')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_supergroups', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supergroups', to='objects.object', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Супергруппа',
                'verbose_name_plural': 'Супергруппы',
                'unique_together': {('object', 'contractor')},
            },
        ),
        migrations.CreateModel(
            name='ShiftRegistration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Время регистрации')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='GPS широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='GPS долгота')),
                ('geo_valid', models.BooleanField(default=False, verbose_name='В геозоне объекта')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_workers', to='worklog.worker', verbose_name='Кто зарегистрировал')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='worklog.shift', verbose_name='Смена')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_registrations', to='worklog.worker', verbose_name='Монтажник')),
            ],
            options={
                'verbose_name': 'Регистрация на смену',
                'verbose_name_plural': 'Регистрации на смены',
                'unique_together': {('shift', 'worker')},
            },
        ),
    ]
