# Generated by Django 4.2.7 on 2026-02-09 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid
import worklog.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_legalentity_director_legalentity_director_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('worklog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteToken',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(default=worklog.models._generate_invite_code, max_length=32, unique=True, verbose_name='Код приглашения')),
                ('role', models.CharField(choices=[('worker', 'Монтажник'), ('brigadier', 'Бригадир')], default='worker', max_length=16, verbose_name='Роль приглашённого')),
                ('expires_at', models.DateTimeField(default=worklog.models._default_invite_expires, verbose_name='Действителен до')),
                ('used', models.BooleanField(default=False, verbose_name='Использован')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Когда использован')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_tokens', to='accounting.counterparty', verbose_name='Исполнитель')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invites', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_invite', to='worklog.worker', verbose_name='Кто использовал')),
            ],
            options={
                'verbose_name': 'Приглашение',
                'verbose_name_plural': 'Приглашения',
                'ordering': ['-created_at'],
            },
        ),
    ]
