# Generated by Django 4.2.7 on 2026-02-10 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0012_alter_act_options_act_contracts_a_contrac_6d81aa_idx_and_more'),
        ('worklog', '0002_add_invite_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='contracts.contract', verbose_name='Договор'),
        ),
    ]
