# Generated by Django 4.2.7 on 2026-02-11 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import personnel.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0007_alter_counterparty_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, verbose_name='Пол')),
                ('current_position', models.CharField(blank=True, max_length=255, verbose_name='Текущая должность')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Дата приёма на работу')),
                ('salary_full', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Оклад полный (руб.)')),
                ('salary_official', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Оклад официальный (руб.)')),
                ('responsibilities', models.TextField(blank=True, verbose_name='Обязанности')),
                ('bank_name', models.CharField(blank=True, max_length=255, verbose_name='Наименование банка')),
                ('bank_bik', models.CharField(blank=True, max_length=9, verbose_name='БИК')),
                ('bank_corr_account', models.CharField(blank=True, max_length=20, verbose_name='Корр. счёт')),
                ('bank_account', models.CharField(blank=True, max_length=20, verbose_name='Расчётный счёт')),
                ('bank_card_number', models.CharField(blank=True, max_length=19, verbose_name='Номер карты')),
                ('erp_permissions', models.JSONField(blank=True, default=personnel.models.default_erp_permissions, help_text='{"objects":"read","payments":"edit",...}', verbose_name='Права доступа ERP')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('counterparty', models.OneToOneField(blank=True, help_text='Контрагент для выплаты зарплаты', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_record', to='accounting.counterparty', verbose_name='Контрагент')),
                ('supervisors', models.ManyToManyField(blank=True, help_text='Непосредственные руководители (матричная структура)', related_name='subordinates', to='personnel.employee', verbose_name='Руководители')),
                ('user', models.OneToOneField(blank=True, help_text='Опционально: привязка к учётной записи для входа в систему', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь ERP')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='SalaryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('salary_full', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Оклад полный (руб.)')),
                ('salary_official', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Оклад официальный (руб.)')),
                ('effective_date', models.DateField(verbose_name='Дата вступления в силу')),
                ('reason', models.CharField(blank=True, help_text='Повышение, индексация, перевод и т.д.', max_length=255, verbose_name='Причина изменения')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_history', to='personnel.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Запись об окладе',
                'verbose_name_plural': 'История окладов',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='PositionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('position_title', models.CharField(max_length=255, verbose_name='Наименование должности')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, help_text='Пусто = текущая должность', null=True, verbose_name='Дата окончания')),
                ('is_current', models.BooleanField(default=True, verbose_name='Текущая')),
                ('order_number', models.CharField(blank=True, max_length=100, verbose_name='Номер приказа')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='personnel.employee', verbose_name='Сотрудник')),
                ('legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_records', to='accounting.legalentity', verbose_name='Юридическое лицо')),
            ],
            options={
                'verbose_name': 'Запись о должности',
                'verbose_name_plural': 'Записи о должностях',
                'ordering': ['-start_date'],
            },
        ),
    ]
