# Generated by Django 4.2.7 on 2026-02-14 22:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sha256', models.CharField(max_length=64, unique=True)),
                ('size_bytes', models.BigIntegerField()),
                ('mime_type', models.CharField(blank=True, max_length=255)),
                ('original_filename', models.CharField(blank=True, max_length=512)),
                ('bucket', models.CharField(max_length=255)),
                ('object_key', models.CharField(max_length=1024)),
                ('status', models.CharField(choices=[('uploading', 'Загружается'), ('ready', 'Готово')], default='uploading', max_length=20)),
                ('created_by_user_id', models.IntegerField(blank=True, null=True)),
                ('created_by_username', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Файл (registry)',
                'verbose_name_plural': 'Файлы (registry)',
                'indexes': [models.Index(fields=['status'], name='kanban_file_status_612be8_idx'), models.Index(fields=['created_by_user_id'], name='kanban_file_created_77cdac_idx')],
            },
        ),
    ]
