"""
Django settings for finans_assistant project.

Generated by 'django-admin startproject' using Django 4.2.24.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Загрузка переменных из .env файла (если существует)
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-^)16g74+k9b!4mfbp3r6ih4h$1===oca==rjvsijbtr4uq&-=^')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '72.56.83.95',  # Production server IP
    '.ngrok-free.app',
    'finance.ngrok.app',  # Development ngrok domain
    '.ngrok.io',
]

# Add production domain from environment variable
PRODUCTION_DOMAIN = os.environ.get('PRODUCTION_DOMAIN', '')
if PRODUCTION_DOMAIN:
    ALLOWED_HOSTS.extend([PRODUCTION_DOMAIN, f'www.{PRODUCTION_DOMAIN}'])

CSRF_TRUSTED_ORIGINS = [
    'https://finance.ngrok.app',
    'https://*.figmaiframepreview.figma.site',
    'https://*.figma.site',
]

# Add production domain to CSRF trusted origins
if PRODUCTION_DOMAIN:
    CSRF_TRUSTED_ORIGINS.extend([
        f'https://{PRODUCTION_DOMAIN}',
        f'https://www.{PRODUCTION_DOMAIN}',
    ])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'drf_spectacular',
    'django_filters',
    'corsheaders',
    'core',
    'objects',
    'contracts',
    'payments',
    'catalog',
    'llm_services',
    'accounting',
    'communications',
    'pricelists',
    'estimates',
    'proposals',
    'worklog',
    'fns',
    'personnel',
    'banking',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Должен быть ПЕРВЫМ!
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Раздача static файлов (production)
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'finans_assistant.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'finans_assistant.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'finans_assistant'),
        'USER': os.environ.get('DB_USER', 'postgres'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'postgres'),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (загружаемые пользователями)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# CORS settings
# ⚠️ Зависит от DEBUG — в production автоматически отключается CORS_ALLOW_ALL_ORIGINS
if DEBUG:
    # Для разработки - разрешить все источники (только для тестирования фронтенда в Figma)
    CORS_ALLOW_ALL_ORIGINS = True
else:
    # Production — только конкретные домены
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = [
        "https://your-production-domain.com",  # TODO: заменить на реальный домен
        # Добавьте другие production домены
    ]
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
CORS_PREFLIGHT_MAX_AGE = 86400

# Примечание: CORS_ALLOW_PRIVATE_NETWORK не поддерживается django-cors-headers
# Для работы с Figma во время разработки используйте ngrok туннель (см. start_ngrok.sh)
# После развёртывания на production ngrok больше не нужен

# Дополнительные заголовки для работы с Figma и ngrok
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'ngrok-skip-browser-warning',  # Заголовок ngrok для пропуска предупреждения браузера
    'x-ngrok-skip-browser-warning',  # Альтернативный вариант
]

# Явная поддержка Figma доменов через regex (на случай если CORS_ALLOW_ALL_ORIGINS не сработает)
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://.*\.figmaiframepreview\.figma\.site$",
    r"^https://.*\.figma\.site$",
    r"^https://.*\.ngrok-free\.app$",
    r"^https://.*\.ngrok\.io$",
]

# Для production используйте конкретные домены:
# CORS_ALLOW_ALL_ORIGINS = False
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:3000",
#     "http://127.0.0.1:3000",
#     "https://figma.site",
# ]

# JWT Settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

# drf-spectacular settings
SPECTACULAR_SETTINGS = {
    'TITLE': 'Финансовый ассистент API',
    'DESCRIPTION': 'API для управления финансовыми данными строительной компании',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_PATH_PREFIX': '/api/v1/',
    'AUTHENTICATION_WHITELIST': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'SERVERS': [
        {'url': 'http://localhost:8000', 'description': 'Локальный сервер разработки'},
    ],
    'TAGS': [
        {'name': 'Аутентификация', 'description': 'Регистрация, логин, управление токенами'},
        {'name': 'Пользователи', 'description': 'Управление пользователями'},
        {'name': 'Объекты', 'description': 'Управление строительными объектами'},
        {'name': 'Договоры', 'description': 'Управление договорами'},
        {'name': 'Платежи', 'description': 'Управление фактическими платежами'},
        {'name': 'Плановые платежи', 'description': 'Управление реестром плановых платежей'},
        {'name': 'Импорты', 'description': 'Журнал импорта данных'},
    ],
}

# Настройки нумерации коммерческих предложений
COMMERCIAL_PROPOSAL_START_NUMBER = 210  # Начальный порядковый номер для ТКП (можно изменить)

# =============================================================================
# Celery Configuration
# =============================================================================
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 300  # 5 минут

# =============================================================================
# MinIO / S3 Configuration (для медиа сервиса фиксации работ)
# =============================================================================
WORKLOG_S3_ENDPOINT_URL = os.environ.get('WORKLOG_S3_ENDPOINT_URL', 'http://localhost:9000')
WORKLOG_S3_PUBLIC_URL = os.environ.get('WORKLOG_S3_PUBLIC_URL', WORKLOG_S3_ENDPOINT_URL)
WORKLOG_S3_ACCESS_KEY = os.environ.get('WORKLOG_S3_ACCESS_KEY', 'minioadmin')
WORKLOG_S3_SECRET_KEY = os.environ.get('WORKLOG_S3_SECRET_KEY', 'minioadmin')
WORKLOG_S3_BUCKET_NAME = os.environ.get('WORKLOG_S3_BUCKET_NAME', 'worklog-media')
WORKLOG_S3_REGION = 'us-east-1'

# =============================================================================
# Telegram Bot Configuration
# =============================================================================
TELEGRAM_BOT_TOKEN = os.environ.get('TELEGRAM_BOT_TOKEN', '')

# =============================================================================
# ElevenLabs Configuration (транскрибация голосовых — Scribe v2)
# =============================================================================
ELEVENLABS_API_KEY = os.environ.get('ELEVENLABS_API_KEY', '')

# =============================================================================
# API-FNS Configuration (проверка контрагентов)
# =============================================================================
FNS_API_KEY = os.environ.get('FNS_API_KEY', '')

# =============================================================================
# Banking Encryption Key (шифрование банковских секретов)
# =============================================================================
BANK_ENCRYPTION_KEY = os.environ.get('BANK_ENCRYPTION_KEY', '')

# =============================================================================
# Sentry Configuration (мониторинг ошибок)
# =============================================================================
SENTRY_DSN = os.environ.get('SENTRY_DSN', '')

if SENTRY_DSN:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration
    from sentry_sdk.integrations.celery import CeleryIntegration
    from sentry_sdk.integrations.redis import RedisIntegration

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[
            DjangoIntegration(),
            CeleryIntegration(),
            RedisIntegration(),
        ],
        traces_sample_rate=0.2,  # 20% трассировок для мониторинга производительности
        send_default_pii=False,
        environment=os.environ.get('SENTRY_ENVIRONMENT', 'development'),
    )

# =============================================================================
# Logging Configuration
# =============================================================================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {module}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'worklog.log'),
            'maxBytes': 10 * 1024 * 1024,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'worklog': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'celery': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}

# =========================================================================
# PRODUCTION SECURITY SETTINGS
# =========================================================================

if not DEBUG:
    # Secure cookies
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    # HTTPS redirect (if behind reverse proxy like Cloudflare/nginx)
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    
    # HSTS (HTTP Strict Transport Security)
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Additional security headers
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'DENY'
    
    # Logging configuration for production
    LOGGING['loggers']['django']['level'] = 'ERROR'
    LOGGING['loggers']['worklog']['handlers'].append('file')
    LOGGING['loggers']['celery']['handlers'].append('file')

