# Generated by Django 4.2.7 on 2025-11-22 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('import_batch_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Идентификатор импорта')),
                ('file_name', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('file_type', models.CharField(choices=[('payments_actual', 'Фактические платежи'), ('payments_plan', 'Плановые платежи'), ('incomes', 'Поступления'), ('balance', 'Задолженность')], max_length=50, verbose_name='Тип файла')),
                ('file_size', models.PositiveIntegerField(verbose_name='Размер файла (байт)')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='Путь к файлу')),
                ('status', models.CharField(choices=[('pending', 'В обработке'), ('success', 'Успешно'), ('failed', 'Ошибка'), ('partial', 'Частично успешно')], default='pending', max_length=20, verbose_name='Статус обработки')),
                ('records_count', models.PositiveIntegerField(default=0, verbose_name='Количество записей')),
                ('success_count', models.PositiveIntegerField(default=0, verbose_name='Успешно обработано')),
                ('error_count', models.PositiveIntegerField(default=0, verbose_name='Ошибок')),
                ('errors', models.TextField(blank=True, verbose_name='Описание ошибок')),
                ('import_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата импорта')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Журнал импорта',
                'verbose_name_plural': 'Журнал импортов',
                'ordering': ['-import_date', '-created_at'],
                'indexes': [models.Index(fields=['import_batch_id'], name='imports_imp_import__0708e9_idx'), models.Index(fields=['status', 'import_date'], name='imports_imp_status_23c729_idx'), models.Index(fields=['file_type', 'import_date'], name='imports_imp_file_ty_2f5372_idx'), models.Index(fields=['user', 'import_date'], name='imports_imp_user_id_dec9b5_idx')],
            },
        ),
    ]
