# Generated by Django 4.2.7 on 2025-12-13 14:18

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0003_add_vendor_subtype_to_counterparty'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('number', models.CharField(max_length=50, verbose_name='Номер прайс-листа')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('date', models.DateField(verbose_name='Дата прайс-листа')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Действующий'), ('archived', 'Архивный')], default='draft', max_length=20, verbose_name='Статус')),
                ('grade_1_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Ставка 1 разряда')),
                ('grade_2_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Ставка 2 разряда')),
                ('grade_3_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Ставка 3 разряда')),
                ('grade_4_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Ставка 4 разряда')),
                ('grade_5_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Ставка 5 разряда')),
                ('version_number', models.PositiveIntegerField(default=1, verbose_name='Номер версии')),
                ('parent_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_versions', to='pricelists.pricelist', verbose_name='Предыдущая версия')),
            ],
            options={
                'verbose_name': 'Прайс-лист',
                'verbose_name_plural': 'Прайс-листы',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkerGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('grade', models.PositiveSmallIntegerField(help_text='Значение от 1 до 5', unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Номер разряда')),
                ('name', models.CharField(help_text='Например: Монтажник 1 разряда', max_length=100, verbose_name='Название')),
                ('default_hourly_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Базовая ставка руб/час')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Разряд рабочего',
                'verbose_name_plural': 'Разряды рабочих',
                'ordering': ['grade'],
            },
        ),
        migrations.CreateModel(
            name='WorkSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('code', models.CharField(help_text='Например: VENT, COND', max_length=50, unique=True, verbose_name='Код раздела')),
                ('name', models.CharField(help_text='Например: Вентиляция, Кондиционирование', max_length=200, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='pricelists.worksection', verbose_name='Родительский раздел')),
            ],
            options={
                'verbose_name': 'Раздел работ',
                'verbose_name_plural': 'Разделы работ',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('article', models.CharField(help_text='Например: V-001', max_length=50, unique=True, verbose_name='Артикул')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование работы')),
                ('unit', models.CharField(choices=[('шт', 'Штука'), ('м.п.', 'Метр погонный'), ('м²', 'Метр квадратный'), ('м³', 'Метр кубический'), ('компл', 'Комплект'), ('ед', 'Единица'), ('ч', 'Час'), ('кг', 'Килограмм'), ('т', 'Тонна')], max_length=20, verbose_name='Единица измерения')),
                ('hours', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Кол-во часов на единицу')),
                ('composition', models.TextField(blank=True, help_text='Описание состава работы', verbose_name='Состав работы')),
                ('coefficient', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Коэффициент сложности')),
                ('version_number', models.PositiveIntegerField(default=1, verbose_name='Номер версии')),
                ('is_current', models.BooleanField(default=True, verbose_name='Актуальная версия')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_items', to='pricelists.workergrade', verbose_name='Требуемый разряд')),
                ('parent_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_versions', to='pricelists.workitem', verbose_name='Предыдущая версия')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_items', to='pricelists.worksection', verbose_name='Раздел работ')),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работы',
                'ordering': ['section', 'article'],
            },
        ),
        migrations.CreateModel(
            name='WorkerGradeSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('description', models.TextField(verbose_name='Описание навыков')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='pricelists.workergrade', verbose_name='Разряд')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_skills', to='pricelists.worksection', verbose_name='Раздел работ')),
            ],
            options={
                'verbose_name': 'Навыки разряда',
                'verbose_name_plural': 'Навыки разрядов',
                'unique_together': {('grade', 'section')},
            },
        ),
        migrations.CreateModel(
            name='PriceListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_override', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Переопределённые часы')),
                ('coefficient_override', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Переопределённый коэффициент')),
                ('is_included', models.BooleanField(default=True, verbose_name='Включена в прайс')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pricelists.pricelist', verbose_name='Прайс-лист')),
                ('work_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_list_items', to='pricelists.workitem', verbose_name='Работа')),
            ],
            options={
                'verbose_name': 'Позиция прайс-листа',
                'verbose_name_plural': 'Позиции прайс-листа',
                'ordering': ['work_item__section', 'work_item__article'],
                'unique_together': {('price_list', 'work_item')},
            },
        ),
        migrations.CreateModel(
            name='PriceListAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreed_date', models.DateField(verbose_name='Дата согласования')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_list_agreements', to='accounting.counterparty', verbose_name='Исполнитель')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='pricelists.pricelist', verbose_name='Прайс-лист')),
            ],
            options={
                'verbose_name': 'Согласование прайс-листа',
                'verbose_name_plural': 'Согласования прайс-листов',
                'unique_together': {('price_list', 'counterparty')},
            },
        ),
    ]
