# Generated by Django 4.2.7 on 2025-12-13 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricelists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricelistagreement',
            options={'ordering': ['-agreed_date', '-created_at'], 'verbose_name': 'Согласование прайс-листа', 'verbose_name_plural': 'Согласования прайс-листов'},
        ),
    ]
