# Generated by Django 4.2.7 on 2025-12-13 18:28

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelists', '0002_alter_pricelistagreement_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelistitem',
            name='grade_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Дробный разряд для работы (например, 3.65). Если не указан, используется разряд из работы.', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1')), django.core.validators.MaxValueValidator(Decimal('5'))], verbose_name='Переопределённый разряд'),
        ),
    ]
