# Generated by Django 4.2.7 on 2025-12-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelists', '0003_pricelistitem_grade_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='comment',
            field=models.TextField(blank=True, help_text='Дополнительные комментарии к работе', verbose_name='Комментарий'),
        ),
    ]
