# Generated by Django 4.2.7 on 2025-12-14 09:01

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelists', '0004_workitem_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workitem',
            name='hours',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), help_text='Если не указано, используется 0', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Кол-во часов на единицу'),
        ),
    ]
