# Generated by Django 4.2.7 on 2025-12-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelists', '0005_alter_workitem_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workitem',
            name='unit',
            field=models.CharField(choices=[('шт', 'Штука'), ('м.п.', 'Метр погонный'), ('м²', 'Метр квадратный'), ('м³', 'Метр кубический'), ('компл', 'Комплект'), ('ед', 'Единица'), ('ч', 'Час'), ('кг', 'Килограмм'), ('т', 'Тонна'), ('точка', 'Точка')], max_length=20, verbose_name='Единица измерения'),
        ),
    ]
