# Generated by Django 4.2.7 on 2025-12-14 12:25

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricelists', '0006_alter_workitem_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='required_grade',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Точный требуемый разряд работы (может быть дробным, например 3.65)', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1')), django.core.validators.MaxValueValidator(Decimal('5'))], verbose_name='Требуемый разряд'),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='grade',
            field=models.ForeignKey(help_text='Ближайший целый разряд вниз для базовой ставки (для дробных разрядов)', on_delete=django.db.models.deletion.PROTECT, related_name='work_items', to='pricelists.workergrade', verbose_name='Базовый разряд'),
        ),
    ]
