# Generated by Django 4.2.7 on 2025-11-22 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('planned_date', models.DateField(verbose_name='Плановая дата')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сумма')),
                ('status', models.CharField(choices=[('planned', 'Планируется'), ('approved', 'Утверждено'), ('cancelled', 'Отменено')], default='planned', max_length=20, verbose_name='Статус')),
                ('initiator', models.CharField(blank=True, max_length=255, verbose_name='Инициатор платежа')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_payments', to='contracts.contract', verbose_name='Договор')),
            ],
            options={
                'verbose_name': 'Плановый платёж',
                'verbose_name_plural': 'Реестр плановых платежей',
                'ordering': ['planned_date', '-created_at'],
                'indexes': [models.Index(fields=['planned_date'], name='payments_pa_planned_c117ba_idx'), models.Index(fields=['status', 'planned_date'], name='payments_pa_status_bd445a_idx'), models.Index(fields=['contract', 'planned_date'], name='payments_pa_contrac_1c66c8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('payment_type', models.CharField(choices=[('expense', 'Расход'), ('income', 'Поступление')], max_length=20, verbose_name='Тип платежа')),
                ('payment_date', models.DateField(verbose_name='Дата платежа')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сумма')),
                ('company_account', models.CharField(blank=True, max_length=100, verbose_name='Счёт компании')),
                ('description', models.TextField(blank=True, verbose_name='Назначение платежа')),
                ('document_link', models.CharField(blank=True, max_length=500, verbose_name='Ссылка на документ')),
                ('import_batch_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Идентификатор импорта')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='contracts.contract', verbose_name='Договор')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-payment_date', '-created_at'],
                'indexes': [models.Index(fields=['payment_date'], name='payments_pa_payment_1d6e55_idx'), models.Index(fields=['payment_type', 'payment_date'], name='payments_pa_payment_93fd1e_idx'), models.Index(fields=['contract', 'payment_date'], name='payments_pa_contrac_50b69a_idx')],
            },
        ),
    ]
