# Generated by Django 4.2.7 on 2025-11-23 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
                ('code', models.CharField(help_text='Уникальный код для программного использования (например: salary, rent)', max_length=100, unique=True, verbose_name='Код категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, help_text='Неактивные категории не отображаются в списках', verbose_name='Активна')),
                ('requires_contract', models.BooleanField(default=False, help_text='Если отмечено, платежи этой категории должны быть привязаны к договору', verbose_name='Требует договор')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Чем меньше число, тем выше в списке', verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Категория расходов/доходов',
                'verbose_name_plural': 'Категории расходов/доходов',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='payment',
            name='contract',
            field=models.ForeignKey(blank=True, help_text='Оставьте пустым для операционных расходов/доходов', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='contracts.contract', verbose_name='Договор'),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Оставьте пустым для категории верхнего уровня', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='payments.expensecategory', verbose_name='Родительская категория'),
        ),
        migrations.AddField(
            model_name='payment',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Категория платежа (например: Зарплата, Аренда)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.expensecategory', verbose_name='Категория'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['category', 'payment_date'], name='payments_pa_categor_b2e212_idx'),
        ),
        migrations.AddIndex(
            model_name='expensecategory',
            index=models.Index(fields=['code'], name='payments_ex_code_881785_idx'),
        ),
        migrations.AddIndex(
            model_name='expensecategory',
            index=models.Index(fields=['parent', 'is_active'], name='payments_ex_parent__3ae757_idx'),
        ),
    ]
