# Generated by Django 4.2.7 on 2025-11-26 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import payments.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_populate_tax_systems'),
        ('contracts', '0002_act_contract_contract_type_contract_counterparty_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0004_make_category_required'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentregistry',
            options={'ordering': ['planned_date', '-created_at'], 'verbose_name': 'Заявка на платёж', 'verbose_name_plural': 'Реестр платежей'},
        ),
        migrations.AddField(
            model_name='payment',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='accounting.account', verbose_name='Счёт компании'),
        ),
        migrations.AddField(
            model_name='payment',
            name='amount_gross',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Сумма с НДС'),
        ),
        migrations.AddField(
            model_name='payment',
            name='amount_net',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Сумма без НДС'),
        ),
        migrations.AddField(
            model_name='payment',
            name='legal_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='accounting.legalentity', verbose_name='Юридическое лицо'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_registry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_fact', to='payments.paymentregistry', verbose_name='Связанная заявка'),
        ),
        migrations.AddField(
            model_name='payment',
            name='scan_file',
            field=models.FileField(blank=True, null=True, upload_to=payments.models.payment_scan_path, verbose_name='Скан платежки'),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'В обработке'), ('paid', 'Проведен'), ('cancelled', 'Отменен')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='payment',
            name='vat_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Сумма НДС'),
        ),
        migrations.AddField(
            model_name='paymentregistry',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_requests', to='accounting.account', verbose_name='Счёт списания'),
        ),
        migrations.AddField(
            model_name='paymentregistry',
            name='act',
            field=models.ForeignKey(blank=True, help_text='Если заполнено - постоплата по акту. Иначе - аванс.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_requests', to='contracts.act', verbose_name='Основание (Акт)'),
        ),
        migrations.AddField(
            model_name='paymentregistry',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата одобрения'),
        ),
        migrations.AddField(
            model_name='paymentregistry',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payments', to=settings.AUTH_USER_MODEL, verbose_name='Кем одобрено'),
        ),
        migrations.AddField(
            model_name='paymentregistry',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_requests', to='payments.expensecategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='paymentregistry',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to=payments.models.invoice_scan_path, verbose_name='Скан счета на оплату'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='company_account',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Счёт компании (Legacy)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='contract',
            field=models.ForeignKey(blank=True, help_text='Оставьте пустым для операционных расходов/доходов', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='contracts.contract', verbose_name='Договор'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='document_link',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка на документ (Legacy)'),
        ),
        migrations.AlterField(
            model_name='paymentregistry',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planned_payments', to='contracts.contract', verbose_name='Договор'),
        ),
        migrations.AlterField(
            model_name='paymentregistry',
            name='status',
            field=models.CharField(choices=[('planned', 'Планируется'), ('approved', 'Утверждено'), ('paid', 'Оплачено'), ('cancelled', 'Отменено')], default='planned', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx'),
        ),
    ]
