# Generated by Django 4.2.7 on 2025-11-26 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_paymentregistry_options_payment_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='company_account',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='document_link',
        ),
    ]
