# Generated by Django 4.2.7 on 2025-12-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_remove_payment_company_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='internal_transfer_group',
            field=models.CharField(blank=True, db_index=True, help_text='Группа для связывания внутренних переводов (если платеж является частью внутреннего перевода)', max_length=100, null=True, verbose_name='Группа внутреннего перевода'),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_internal_transfer',
            field=models.BooleanField(default=False, help_text='Флаг внутреннего перевода между счетами', verbose_name='Внутренний перевод'),
        ),
    ]
