# Generated by Django 4.2.7 on 2026-01-04 11:49

from django.db import migrations, models
import django.db.models.deletion
import payments.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('payments', '0008_alter_payment_scan_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='scan_file',
            field=models.FileField(help_text='PDF для расходов, любой формат для доходов', upload_to=payments.models.payment_scan_path, verbose_name='Документ (счёт/акт)'),
        ),
        migrations.CreateModel(
            name='PaymentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('raw_name', models.CharField(max_length=500, verbose_name='Исходное название из счёта')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Количество')),
                ('unit', models.CharField(max_length=20, verbose_name='Единица измерения')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Цена за единицу')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сумма')),
                ('vat_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='НДС по позиции')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payments.payment', verbose_name='Платёж')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_items', to='catalog.product', verbose_name='Товар из каталога')),
            ],
            options={
                'verbose_name': 'Позиция платежа',
                'verbose_name_plural': 'Позиции платежей',
                'ordering': ['id'],
            },
        ),
    ]
