# Generated by Django 4.2.7 on 2026-02-14 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import payments.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('objects', '0006_add_registration_window_minutes'),
        ('contracts', '0012_alter_act_options_act_contracts_a_contrac_6d81aa_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('banking', '0002_rename_banking_ban_status_idx_banking_ban_status_19ad6c_idx_and_more'),
        ('llm_services', '0003_add_indexes'),
        ('accounting', '0009_accountbalance_source'),
        ('payments', '0009_alter_payment_scan_file_paymentitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сумма')),
                ('payment_date', models.DateField(verbose_name='Дата поступления')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('scan_file', models.FileField(blank=True, null=True, upload_to='income/%Y/%m/', verbose_name='Скан документа')),
            ],
            options={
                'verbose_name': 'Поступление (доход)',
                'verbose_name_plural': 'Поступления (доходы)',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('source', models.CharField(choices=[('bitrix', 'Из Битрикс24'), ('manual', 'Ручной ввод'), ('recurring', 'Периодический')], default='manual', max_length=20, verbose_name='Источник')),
                ('invoice_file', models.FileField(blank=True, null=True, upload_to=payments.models.invoice_file_path, verbose_name='PDF счёта')),
                ('invoice_number', models.CharField(blank=True, max_length=100, verbose_name='Номер счёта')),
                ('invoice_date', models.DateField(blank=True, null=True, verbose_name='Дата счёта')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Срок оплаты')),
                ('amount_gross', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Сумма с НДС')),
                ('amount_net', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Сумма без НДС')),
                ('vat_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Сумма НДС')),
                ('status', models.CharField(choices=[('recognition', 'Распознаётся'), ('review', 'На проверке'), ('in_registry', 'В реестре'), ('approved', 'Одобрен'), ('sending', 'Отправляется в банк'), ('paid', 'Оплачен'), ('cancelled', 'Отменён')], default='recognition', max_length=20, verbose_name='Статус')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата одобрения')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты')),
                ('description', models.TextField(blank=True, verbose_name='Описание / назначение платежа')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий директора')),
                ('recognition_confidence', models.FloatField(blank=True, null=True, verbose_name='Уверенность распознавания')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='accounting.account', verbose_name='Счёт списания')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_invoices', to=settings.AUTH_USER_MODEL, verbose_name='Одобрено (директор)')),
                ('bank_payment_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='banking.bankpaymentorder', verbose_name='Платёжное поручение')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='payments.expensecategory', verbose_name='Категория')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='contracts.contract', verbose_name='Договор')),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='accounting.counterparty', verbose_name='Контрагент (поставщик)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL, verbose_name='Создано')),
                ('legal_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='accounting.legalentity', verbose_name='Юридическое лицо')),
                ('object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='objects.object', verbose_name='Объект')),
                ('parsed_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='llm_services.parseddocument', verbose_name='Распознанный документ (LLM)')),
            ],
            options={
                'verbose_name': 'Счёт на оплату',
                'verbose_name_plural': 'Счета на оплату',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='payment',
            name='internal_transfer_group',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Группа внутреннего перевода'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='is_internal_transfer',
            field=models.BooleanField(default=False, verbose_name='Внутренний перевод'),
        ),
        migrations.AlterField(
            model_name='paymentregistry',
            name='act',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_requests', to='contracts.act', verbose_name='Основание (Акт)'),
        ),
        migrations.AlterField(
            model_name='paymentregistry',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to='invoices/%Y/%m/', verbose_name='Скан счета на оплату'),
        ),
        migrations.CreateModel(
            name='RecurringPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(help_text='Например: "Аренда офиса", "Интернет", "Лицензия 1С"', max_length=255, verbose_name='Название')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Базовая сумма')),
                ('amount_is_fixed', models.BooleanField(default=True, help_text='Если нет — оператор вводит сумму для каждого счёта', verbose_name='Фиксированная сумма')),
                ('frequency', models.CharField(choices=[('monthly', 'Ежемесячно'), ('quarterly', 'Ежеквартально'), ('yearly', 'Ежегодно')], default='monthly', max_length=20, verbose_name='Периодичность')),
                ('day_of_month', models.PositiveIntegerField(default=1, help_text='День месяца для генерации (1-28)', verbose_name='День месяца')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, help_text='Пусто — бессрочный', null=True, verbose_name='Дата окончания')),
                ('next_generation_date', models.DateField(verbose_name='Следующая дата генерации')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_payments', to='accounting.account', verbose_name='Счёт списания')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_payments', to='payments.expensecategory', verbose_name='Категория')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_payments', to='contracts.contract', verbose_name='Договор')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_payments', to='accounting.counterparty', verbose_name='Контрагент')),
                ('legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_payments', to='accounting.legalentity', verbose_name='Юридическое лицо')),
                ('object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_payments', to='objects.object', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Периодический платёж',
                'verbose_name_plural': 'Периодические платежи',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('raw_name', models.CharField(max_length=500, verbose_name='Исходное название из счёта')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Количество')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='Единица измерения')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Цена за единицу')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сумма')),
                ('vat_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='НДС по позиции')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payments.invoice', verbose_name='Счёт')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='catalog.product', verbose_name='Товар из каталога')),
            ],
            options={
                'verbose_name': 'Позиция счёта',
                'verbose_name_plural': 'Позиции счетов',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('event_type', models.CharField(choices=[('created', 'Создан'), ('recognized', 'Распознан (LLM)'), ('reviewed', 'Проверен оператором'), ('sent_to_registry', 'Отправлен в реестр'), ('approved', 'Одобрен'), ('rejected', 'Отклонён'), ('rescheduled', 'Перенесена дата'), ('sent_to_bank', 'Отправлен в банк'), ('paid', 'Оплачен'), ('cancelled', 'Отменён'), ('comment', 'Комментарий')], max_length=30, verbose_name='Тип события')),
                ('old_value', models.JSONField(blank=True, null=True, verbose_name='Предыдущее значение')),
                ('new_value', models.JSONField(blank=True, null=True, verbose_name='Новое значение')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='payments.invoice', verbose_name='Счёт')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_events', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Событие счёта',
                'verbose_name_plural': 'События счетов',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='recurring_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='payments.recurringpayment', verbose_name='Периодический платёж'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_invoices', to=settings.AUTH_USER_MODEL, verbose_name='Проверено (оператор)'),
        ),
    ]
