# Generated by Django 4.2.7 on 2026-02-14 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_incomerecord_invoice_and_more'),
        ('supply', '0001_initial'),
        ('accounting', '0009_accountbalance_source'),
        ('contracts', '0012_alter_act_options_act_contracts_a_contrac_6d81aa_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='supply_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='supply.supplyrequest', verbose_name='Запрос на снабжение'),
        ),
        migrations.AddField(
            model_name='incomerecord',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='income_records', to='accounting.account', verbose_name='Счёт зачисления'),
        ),
        migrations.AddField(
            model_name='incomerecord',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='income_records', to='payments.expensecategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='incomerecord',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_records', to='contracts.contract', verbose_name='Договор'),
        ),
        migrations.AddField(
            model_name='incomerecord',
            name='counterparty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_records', to='accounting.counterparty', verbose_name='Контрагент'),
        ),
        migrations.AddField(
            model_name='incomerecord',
            name='legal_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='income_records', to='accounting.legalentity', verbose_name='Юридическое лицо'),
        ),
        migrations.AddIndex(
            model_name='recurringpayment',
            index=models.Index(fields=['is_active', 'next_generation_date'], name='payments_re_is_acti_1861cf_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='payments_in_status_45b876_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['source'], name='payments_in_source_99c41d_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_date'], name='payments_in_due_dat_9c830a_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', 'due_date'], name='payments_in_status_68daea_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['object', 'status'], name='payments_in_object__fb45fc_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['counterparty', 'status'], name='payments_in_counter_9487cb_idx'),
        ),
        migrations.AddIndex(
            model_name='incomerecord',
            index=models.Index(fields=['payment_date'], name='payments_in_payment_c1b339_idx'),
        ),
        migrations.AddIndex(
            model_name='incomerecord',
            index=models.Index(fields=['account', 'payment_date'], name='payments_in_account_3de460_idx'),
        ),
    ]
