# Generated by Django 4.2.7 on 2026-02-18 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_banktransaction_invoice_and_more'),
        ('contracts', '0012_alter_act_options_act_contracts_a_contrac_6d81aa_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('objects', '0007_object_photo'),
        ('payments', '0011_invoice_supply_request_incomerecord_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('date', models.DateField(verbose_name='Дата проводки')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сумма')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_auto', models.BooleanField(default=False, help_text='Создана автоматически при оплате/поступлении', verbose_name='Автоматическая проводка')),
            ],
            options={
                'verbose_name': 'Проводка',
                'verbose_name_plural': 'Проводки',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Внутренний план счетов', 'verbose_name_plural': 'Внутренний план счетов'},
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='account_type',
            field=models.CharField(choices=[('expense', 'Расходная категория'), ('income', 'Доходная категория'), ('system', 'Системный счёт'), ('object', 'Счёт объекта'), ('contract', 'Субсчёт договора')], default='expense', max_length=20, verbose_name='Тип счёта'),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='contract',
            field=models.OneToOneField(blank=True, help_text='Заполняется автоматически для типа CONTRACT', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_account', to='contracts.contract', verbose_name='Договор'),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='object',
            field=models.OneToOneField(blank=True, help_text='Заполняется автоматически для типа OBJECT', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_account', to='objects.object', verbose_name='Объект'),
        ),
        migrations.AddField(
            model_name='incomerecord',
            name='act',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_records', to='contracts.act', verbose_name='Акт'),
        ),
        migrations.AddField(
            model_name='incomerecord',
            name='bank_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_records', to='banking.banktransaction', verbose_name='Банковская транзакция'),
        ),
        migrations.AddField(
            model_name='incomerecord',
            name='income_type',
            field=models.CharField(choices=[('customer_act', 'Оплата по Акту от Заказчика'), ('advance', 'Авансовый платёж'), ('warranty_return', 'Возврат гарантийных удержаний'), ('supplier_return', 'Возврат от Поставщика'), ('bank_interest', 'Проценты банка'), ('other', 'Прочие поступления')], default='other', max_length=20, verbose_name='Тип поступления'),
        ),
        migrations.AddField(
            model_name='incomerecord',
            name='is_cash',
            field=models.BooleanField(default=False, verbose_name='Наличный платёж'),
        ),
        migrations.AddField(
            model_name='incomerecord',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_records', to='objects.object', verbose_name='Объект'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='act',
            field=models.ForeignKey(blank=True, help_text='Для типа ACT_BASED', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='contracts.act', verbose_name='Акт выполненных работ'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('supplier', 'От Поставщика'), ('act_based', 'По Акту выполненных работ'), ('household', 'Хозяйственная деятельность'), ('warehouse', 'Закупка на склад'), ('internal_transfer', 'Внутренний перевод')], default='supplier', max_length=20, verbose_name='Тип счёта'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_debt',
            field=models.BooleanField(default=False, help_text='Отметить, если оплата будет отложена', verbose_name='Долговой счёт'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='skip_recognition',
            field=models.BooleanField(default=False, help_text='Не выполнять LLM-распознавание при загрузке', verbose_name='Пропустить распознавание'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='target_internal_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transfers', to='payments.expensecategory', verbose_name='Целевой счёт (для внутренних переводов)'),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='code',
            field=models.CharField(help_text='Уникальный код (например: salary, rent, profit, obj_123)', max_length=100, unique=True, verbose_name='Код счёта'),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Неактивные счета не отображаются в списках', verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Оставьте пустым для счёта верхнего уровня', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='payments.expensecategory', verbose_name='Родительский счёт'),
        ),
        migrations.AlterField(
            model_name='incomerecord',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='income_records', to='payments.expensecategory', verbose_name='Счёт плана'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='payments.expensecategory', verbose_name='Категория / счёт плана'),
        ),
        migrations.AddIndex(
            model_name='expensecategory',
            index=models.Index(fields=['account_type'], name='payments_ex_account_99453e_idx'),
        ),
        migrations.AddIndex(
            model_name='incomerecord',
            index=models.Index(fields=['income_type'], name='payments_in_income__f428ea_idx'),
        ),
        migrations.AddIndex(
            model_name='incomerecord',
            index=models.Index(fields=['object', 'payment_date'], name='payments_in_object__4361a8_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_type'], name='payments_in_invoice_122caa_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['is_debt'], name='payments_in_is_debt_eb9978_idx'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='from_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debit_entries', to='payments.expensecategory', verbose_name='Со счёта (дебет)'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='income_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='payments.incomerecord', verbose_name='Поступление'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='payments.invoice', verbose_name='Счёт на оплату'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='to_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_entries', to='payments.expensecategory', verbose_name='На счёт (кредит)'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['date'], name='payments_jo_date_ba2bbd_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['from_account', 'date'], name='payments_jo_from_ac_d6b0f8_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['to_account', 'date'], name='payments_jo_to_acco_b26c39_idx'),
        ),
    ]
