# Generated by Django 4.2.7 on 2026-02-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fns', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='fnscache',
            new_name='fns_fnscach_expires_f7bb49_idx',
            old_name='fns_fnscach_expires_idx',
        ),
        migrations.RenameIndex(
            model_name='fnsreport',
            new_name='fns_fnsrepo_counter_5de69d_idx',
            old_name='fns_fnsrepo_counter_idx',
        ),
        migrations.RenameIndex(
            model_name='fnsreport',
            new_name='fns_fnsrepo_inn_5f7d96_idx',
            old_name='fns_fnsrepo_inn_idx',
        ),
        migrations.AlterField(
            model_name='fnsreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='fnsreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
