# Generated by Django 4.2.7 on 2026-01-04 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0008_alter_payment_scan_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('provider_type', models.CharField(choices=[('openai', 'OpenAI'), ('gemini', 'Google Gemini'), ('grok', 'xAI Grok')], max_length=20, verbose_name='Тип провайдера')),
                ('model_name', models.CharField(help_text='Например: gpt-4o, gemini-1.5-pro, grok-2-vision', max_length=100, verbose_name='Название модели')),
                ('env_key_name', models.CharField(help_text='Например: OPENAI_API_KEY', max_length=100, verbose_name='Имя ENV переменной')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_default', models.BooleanField(default=False, verbose_name='По умолчанию')),
            ],
            options={
                'verbose_name': 'LLM-провайдер',
                'verbose_name_plural': 'LLM-провайдеры',
                'ordering': ['-is_default', 'provider_type'],
            },
        ),
        migrations.CreateModel(
            name='ParsedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('file_hash', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='SHA256 хэш файла')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Исходное имя файла')),
                ('file', models.FileField(blank=True, null=True, upload_to='parsed_documents/%Y/%m/', verbose_name='Файл')),
                ('raw_response', models.JSONField(blank=True, null=True, verbose_name='Сырой ответ LLM')),
                ('parsed_data', models.JSONField(blank=True, null=True, verbose_name='Распарсенные данные')),
                ('confidence_score', models.FloatField(blank=True, null=True, verbose_name='Уверенность (0.0-1.0)')),
                ('processing_time_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Время обработки (мс)')),
                ('status', models.CharField(choices=[('pending', 'В обработке'), ('success', 'Успешно'), ('failed', 'Ошибка'), ('needs_review', 'Требует проверки')], default='pending', max_length=20, verbose_name='Статус')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parsed_documents', to='payments.payment', verbose_name='Связанный платёж')),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parsed_documents', to='llm_services.llmprovider', verbose_name='Использованный провайдер')),
            ],
            options={
                'verbose_name': 'Распарсенный документ',
                'verbose_name_plural': 'Распарсенные документы',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['file_hash'], name='llm_service_file_ha_12ed2e_idx'), models.Index(fields=['status'], name='llm_service_status_951664_idx')],
            },
        ),
    ]
