# Generated by Django 4.2.7 on 2026-01-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parseddocument',
            name='retry_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Количество попыток парсинга'),
        ),
    ]
