# Generated by Django 4.2.7 on 2026-01-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_services', '0002_add_retry_count'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='parseddocument',
            index=models.Index(fields=['status', 'created_at'], name='llm_service_status_4b0e7a_idx'),
        ),
        migrations.AddIndex(
            model_name='parseddocument',
            index=models.Index(fields=['provider', 'created_at'], name='llm_service_provide_8478da_idx'),
        ),
    ]
