# Generated by Django 4.2.7 on 2026-03-27 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('llm_services', '0003_add_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmprovider',
            name='supports_web_search',
            field=models.BooleanField(default=False, help_text='Gemini с Google Search Grounding, Perplexity и т.п.', verbose_name='Поддерживает web search'),
        ),
        migrations.AlterField(
            model_name='llmprovider',
            name='provider_type',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('gemini', 'Google Gemini'), ('grok', 'xAI Grok'), ('local', 'Local LLM')], max_length=20, verbose_name='Тип провайдера'),
        ),
        migrations.CreateModel(
            name='LLMTaskConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('task_type', models.CharField(choices=[('invoice_parsing', 'Распознавание счетов'), ('product_matching', 'Подбор товаров'), ('work_matching_semantic', 'Подбор работ (semantic)'), ('work_matching_web', 'Подбор работ (web search)'), ('estimate_import', 'Импорт сметы из PDF')], max_length=50, unique=True, verbose_name='Задача')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Включена')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки оператора')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_configs', to='llm_services.llmprovider', verbose_name='Провайдер')),
            ],
            options={
                'verbose_name': 'Настройка LLM для задачи',
                'verbose_name_plural': 'Настройки LLM для задач',
                'ordering': ['task_type'],
            },
        ),
    ]
