# Generated by Django 4.2.7 on 2026-04-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_services', '0005_populate_task_configs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmtaskconfig',
            name='task_type',
            field=models.CharField(choices=[('invoice_parsing', 'Распознавание счетов'), ('product_matching', 'Подбор товаров'), ('work_matching_semantic', 'Подбор работ (semantic)'), ('work_matching_web', 'Подбор работ (web search)'), ('estimate_import', 'Импорт сметы из PDF'), ('ac_pros_cons', 'AC Rating: плюсы/минусы (AI)')], max_length=50, unique=True, verbose_name='Задача'),
        ),
    ]
