# Generated by Django 4.2.7 on 2026-02-14 10:11

from django.db import migrations, models
import django.db.models.deletion
import supply.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personnel', '0001_initial'),
        ('objects', '0006_add_registration_window_minutes'),
        ('contracts', '0012_alter_act_options_act_contracts_a_contrac_6d81aa_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitrixIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(help_text='Например: "SRM Август — Снабжение"', max_length=255, verbose_name='Название подключения')),
                ('portal_url', models.URLField(help_text='Например: https://mycompany.bitrix24.ru', verbose_name='URL портала Битрикс24')),
                ('webhook_url', models.CharField(help_text='Incoming webhook для обратных вызовов к Битрикс24 API. Формат: https://xxx.bitrix24.ru/rest/{user_id}/{secret}/', max_length=500, verbose_name='URL входящего вебхука')),
                ('outgoing_webhook_token', models.CharField(help_text='application_token из настроек Outgoing Webhook в Битрикс24', max_length=255, verbose_name='Токен исходящего вебхука')),
                ('target_category_id', models.IntegerField(default=0, help_text='0 = воронка по умолчанию', verbose_name='ID воронки (категории)')),
                ('target_stage_id', models.CharField(help_text='ID стадии "Передан в Оплату" из crm.status.list', max_length=50, verbose_name='STAGE_ID целевой стадии')),
                ('contract_field_mapping', models.CharField(blank=True, help_text='Системное имя кастомного поля (UF_CRM_xxx). Если пусто — парсинг из заголовка карточки.', max_length=100, verbose_name='Поле "Номер договора"')),
                ('object_field_mapping', models.CharField(blank=True, help_text='Системное имя кастомного поля (UF_CRM_xxx). Если пусто — парсинг из заголовка карточки.', max_length=100, verbose_name='Поле "Название объекта"')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Интеграция Битрикс24',
                'verbose_name_plural': 'Интеграции Битрикс24',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SupplyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('bitrix_deal_id', models.IntegerField(unique=True, verbose_name='ID сделки в Битрикс24')),
                ('bitrix_deal_title', models.CharField(blank=True, max_length=500, verbose_name='Заголовок карточки')),
                ('request_text', models.TextField(blank=True, help_text='Текст из комментария со словом "запрос"', verbose_name='Текст запроса')),
                ('request_file', models.FileField(blank=True, null=True, upload_to=supply.models.supply_request_file_path, verbose_name='Файл запроса')),
                ('notes', models.TextField(blank=True, help_text='Описание из карточки Битрикс, комментарии к запросу', verbose_name='Заметки')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Сумма из Битрикс')),
                ('status', models.CharField(choices=[('received', 'Получен'), ('processing', 'Обрабатывается'), ('completed', 'Завершён'), ('error', 'Ошибка')], default='received', max_length=20, verbose_name='Статус')),
                ('mapping_errors', models.JSONField(blank=True, default=dict, help_text='{"contract": "not_found", "object": "not_found"}', verbose_name='Ошибки маппинга')),
                ('raw_deal_data', models.JSONField(blank=True, default=dict, verbose_name='Данные сделки (raw)')),
                ('raw_comments_data', models.JSONField(blank=True, default=list, verbose_name='Комментарии (raw)')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата синхронизации')),
                ('bitrix_integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_requests', to='supply.bitrixintegration', verbose_name='Интеграция Битрикс24')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply_requests', to='contracts.contract', verbose_name='Договор')),
                ('object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply_requests', to='objects.object', verbose_name='Объект')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply_requests', to='personnel.employee', verbose_name='Оператор-снабженец')),
            ],
            options={
                'verbose_name': 'Запрос на снабжение',
                'verbose_name_plural': 'Запросы на снабжение',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['bitrix_deal_id'], name='supply_supp_bitrix__e30f0e_idx'), models.Index(fields=['status'], name='supply_supp_status_464948_idx'), models.Index(fields=['object', 'status'], name='supply_supp_object__697722_idx')],
            },
        ),
    ]
