# Generated by Django 5.1.15 on 2026-04-26 07:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estimate', '0005_estimate_note'),
        ('workspace', '0001_create_workspace_and_member'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecognitionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(default='pdf', max_length=20)),
                ('file_blob', models.BinaryField()),
                ('profile_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('queued', 'В очереди'), ('running', 'В работе'), ('done', 'Готово'), ('failed', 'Ошибка'), ('cancelled', 'Отменено')], default='queued', max_length=20)),
                ('pages_total', models.IntegerField(blank=True, null=True)),
                ('pages_done', models.IntegerField(default=0)),
                ('items_count', models.IntegerField(default=0)),
                ('items', models.JSONField(blank=True, default=list)),
                ('pages_summary', models.JSONField(blank=True, default=list)),
                ('llm_costs', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('cancellation_token', models.CharField(default='', max_length=64)),
                ('apply_result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recognition_jobs', to='estimate.estimate')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recognition_jobs', to='workspace.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='recognition_status_2b1423_idx'), models.Index(fields=['created_by', 'created_at'], name='recognition_created_7d3ac9_idx'), models.Index(fields=['estimate', 'created_at'], name='recognition_estimat_8e1237_idx')],
            },
        ),
    ]
