# Generated by Django 4.2.7 on 2026-03-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_add_prompts_to_searchconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft-delete: новость скрыта и не будет пересоздана discovery', verbose_name='Deleted'),
        ),
    ]
