# Generated by Django 4.2.7 on 2026-03-27 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_add_is_deleted_soft_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsDuplicateGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merged_title', models.CharField(blank=True, help_text='Объединённый заголовок из всех дубликатов', max_length=500, verbose_name='Merged Title')),
                ('merged_body', models.TextField(blank=True, help_text='Объединённый текст из всех дубликатов (сформирован LLM)', verbose_name='Merged Body')),
                ('source_count', models.IntegerField(default=0, help_text='Количество источников, в которых найдена новость', verbose_name='Source Count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'News Duplicate Group',
                'verbose_name_plural': 'News Duplicate Groups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RatingConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', help_text='Название конфигурации для идентификации', max_length=100, verbose_name='Configuration Name')),
                ('is_active', models.BooleanField(default=False, help_text='Только одна конфигурация может быть активной', verbose_name='Is Active')),
                ('primary_provider', models.CharField(choices=[('grok', 'Grok (xAI)'), ('anthropic', 'Anthropic Claude'), ('gemini', 'Google Gemini'), ('openai', 'OpenAI GPT')], default='grok', help_text='Основной провайдер для оценки', max_length=20, verbose_name='Primary Provider')),
                ('fallback_chain', models.JSONField(blank=True, default=list, help_text="Цепочка резервных провайдеров: ['anthropic', 'gemini', 'openai']", verbose_name='Fallback Chain')),
                ('temperature', models.FloatField(default=0.2, help_text='Температура LLM (0.0-1.0). Для рейтинга рекомендуется низкая (0.1-0.3)', verbose_name='Temperature')),
                ('timeout', models.IntegerField(default=120, help_text='Таймаут запроса к LLM в секундах', verbose_name='Timeout (seconds)')),
                ('grok_model', models.CharField(default='grok-4-1-fast', max_length=50, verbose_name='Grok Model')),
                ('anthropic_model', models.CharField(default='claude-3-5-haiku-20241022', max_length=50, verbose_name='Anthropic Model')),
                ('gemini_model', models.CharField(default='gemini-2.0-flash-exp', max_length=50, verbose_name='Gemini Model')),
                ('openai_model', models.CharField(default='gpt-4o', max_length=50, verbose_name='OpenAI Model')),
                ('batch_size', models.IntegerField(default=10, help_text='Количество новостей в одном батче для LLM (10-20)', verbose_name='Batch Size')),
                ('duplicate_similarity_threshold', models.FloatField(default=0.75, help_text='Порог схожести заголовков для определения дубликатов (0.0-1.0)', verbose_name='Duplicate Similarity Threshold')),
                ('grok_input_price', models.DecimalField(decimal_places=4, default=3.0, max_digits=10, verbose_name='Grok Input Price')),
                ('grok_output_price', models.DecimalField(decimal_places=4, default=15.0, max_digits=10, verbose_name='Grok Output Price')),
                ('anthropic_input_price', models.DecimalField(decimal_places=4, default=0.8, max_digits=10, verbose_name='Anthropic Input Price')),
                ('anthropic_output_price', models.DecimalField(decimal_places=4, default=4.0, max_digits=10, verbose_name='Anthropic Output Price')),
                ('gemini_input_price', models.DecimalField(decimal_places=4, default=0.075, max_digits=10, verbose_name='Gemini Input Price')),
                ('gemini_output_price', models.DecimalField(decimal_places=4, default=0.3, max_digits=10, verbose_name='Gemini Output Price')),
                ('openai_input_price', models.DecimalField(decimal_places=4, default=2.5, max_digits=10, verbose_name='OpenAI Input Price')),
                ('openai_output_price', models.DecimalField(decimal_places=4, default=10.0, max_digits=10, verbose_name='OpenAI Output Price')),
                ('prompts', models.JSONField(blank=True, default=dict, help_text='Промпты для рейтинга: {system_prompt, rating_prompt, duplicate_prompt, merge_prompt}. Пустой {} = дефолтные промпты.', verbose_name='Prompts')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Rating Configuration',
                'verbose_name_plural': 'Rating Configurations',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='RatingCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_rating', models.IntegerField(choices=[(0, '0 — Не классифицировано'), (2, '2 — Не по теме'), (3, '3 — Не интересно'), (4, '4 — Ограниченно интересно'), (5, '5 — Интересно')], help_text='Уровень звёзд, к которому относится критерий', verbose_name='Star Rating')),
                ('name', models.CharField(help_text='Короткое имя критерия для отображения в списке', max_length=255, verbose_name='Name')),
                ('description', models.TextField(help_text='Полное описание критерия для промпта LLM. Чем подробнее, тем точнее будет оценка.', verbose_name='Description')),
                ('keywords', models.JSONField(blank=True, default=list, help_text="Подсказки по ключевым словам: ['назначение', 'увольнение', 'CEO']", verbose_name='Keywords')),
                ('is_active', models.BooleanField(default=True, help_text='Неактивные критерии не участвуют в оценке', verbose_name='Is Active')),
                ('override_star_rating', models.IntegerField(blank=True, help_text='Если сработал И родитель И этот критерий, используем этот рейтинг вместо родительского', null=True, verbose_name='Override Star Rating')),
                ('order', models.IntegerField(default=0, help_text='Порядок отображения в списке', verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Rating Criterion',
                'verbose_name_plural': 'Rating Criteria',
                'ordering': ['star_rating', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RatingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_snapshot', models.JSONField(blank=True, help_text='Копия конфигурации рейтинга на момент запуска', null=True, verbose_name='Config Snapshot')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Finished At')),
                ('total_news_rated', models.IntegerField(default=0, verbose_name='Total News Rated')),
                ('total_requests', models.IntegerField(default=0, verbose_name='Total Requests')),
                ('total_input_tokens', models.IntegerField(default=0, verbose_name='Total Input Tokens')),
                ('total_output_tokens', models.IntegerField(default=0, verbose_name='Total Output Tokens')),
                ('estimated_cost_usd', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Estimated Cost (USD)')),
                ('provider_stats', models.JSONField(blank=True, default=dict, verbose_name='Provider Stats')),
                ('rating_distribution', models.JSONField(blank=True, default=dict, help_text='Распределение по звёздам: {"0": 5, "1": 20, "2": 50, "3": 200, "4": 30, "5": 10}', verbose_name='Rating Distribution')),
                ('duplicates_found', models.IntegerField(default=0, verbose_name='Duplicates Found')),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('error', 'Error')], default='running', max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Error Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Rating Run',
                'verbose_name_plural': 'Rating Runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='newspost',
            name='matched_criteria',
            field=models.JSONField(blank=True, default=list, help_text='Список ID критериев, которые сработали для этой новости', verbose_name='Matched Criteria'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='rating_explanation',
            field=models.TextField(blank=True, default='', help_text='Объяснение LLM, почему присвоен такой рейтинг', verbose_name='Rating Explanation'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='star_rating',
            field=models.IntegerField(blank=True, choices=[(0, '0 — Не классифицировано'), (1, '1 — Новостей не найдено'), (2, '2 — Не по теме'), (3, '3 — Не интересно'), (4, '4 — Ограниченно интересно'), (5, '5 — Интересно')], help_text='AI-рейтинг (0-5 звёзд). NULL = ещё не оценена.', null=True, verbose_name='Star Rating'),
        ),
        migrations.AddIndex(
            model_name='newspost',
            index=models.Index(fields=['star_rating', 'status', '-pub_date'], name='news_newspo_star_ra_0f20f3_idx'),
        ),
        migrations.AddField(
            model_name='ratingrun',
            name='discovery_run',
            field=models.ForeignKey(blank=True, help_text='Discovery-запуск, после которого был запущен рейтинг', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rating_runs', to='news.newsdiscoveryrun', verbose_name='Discovery Run'),
        ),
        migrations.AddField(
            model_name='ratingcriterion',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Родительский критерий для двухуровневой оценки', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='news.ratingcriterion', verbose_name='Parent Criterion'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='duplicate_group',
            field=models.ForeignKey(blank=True, help_text='Группа дубликатов, к которой относится эта новость', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_posts', to='news.newsduplicategroup', verbose_name='Duplicate Group'),
        ),
        migrations.AddIndex(
            model_name='ratingrun',
            index=models.Index(fields=['-created_at'], name='news_rating_created_66f254_idx'),
        ),
        migrations.AddIndex(
            model_name='ratingcriterion',
            index=models.Index(fields=['star_rating', 'is_active'], name='news_rating_star_ra_1ce8ab_idx'),
        ),
    ]
