# Generated by Django 4.2.7 on 2026-03-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0019_rating_data_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingrun',
            name='current_phase',
            field=models.CharField(blank=True, default='', help_text='Текущий этап: quick_rules / llm_rating / duplicates / completed', max_length=100, verbose_name='Current Phase'),
        ),
        migrations.AddField(
            model_name='ratingrun',
            name='processed_count',
            field=models.IntegerField(default=0, help_text='Количество уже обработанных новостей', verbose_name='Processed Count'),
        ),
        migrations.AddField(
            model_name='ratingrun',
            name='total_to_rate',
            field=models.IntegerField(default=0, help_text='Общее количество новостей для оценки', verbose_name='Total To Rate'),
        ),
    ]
