# Generated by Django 4.2.7 on 2026-04-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0022_newspost_translation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='category',
            field=models.CharField(choices=[('business', 'Деловые'), ('industry', 'Индустрия'), ('market', 'Рынок'), ('regulation', 'Регулирование'), ('review', 'Обзор'), ('guide', 'Гайд'), ('brands', 'Бренды'), ('other', 'Прочее')], default='other', help_text='Категория новости. Показывается как eyebrow-label и chip-filter в ленте.', max_length=20, verbose_name='Category'),
        ),
        # Django 4.2.7 drops SQL DEFAULT после AddField — restore через RunSQL,
        # чтобы load_ac_rating_dump / COPY старых дампов не падал NotNullViolation.
        migrations.RunSQL(
            sql="ALTER TABLE news_newspost ALTER COLUMN category SET DEFAULT 'other';",
            reverse_sql="ALTER TABLE news_newspost ALTER COLUMN category DROP DEFAULT;",
        ),
    ]
