# Generated by Django 4.2.7 on 2026-04-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0023_newspost_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='lede',
            field=models.TextField(blank=True, default='', help_text='Вводный абзац (serif 15px) отдельно от body. Если пустой — фронт берёт первые 2 абзаца body.', verbose_name='Lede'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='reading_time_minutes',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Оценка времени чтения в минутах. Если null — вычисляется из body при save().', null=True, verbose_name='Reading Time (minutes)'),
        ),
        # Django 4.2.7 drops SQL DEFAULT после AddField — restore для NOT NULL lede,
        # чтобы load_ac_rating_dump / COPY старых дампов не падал NotNullViolation.
        # reading_time_minutes nullable — дефолт не нужен.
        migrations.RunSQL(
            sql="ALTER TABLE news_newspost ALTER COLUMN lede SET DEFAULT '';",
            reverse_sql="ALTER TABLE news_newspost ALTER COLUMN lede DROP DEFAULT;",
        ),
    ]
