# Generated by Django 4.2.7 on 2026-04-21 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0024_newspost_lede_newspost_reading_time_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Имя для отображения: «Евгений Лаврентьев».', max_length=200, verbose_name='Name')),
                ('role', models.CharField(blank=True, default='', help_text='Должность/роль: «Редактор отраслевой ленты».', max_length=200, verbose_name='Role')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='news/authors/', verbose_name='Avatar')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Порядок в admin-select.', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'News Author',
                'verbose_name_plural': 'News Authors',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.AddField(
            model_name='newspost',
            name='editorial_author',
            field=models.ForeignKey(blank=True, help_text='Отображаемый автор на публичном HVAC-портале. Можно оставить пустым — тогда подпись скрывается.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='news.newsauthor', verbose_name='Editorial Author'),
        ),
    ]
