# Generated by Django 4.2.7 on 2026-04-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac_catalog', '0004_add_supplier_enrichment'),
        ('news', '0025_newsauthor_newspost_editorial_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='mentioned_ac_models',
            field=models.ManyToManyField(blank=True, help_text='AC-модели, упомянутые в новости. Показываются как «Упомянутая модель» card в детальной странице новости и в секции «Упоминания в прессе» на детальной странице модели AC.', related_name='news_mentions', to='ac_catalog.acmodel', verbose_name='Mentioned AC Models'),
        ),
    ]
