# Generated by Django 4.2.7 on 2026-04-26 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0028_seed_news_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedNewsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('category', models.ForeignKey(blank=True, db_column='category_slug', help_text='Категория, из которой берётся latest published новость для hero-блока на главной hvac-info. Если пусто — берётся latest published из всех категорий (текущее поведение).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='news.newscategory', to_field='slug', verbose_name='Featured Category')),
            ],
            options={
                'verbose_name': 'Настройки главной (featured news)',
                'verbose_name_plural': 'Настройки главной (featured news)',
            },
        ),
    ]
