# Generated by Django 4.2.7 on 2026-04-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0030_seed_featured_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='category',
            field=models.CharField(default='other', help_text='Slug категории новости. Свободная строка — справочник динамический (см. NewsCategory). Старый TextChoices enum Category остаётся как Python-helper для defaults и legacy.', max_length=64, verbose_name='Category'),
        ),
    ]
