# Generated by Django 5.1.15 on 2026-04-28 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estimate', '0005_estimate_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('base_url', models.URLField(default='https://api.openai.com')),
                ('api_key_encrypted', models.BinaryField()),
                ('extract_model', models.CharField(max_length=100)),
                ('multimodal_model', models.CharField(blank=True, default='', max_length=100)),
                ('classify_model', models.CharField(blank=True, default='', max_length=100)),
                ('vision_supported', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_llm_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'llm_profile',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(default='pdf', max_length=20)),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('cost_usd', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('items_created', models.IntegerField(default=0)),
                ('pages_processed', models.IntegerField(blank=True, null=True)),
                ('llm_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_logs', to='estimate.estimate')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_logs', to='llm_profiles.llmprofile')),
            ],
            options={
                'db_table': 'llm_import_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='llmprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='uniq_llm_profile_default'),
        ),
        migrations.AddIndex(
            model_name='importlog',
            index=models.Index(fields=['estimate', '-created_at'], name='idx_implog_est_created'),
        ),
    ]
