# Generated by Django 4.2.7 on 2026-02-14 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('notification_type', models.CharField(choices=[('new_invoice_bitrix', 'Новый счёт из Битрикс'), ('invoice_awaiting_review', 'Счёт ожидает проверки'), ('invoice_awaiting_approval', 'Счёт ожидает одобрения'), ('invoice_approved', 'Счёт одобрен'), ('invoice_rejected', 'Счёт отклонён'), ('invoice_paid', 'Счёт оплачен'), ('invoice_overdue', 'Просрочен срок оплаты'), ('mapping_error', 'Ошибка маппинга из Битрикс'), ('contract_expiring', 'Договор скоро истекает'), ('general', 'Общее')], default='general', max_length=50, verbose_name='Тип')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('data', models.JSONField(blank=True, help_text='Дополнительные данные: {"invoice_id": 123, "url": "/invoices/123"}', null=True, verbose_name='Данные')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='core_notifi_user_id_cb8f07_idx'), models.Index(fields=['user', 'notification_type'], name='core_notifi_user_id_aa1102_idx')],
            },
        ),
    ]
