# Generated by Django 4.2.7 on 2026-02-18 18:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kanban_core', '0004_alter_card_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('erp_object_id', models.BigIntegerField(blank=True, null=True)),
                ('erp_object_name', models.CharField(blank=True, max_length=255)),
                ('system_name', models.CharField(blank=True, max_length=255, verbose_name='Система')),
                ('erp_counterparty_id', models.BigIntegerField(blank=True, null=True)),
                ('erp_counterparty_name', models.CharField(blank=True, max_length=500)),
                ('erp_tkp_ids', models.JSONField(blank=True, default=list, verbose_name='ID привязанных ТКП')),
                ('contacts_info', models.TextField(blank=True, verbose_name='Контакты потенциального заказчика')),
                ('comments', models.TextField(blank=True, verbose_name='Комментарии')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_case', to='kanban_core.card')),
            ],
            options={
                'verbose_name': 'CommercialCase',
                'verbose_name_plural': 'CommercialCases',
            },
        ),
    ]
